Repository flexera-public/policy_templates, pull requests merged in 2018-06, with the labels that each got.

#8 PSASSET-824 Old Snapshots
  README.md
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/README.md
  cost/volumes/old_snapshots/old_snapshot.pt
Labels: READY-FOR-REVIEW

#38 PSASSET-826 Security Group: High Open Ports
  README.md
  security/security_groups/high_open_ports/CHANGELOG.md
  security/security_groups/high_open_ports/README.md
  security/security_groups/high_open_ports/open_ports.pt
Labels: READY-FOR-REVIEW

#42 PSASSET-793 AWS Connection Key Rotation Policy Template
  README.md
  operational/cloud_credentials/aws/README.md
  operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
  operational/cloud_credentials/aws/changelog.md
Labels: READY-FOR-REVIEW

#55 PSASSET-867 Pretty Generate
  Rakefile
  active-policy-list.json
Labels: repo_maintenance

#57 Updating policy sync readme
  operational/policy_sync/README.md
Labels: repo_maintenance

#56 Adding in Danger Systems to verify changelog and readme, enable support for future rules
  .travis.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: repo_maintenance

#58 Psasset 864 policy upload scripting
  tools/policy_upload_scripts/CHANGELOG.md
  tools/policy_upload_scripts/README.md
  tools/policy_upload_scripts/policy_bootstrapper.py
  tools/policy_upload_scripts/support_modules/rs_account_info.py
  tools/policy_upload_scripts/support_modules/rs_auth.py
  tools/policy_upload_scripts/support_modules/rs_user_info.py
  tools/policy_upload_scripts/test_code/unapply_delete_all_policies.py
Labels: READY-FOR-REVIEW

#47 PSASSET-830 No Recent Snapshots Policy Template
  .travis.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  README.md
  active-policy-list.json
  operational/snapshots/CHANGELOG.md
  operational/snapshots/README.md
  operational/snapshots/no_recent_snapshots.pt
Labels: READY-FOR-REVIEW

#62 Adding a screenshot to make it better and easier to follow.
  operational/policy_sync/README.md
  operational/policy_sync/policy_sync.png
Labels: repo_maintenance

#64 Moving policy sync out of operational to tools directory
  active-policy-list.json
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/README.md
  tools/policy_sync/policy_sync.png
  tools/policy_sync/policy_sync.pt
  tools/policy_upload_scripts/policy_bootstrapper.py
  tools/policy_upload_scripts/test_code/unapply_delete_all_policies.py
Labels: repo_maintenance

#67 Updating templates to add the resource count
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/downsize-instance.pt
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: enhancement

#68 Policy bootstrap script enhancements and fixes
  tools/policy_upload_scripts/CHANGELOG.md
  tools/policy_upload_scripts/README.md
  tools/policy_upload_scripts/policy_bootstrapper.py
Labels: bug, enhancement

#70 Added support for "exclusion" tags.
  active-policy-list.json
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/README.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: enhancement

#73 Psasset 833 - fix error with no resources
  Dangerfile
  compliance/tags/tag_checker/changelog.md
  compliance/tags/tag_checker/tag_checker.pt
Labels: READY-FOR-REVIEW

#74 Danger update
  README.md
  compliance/tags/tag_checker/CHANGELOG.md
Labels: repo_maintenance
