Repository flexera-public/policy_templates, pull requests merged in 2018-07, with the labels that each got.

#77 Uav support for new email and delete parameter
  Dangerfile
  active-policy-list.json
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: bug

#84 Lowering the severity of the sec group policy
  security/security_groups/rules_without_descriptions/CHANGELOG.md
  security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
Labels: enhancement

#85 Updating policy upload tool instructions and typo
  tools/policy_upload_scripts/README.md
Labels: enhancement

#87 Adding permissions required to run the policy
  cost/volumes/unattached_volumes/uav_policy.pt
  security/security_groups/high_open_ports/CHANGELOG.md
  security/security_groups/high_open_ports/open_ports.pt
  security/security_groups/icmp_enabled/CHANGELOG.md
  security/security_groups/icmp_enabled/icmp_enabled.pt
  security/security_groups/rules_without_descriptions/CHANGELOG.md
  security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
Labels: enhancement

#88 Adding permissions block to RI coverage policy - git issue 82
  cost/aws/reserved_instances/coverage/CHANGELOG.md
  cost/aws/reserved_instances/coverage/reserved_instance_coverage.pt
Labels: enhancement

#91 Actions resolutions labels account name id mk ii
  active-policy-list.json
  compliance/tags/tag_checker/CHANGELOG.md
  compliance/tags/tag_checker/tag_checker.pt
  cost/aws/reserved_instances/coverage/CHANGELOG.md
  cost/aws/reserved_instances/coverage/reserved_instance_coverage.pt
  cost/aws/reserved_instances/expiration/CHANGELOG.md
  cost/aws/reserved_instances/expiration/expired_ris.pt
  cost/aws/reserved_instances/utilization/utilization_ris.pt
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/downsize-instance-add-tags.pt
  cost/downsize_instance/downsize-instance.pt
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/uav_policy.pt
  operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
  operational/cloud_credentials/aws/changelog.md
  operational/snapshots/CHANGELOG.md
  operational/snapshots/no_recent_snapshots.pt
  security/security_groups/high_open_ports/CHANGELOG.md
  security/security_groups/high_open_ports/open_ports.pt
  security/security_groups/icmp_enabled/CHANGELOG.md
  security/security_groups/icmp_enabled/icmp_enabled.pt
  security/security_groups/rules_without_descriptions/CHANGELOG.md
  security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
  security/storage/aws/public_buckets/CHANGELOG.md
  security/storage/aws/public_buckets/aws_public_buckets.pt
  security/storage/google/public_buckets/CHANGELOG.md
  security/storage/google/public_buckets/google_public_buckets.pt
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: enhancement

#18 Schedule Instance Policy - WIP
  README.md
  active-policy-list.json
  cost/schedule_instances/CHANGELOG.md
  cost/schedule_instances/README.md
  cost/schedule_instances/schedule_instances.pt
Labels: READY-FOR-REVIEW

#94 PSASSET-874 - fixing check and updating versioning, fixes #93
  active-policy-list.json
  cost/schedule_instances/schedule_instances.pt
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
Labels: READY-FOR-REVIEW, bug
