Repository flexera-public/policy_templates, pull requests merged in 2018-08, with the labels that each got.

#97 update the readme link
  active-policy-list.json
  cost/schedule_instances/CHANGELOG.md
  cost/schedule_instances/schedule_instances.pt
Labels: READY-FOR-REVIEW

#98 Schedule Instance Policy - Fix Version
  active-policy-list.json
  cost/schedule_instances/CHANGELOG.md
  cost/schedule_instances/schedule_instances.pt
Labels: READY-FOR-REVIEW

#100 Make Dangerfile actually valid
  Dangerfile
Labels: repo_maintenance

#101 Updating policy templates name for consistency
  active-policy-list.json
  compliance/tags/tag_checker/README.md
  compliance/tags/tag_checker/tag_checker.pt
  cost/aws/reserved_instances/coverage/README.md
  cost/aws/reserved_instances/expiration/README.md
  cost/aws/reserved_instances/utilization/README.md
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/downsize-instance-add-tags.pt
  cost/downsize_instance/downsize-instance.pt
  cost/schedule_instances/CHANGELOG.md
  cost/schedule_instances/README.md
  cost/schedule_instances/schedule_instances.pt
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/README.md
  cost/volumes/old_snapshots/old_snapshot.pt
  cost/volumes/unattached_volumes/README.md
  cost/volumes/unattached_volumes/uav_policy.pt
  operational/cloud_credentials/aws/README.md
  operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
  operational/cloud_credentials/aws/changelog.md
  operational/snapshots/CHANGELOG.md
  operational/snapshots/no_recent_snapshots.pt
  security/security_groups/high_open_ports/CHANGELOG.md
  security/security_groups/high_open_ports/README.md
  security/security_groups/high_open_ports/open_ports.pt
  security/security_groups/icmp_enabled/CHANGELOG.md
  security/security_groups/icmp_enabled/README.md
  security/security_groups/icmp_enabled/icmp_enabled.pt
  security/security_groups/rules_without_descriptions/CHANGELOG.md
  security/security_groups/rules_without_descriptions/README.md
  security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
  security/storage/aws/public_buckets/CHANGELOG.md
  security/storage/aws/public_buckets/aws_public_buckets.pt
  security/storage/google/public_buckets/CHANGELOG.md
  security/storage/google/public_buckets/google_public_buckets.pt
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
  tools/policy_upload_scripts/support_modules/rs_auth.pyc
  tools/policy_upload_scripts/support_modules/rs_user_info.pyc
Labels: enhancement

#102 PSASSET-860 - Security Group Rules without Descriptions
  active-policy-list.json
  security/security_groups/rules_without_descriptions/CHANGELOG.md
  security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
Labels: READY-FOR-REVIEW, enhancement

#96 Beginning updates for policy sync
  .gitignore
  .travis.yml
  Rakefile
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW

#92 Psasset 837 issue78 tags in report
  active-policy-list.json
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: enhancement

#107 Added support slack notification
  active-policy-list.json
  security/storage/aws/public_buckets/CHANGELOG.md
  security/storage/aws/public_buckets/README.md
  security/storage/aws/public_buckets/aws_public_buckets.pt
Labels: enhancement

#111 fixing a typo
  active-policy-list.json
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
Labels: bug

#106 Tag example needs to use semi-colons instead of colons
  cost/schedule_instances/README.md
Labels: bug

#112 Aws key rotation log typo
  operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
  operational/cloud_credentials/aws/changelog.md
Labels: bug

#114 RI Utilization Policy - Fixes Email Formatting.
  cost/aws/reserved_instances/utilization/CHANGELOG.md
  cost/aws/reserved_instances/utilization/utilization_ris.pt
Labels: bug

#113 Policy Sync, adding update for existing policies
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: bug

#115 AWS RDS Backup Settings - Initial Release
  operational/dbaas/aws/rds_backup/CHANGELOG.md
  operational/dbaas/aws/rds_backup/README.md
  operational/dbaas/aws/rds_backup/aws_rds_backup.pt
Labels: READY-FOR-REVIEW

#116 Fix Top Level README
  README.md
Labels: repo_maintenance

#118 Policy_Bootstrapper: Removing in favor of catalog.
  tools/policy_upload_scripts/CHANGELOG.md
  tools/policy_upload_scripts/README.md
  tools/policy_upload_scripts/policy_bootstrapper.py
  tools/policy_upload_scripts/support_modules/rs_account_info.py
  tools/policy_upload_scripts/support_modules/rs_account_info.pyc
  tools/policy_upload_scripts/support_modules/rs_auth.py
  tools/policy_upload_scripts/support_modules/rs_auth.pyc
  tools/policy_upload_scripts/support_modules/rs_user_info.py
  tools/policy_upload_scripts/support_modules/rs_user_info.pyc
  tools/policy_upload_scripts/test_code/unapply_delete_all_policies.py
Labels: READY-FOR-REVIEW

#117 RI Utilization Policy - Fix Rounding
  cost/aws/reserved_instances/utilization/CHANGELOG.md
  cost/aws/reserved_instances/utilization/README.md
  cost/aws/reserved_instances/utilization/utilization_ris.pt
Labels: READY-FOR-REVIEW

#120 Policy Sync Tool: Adding in changelog url
  Rakefile
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW

#123 Repo Maintenance
  LICENSE
  README.md
Labels: READY-FOR-REVIEW, repo_maintenance

#122 Aws key rotation issue 121
  operational/cloud_credentials/aws/README.md
  operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
  operational/cloud_credentials/aws/changelog.md
Labels: bug, enhancement
