Repository flexera-public/policy_templates, pull requests merged in 2018-10, with the labels that each got.

#128 skip_excluded_resources_from_ds_volume_attachments_iteration
  operational/snapshots/CHANGELOG.md
  operational/snapshots/no_recent_snapshots.pt
Labels: READY-FOR-REVIEW, bug

#130 Issue 126 uav delete error handling
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/README.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: bug, enhancement

#131 Initial Release: RI Report by BC
  active-policy-list.json
  cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
  cost/aws/reserved_instances/report_by_bc/README.md
  cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
Labels: New Policy, READY-FOR-REVIEW

#133 Initial Release: Azure Disallowed Regions
  README.md
  compliance/azure/azure_disallowed_regions/CHANGELOG.md
  compliance/azure/azure_disallowed_regions/README.md
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
  cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
Labels: New Policy, READY-FOR-REVIEW
