Repository flexera-public/policy_templates, pull requests merged in 2019-09, with the labels that each got.

#307 Pol 47 azure ahub utilization with manual entry
  README.md
  compliance/azure/ahub_manual/Azure_AHUB_Utilization_with_Manual_Entry.pt
  compliance/azure/ahub_manual/CHANGELOG.md
  compliance/azure/ahub_manual/README.md
Labels: New Policy, READY-FOR-REVIEW

#304 Pol 21
  README.md
  cost/aws/s3_bucket_size/CHANGELOG.md
  cost/aws/s3_bucket_size/README.md
  cost/aws/s3_bucket_size/aws_bucket_size.pt
Labels: New Policy, READY-FOR-REVIEW

#298 Add schedule fnms reports
  README.md
  operational/fnms/schedule_fnms_reports/CHANGELOG.md
  operational/fnms/schedule_fnms_reports/README.md
  operational/fnms/schedule_fnms_reports/images/APIToken.png
  operational/fnms/schedule_fnms_reports/images/CMP_NewToken.png
  operational/fnms/schedule_fnms_reports/images/CreateServeceAccount.png
  operational/fnms/schedule_fnms_reports/images/FNMS_cv_Report.png
  operational/fnms/schedule_fnms_reports/images/ReportNumber.png
  operational/fnms/schedule_fnms_reports/images/WebServiceRole.png
  operational/fnms/schedule_fnms_reports/images/email_output.png
  operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
Labels: New Policy, READY-FOR-REVIEW, good first issue

#308 update github org in path
  CODEOWNERS
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
  tools/travis/build_docs.sh
Labels: READY-FOR-REVIEW

#309 update readme to include RCA-V
  cost/volumes/old_snapshots/README.md
Labels: READY-FOR-REVIEW

#311 fix readme link
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
Labels: READY-FOR-REVIEW

#312 - Minor Doc changes
  operational/fnms/schedule_fnms_reports/CHANGELOG.md
  operational/fnms/schedule_fnms_reports/README.md
Labels: READY-FOR-REVIEW

#316 update policy name to reflect supported cloud.
  cost/aws/reserved_instances/utilization/CHANGELOG.md
  cost/aws/reserved_instances/utilization/README.md
  cost/aws/reserved_instances/utilization/utilization_ris.pt
Labels: READY-FOR-REVIEW

#322 Google Idle Compute Instances
  README.md
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/README.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
Labels: New Policy, READY-FOR-REVIEW

#328 AWS Idle Cleanup
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/README.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
Labels: READY-FOR-REVIEW

#324 AWS Unused RDS Instances
  README.md
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/README.md
  cost/aws/unused_rds/unused_rds.pt
Labels: New Policy, READY-FOR-REVIEW

#321 Google Unutilized IP Addresses
  cost/aws/instance_cloudwatch_utilization/README.md
  cost/google/unutilized_ip_addresses/CHANGELOG.md
  cost/google/unutilized_ip_addresses/README.md
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Labels: READY-FOR-REVIEW, enhancement

#329 Pol 104 aws object storage optimization
  README.md
  cost/aws/object_storage_optimization/CHANGELOG.md
  cost/aws/object_storage_optimization/README.md
  cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
Labels: New Policy, READY-FOR-REVIEW

#330 Google CUD Expiration
  README.md
  cost/google/cud_expiration/CHANGELOG.md
  cost/google/cud_expiration/Google_CUD_Expiration_Report.pt
  cost/google/cud_expiration/README.md
Labels: READY-FOR-REVIEW

#331 adding request_approval block
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/README.md
  cost/downsize_instance/downsize_instance.pt
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/README.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: READY-FOR-REVIEW

#290 Enhancement: Link to Billing Center in Email Report
  compliance/billing_center_access_report/CHANGELOG.md
  compliance/billing_center_access_report/bc_access_report.pt
Labels: enhancement

#333 POL-106 Google Object Storage Optimization
  README.md
  cost/google/object_storage_optimization/CHANGELOG.md
  cost/google/object_storage_optimization/README.md
  cost/google/object_storage_optimization/google_object_storage_optimization.pt
Labels: New Policy, READY-FOR-REVIEW

#336 POL-104 modified constructing S3 bucket endpoint.
  cost/aws/object_storage_optimization/CHANGELOG.md
  cost/aws/object_storage_optimization/README.md
  cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
Labels: bug, changelog

#335 Azure RI Expiration
  cost/azure/reserved_instances/expiration/CHANGELOG.md
  cost/azure/reserved_instances/expiration/README.md
  cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
Labels: New Policy, READY-FOR-REVIEW

#334 Google Unused CloudSQL Instances
  cost/google/unused_cloudsql_instances/CHANGELOG.md
  cost/google/unused_cloudsql_instances/README.md
  cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt
Labels: New Policy, READY-FOR-REVIEW

#332 POL-105-Azure Blob Storage Optimization
  README.md
  cost/azure/object_storage_optimization/CHANGELOG.md
  cost/azure/object_storage_optimization/README.md
  cost/azure/object_storage_optimization/azure_object_storage_optimization.pt
Labels: New Policy, READY-FOR-REVIEW

#314 Azure Idle Compute Instances
  README.md
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/README.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Labels: New Policy, READY-FOR-REVIEW

#338 some minor clean up
  README.md
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/reserved_instances/expiration/CHANGELOG.md
  cost/aws/reserved_instances/expiration/README.md
  cost/aws/reserved_instances/expiration/expired_ris.pt
  cost/azure/reserved_instances/expiration/CHANGELOG.md
  cost/azure/reserved_instances/expiration/README.md
  cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
  cost/google/cud_expiration/CHANGELOG.md
  cost/google/cud_expiration/Google_CUD_Expiration_Report.pt
  cost/google/cud_expiration/README.md
  cost/google/cud_report/CHANGELOG.md
  cost/google/cud_report/Google_Committed_UseDiscount_Report.pt
  cost/google/cud_report/README.md
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
Labels: READY-FOR-REVIEW

#339 AWS RDS RightSizing
  README.md
  cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/rds_instance_cloudwatch_utilization/README.md
  cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
  data/aws/instance_types.json
Labels: New Policy, READY-FOR-REVIEW

#315 Azure Rightsize SQL Instances
  README.md
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/README.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
Labels: New Policy, READY-FOR-REVIEW

#323 Google Rightsize Cloud SQL Instances
  README.md
  cost/google/cloudsql_rightsizing/CHANGELOG.md
  cost/google/cloudsql_rightsizing/README.md
  cost/google/cloudsql_rightsizing/google_cloudsql_rightsizing.pt
  data/google/instance_types.json
Labels: New Policy, READY-FOR-REVIEW

#340 update short description, name and readme
  compliance/azure/azure_long_stopped_instances/CHANGELOG.md
  compliance/azure/azure_long_stopped_instances/README.md
  compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
  compliance/unapproved_instance_types/CHANGELOG.md
  compliance/unapproved_instance_types/README.md
  compliance/unapproved_instance_types/unapproved_instance_types.pt
Labels: READY-FOR-REVIEW

#345 RDS RightSizing Fixing json path
  cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
Labels: enhancement

#346 Updating Burstable Template to fix items
  cost/aws/burstable_instance_cloudwatch_credit_utilization/CHANGELOG.md
  cost/aws/burstable_instance_cloudwatch_credit_utilization/README.md
  cost/aws/burstable_instance_cloudwatch_credit_utilization/aws_burstable_instance_cloudwatch_credit_utilization.pt
Labels: enhancement

#347 Pol 109 approval block
  compliance/tags/azure_rg_tags/CHANGELOG.md
  compliance/tags/azure_rg_tags/azure_resource_group_tags.pt
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
  cost/azure/instances_log_analitics_utilization/CHANGELOG.md
  cost/azure/instances_log_analitics_utilization/azure_instance_log_analytics_utilization.pt
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/downsize_instance.pt
  cost/schedule_instances/CHANGELOG.md
  cost/schedule_instances/schedule_instances.pt
  cost/superseded_instance_remediation/CHANGELOG.md
  cost/superseded_instance_remediation/superseded_instance_remediation.pt
  cost/terminate_policy/CHANGELOG.md
  cost/terminate_policy/instance_terminate.pt
  cost/unattached_addresses/CHANGELOG.md
  cost/unattached_addresses/unattached_addresses.pt
  operational/aws/subnet_name_sync/CHANGELOG.md
  operational/aws/subnet_name_sync/aws_subnet_name_sync.pt
  operational/aws/vpc_name_sync/CHANGELOG.md
  operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
  operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
  operational/cloud_credentials/aws/changelog.md
  operational/snapshots/CHANGELOG.md
  operational/snapshots/no_recent_snapshots.pt
  operational/vmware/instance_tag_sync/changelog.md
  operational/vmware/instance_tag_sync/instance_tag_sync.pt
  security/security_groups/world_open_ports/CHANGELOG.md
  security/security_groups/world_open_ports/security_group_rules_with_world_open_ports.pt
  security/storage/aws/public_buckets/CHANGELOG.md
  security/storage/aws/public_buckets/aws_public_buckets.pt
  security/storage/aws/s3_buckets_without_server_access_logging/CHANGELOG.md
  security/storage/aws/s3_buckets_without_server_access_logging/aws_s3_buckets_without_server_access_logging.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#349 Pol-110 Added tenancy "single" in metadata modified(.pt, changelog and readme…
  compliance/billing_center_access_report/CHANGELOG.md
  compliance/billing_center_access_report/README.md
  compliance/billing_center_access_report/bc_access_report.pt
  compliance/github/available_seats/CHANGELOG.md
  compliance/github/available_seats/available_seats.pt
  compliance/github/outside_collaborators/CHANGELOG.md
  compliance/github/outside_collaborators/outside_collaborators.pt
  compliance/github/repository_admin_team/CHANGELOG.md
  compliance/github/repository_admin_team/repository_admin_team.pt
  compliance/github/repository_branch_protection/CHANGELOG.md
  compliance/github/repository_branch_protection/repository_branch_protection.pt
  compliance/github/repository_naming/CHANGELOG.md
  compliance/github/repository_naming/repository_naming.pt
  compliance/github/repository_size/CHANGELOG.md
  compliance/github/repository_size/repository_size.pt
  compliance/github/toplevel_teams/CHANGELOG.md
  compliance/github/toplevel_teams/toplevel_teams.pt
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/README.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/README.md
  cost/budget_alerts/budget_alert.pt
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/low_account_usage.pt
  cost/low_service_usage/CHANGELOG.md
  cost/low_service_usage/low_service_usage.pt
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
  fsm/okta/inactive_users/CHANGELOG.md
  fsm/okta/inactive_users/README.md
  fsm/okta/inactive_users/okta-inactive-users.pt
  operational/fnms/schedule_fnms_reports/CHANGELOG.md
  operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#350 superseded instances v1.4
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/README.md
  cost/superseded_instance/superseded_instance.pt
Labels: READY-FOR-REVIEW, bug

#348 Pol 43 check for azure instances not running fnms agent
  README.md
  compliance/azure/instances_without_fnm_agent/Azure_Instances_not_running_FlexNet_Inventory_Agent.pt
  compliance/azure/instances_without_fnm_agent/CHANGELOG.md
  compliance/azure/instances_without_fnm_agent/README.md
  compliance/azure/instances_without_fnm_agent/images/APIToken.png
  compliance/azure/instances_without_fnm_agent/images/CMP_NewToken.png
  compliance/azure/instances_without_fnm_agent/images/CreateServeceAccount.png
  compliance/azure/instances_without_fnm_agent/images/FNMS_cv_Report.png
  compliance/azure/instances_without_fnm_agent/images/Filter_FNMS_Report.PNG
  compliance/azure/instances_without_fnm_agent/images/ReportNumber.png
  compliance/azure/instances_without_fnm_agent/images/WebServiceRole.png
  compliance/azure/instances_without_fnm_agent/images/email_output.png
Labels: New Policy, READY-FOR-REVIEW

#352 POL-116 adding Saas Manger
  Rakefile
Labels: READY-FOR-REVIEW
