Repository flexera-public/policy_templates, pull requests merged in 2019-02, with the labels that each got.

#173 Budget Alerts - Round Spend
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW, enhancement

#174 removing deprecated list, and updating rake
  Rakefile
  active-policy-list.json
  compliance/tags/tag_checker/tag_checker.pt
  cost/downsize_instance/downsize-instance-add-tags.pt
  cost/downsize_instance/downsize-instance.pt
  cost/schedule_instances/schedule_instances.pt
  operational/dbaas/aws/rds_backup/aws_rds_backup.pt
  operational/snapshots/no_recent_snapshots.pt
Labels: changelog, repo_maintenance

#177 Scheduled Report Policy - Monday Bug Fix
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW, bug

#180 Use billing center names
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW

#181 Scheduled Report - Increment Version Identifier to 1.3
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW, changelog, repo_maintenance

#178 Budget Alerts - Update to new API
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW, enhancement

#182 Scheduled Report - 6mo Utilization Chart
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW, enhancement

#172 Policy Sync: Updating versioning - comparing major and minor versions
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: bug

#184 Billing Center Cost Anomaly - Initial Release
  README.md
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/README.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
  cost/budget_alerts/README.md
Labels: New Policy, READY-FOR-REVIEW

#185 Fix typo
  README.md
Labels: READY-FOR-REVIEW

#188 readme disclaimers
  compliance/billing_center_access_report/README.md
  cost/aws/reserved_instances/expiration/README.md
  cost/aws/reserved_instances/report_by_bc/README.md
  cost/aws/reserved_instances/utilization/README.md
  cost/azure/reserved_instances/utilization/README.md
  cost/billing_center_cost_anomaly/README.md
  cost/budget_alerts/README.md
  cost/scheduled_reports/README.md
Labels: READY-FOR-REVIEW, repo_maintenance

#186 Allow for chart dimension to be selectable
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW, enhancement
