Repository flexera-public/policy_templates, pull requests merged in 2019-11, with the labels that each got.

#383 POL-140: Organize the root readme.
  README.md
Labels: READY-FOR-REVIEW

#353 Danger updates
  .mdlrc
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: READY-FOR-REVIEW

#394 fix issues with link check
  Dangerfile
Labels: READY-FOR-REVIEW

#393 POL-147 - AWS Savings Plan Recos
  README.md
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/README.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
Labels: READY-FOR-REVIEW

#392 POL-98 - Azure Migrate
  README.md
  operational/azure/azure_migrate/README.md
  operational/azure/azure_migrate/changelog.md
  operational/azure/azure_migrate/risc-azure-migrate.pt
Labels: READY-FOR-REVIEW

#390 Pol 42 aws instances not running flexnet inventory agent
  README.md
  compliance/aws/instances_without_fnm_agent/CHANGELOG.md
  compliance/aws/instances_without_fnm_agent/README.md
  compliance/aws/instances_without_fnm_agent/aws_instances_not_running_flexnet_inventory_agent.pt
  compliance/aws/instances_without_fnm_agent/images/APIToken.png
  compliance/aws/instances_without_fnm_agent/images/CMP_NewToken.png
  compliance/aws/instances_without_fnm_agent/images/CreateServeceAccount.png
  compliance/aws/instances_without_fnm_agent/images/FNMS_cv_Report.png
  compliance/aws/instances_without_fnm_agent/images/Filter_FNMS_Report.PNG
  compliance/aws/instances_without_fnm_agent/images/ReportNumber.png
  compliance/aws/instances_without_fnm_agent/images/WebServiceRole.png
  compliance/aws/instances_without_fnm_agent/images/email_output.png
Labels: New Policy, READY-FOR-REVIEW

#391 POL 112 azure rightsize sql databases
  README.md
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/README.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  data/azure/sql_service_tier_types.json
Labels: READY-FOR-REVIEW, changelog, enhancement

#397 Update Policy Actions section
  README_GUIDELINE.md
Labels: READY-FOR-REVIEW

#389 POL-41 Google - Check for long-stopped instances
  README.md
  compliance/google/long_stopped_instances/CHANGELOG.md
  compliance/google/long_stopped_instances/README.md
  compliance/google/long_stopped_instances/google_long_stopped_instances.pt
Labels: New Policy, READY-FOR-REVIEW

#399 check for valid hosts
  Dangerfile
Labels: READY-FOR-REVIEW

#398 POL-26-AWS - Check for long-stopped instances
  README.md
  compliance/aws/long_stopped_instances/CHANGELOG.md
  compliance/aws/long_stopped_instances/README.md
  compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt
Labels: New Policy, READY-FOR-REVIEW

#388 POL-136 Run fpt check during pull request
  .travis.yml
  Dangerfile
Labels: READY-FOR-REVIEW, enhancement

#403 Repo Maintenance
  README.md
  saas/okta/inactive_users/CHANGELOG.md
  saas/okta/inactive_users/README.md
  saas/okta/inactive_users/okta-inactive-users.pt
Labels: READY-FOR-REVIEW, repo_maintenance

#401 danger updates
  Dangerfile
Labels: DO-NOT-MERGE, READY-FOR-REVIEW

#410 Lowercase check
  Dangerfile
Labels: READY-FOR-REVIEW

#411 POL-152 update billing center cost anomalies
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/README.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#412 POL-156 update azure readme
  compliance/azure/azure_long_stopped_instances/README.md
  compliance/azure/instances_without_fnm_agent/README.md
  cost/azure/idle_compute_instances/README.md
  operational/azure/azure_migrate/README.md
  operational/azure/vms_without_managed_disks/README.md
Labels: READY-FOR-REVIEW

#413 POL-159 Dangerfile http response code check
  Dangerfile
Labels: READY-FOR-REVIEW
