Repository flexera-public/policy_templates, pull requests merged in 2019-04, with the labels that each got.

#207 Repo Maintenance - Update AWS VPC and Subnet Sync Policies
  operational/aws/subnet_name_sync/README.md
  operational/aws/subnet_name_sync/aws_subnet_name_sync.pt
  operational/aws/subnet_name_sync/changelog.md
  operational/aws/vpc_name_sync/README.md
  operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
  operational/aws/vpc_name_sync/changelog.md
Labels: READY-FOR-REVIEW, repo_maintenance

#208 Repo Maintenance: Remove old PT files for VPC and Subnet sync
  operational/aws/subnet_name_sync/subnets_sync.pt
  operational/aws/vpc_name_sync/vpc_sync.pt
Labels: READY-FOR-REVIEW, repo_maintenance

#199 Update email template schedule instance
  cost/schedule_instances/CHANGELOG.md
  cost/schedule_instances/schedule_instances.pt
Labels: READY-FOR-REVIEW

#210 Azure CSP Cheaper Regions
  README.md
  cost/azure/csp/cheaper_regions/CHANGELOG.md
  cost/azure/csp/cheaper_regions/README.md
  cost/azure/csp/cheaper_regions/azure_cheaper_regions.pt
Labels: New Policy, READY-FOR-REVIEW

#214 Migration Cheaper Regions from Azure to Multi-Cloud
  README.md
  cost/azure/csp/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/README.md
  cost/cheaper_regions/cheaper_regions.pt
Labels: READY-FOR-REVIEW, enhancement

#205 Pol 34 AWS delete unused ELB(CLB)
  README.md
  cost/aws/elb/clb_unused/AWS_Delete_Unused_CLB.pt
  cost/aws/elb/clb_unused/CHANGELOG.md
  cost/aws/elb/clb_unused/README.md
Labels: New Policy, READY-FOR-REVIEW

#212 Scheduled Report Enhancements
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/currency_reference.json
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW, enhancement

#217 POL-34-Removed Reference URL
  cost/aws/elb/clb_unused/AWS_Delete_Unused_CLB.pt
  cost/aws/elb/clb_unused/CHANGELOG.md
Labels: READY-FOR-REVIEW
