Repository flexera-public/policy_templates, pull requests merged in 2019-12, with the labels that each got.

#404 POL-90 FSM Unsanctioned Spend Alerts
  README.md
  saas/fsm/unsanctioned_spend/CHANGELOG.md
  saas/fsm/unsanctioned_spend/README.md
  saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
Labels: New Policy, READY-FOR-REVIEW

#405 POL-86 FSM Suspicious Users
  README.md
  saas/fsm/suspicious_users/CHANGELOG.md
  saas/fsm/suspicious_users/README.md
  saas/fsm/suspicious_users/fsm-suspicious_users.pt
Labels: New Policy, READY-FOR-REVIEW

#406 POL-87 SaaS Manager - User Status Change
  README.md
  saas/fsm/user_status_change/CHANGELOG.md
  saas/fsm/user_status_change/README.md
  saas/fsm/user_status_change/fsm-user_status_change.pt
Labels: New Policy, READY-FOR-REVIEW

#407 POL-89 SaaS Manager - Renewal Reminder
  README.md
  saas/fsm/renewal_reminder/CHANGELOG.md
  saas/fsm/renewal_reminder/README.md
  saas/fsm/renewal_reminder/fsm-renewal_reminder.pt
Labels: New Policy, READY-FOR-REVIEW

#408 POL-85 Office 365 Security Alerts
  Dangerfile
  README.md
  saas/office365/security_alerts/CHANGELOG.md
  saas/office365/security_alerts/README.md
  saas/office365/security_alerts/o365-security-alerts.pt
Labels: New Policy, READY-FOR-REVIEW

#400 Update instance_types.json
  data/aws/instance_types.json
Labels: bug

#414 POL-28 Disallowed Cloud Images
  README.md
  compliance/disallowed_images/CHANGELOG.md
  compliance/disallowed_images/README.md
  compliance/disallowed_images/disallowed_cloud_images.pt
Labels: New Policy, READY-FOR-REVIEW

#416 POL-157 Added FNMS on-premise support
  .mdlrc
  operational/fnms/schedule_fnms_reports/CHANGELOG.md
  operational/fnms/schedule_fnms_reports/README.md
  operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
Labels: READY-FOR-REVIEW

#402 POL-57-Update to Budget Alerts Policy
  Dangerfile
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#418 POL-157 Version changed to 1.5 to match the new changes
  operational/fnms/schedule_fnms_reports/CHANGELOG.md
  operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
Labels: READY-FOR-REVIEW

#419 Update budget_alert.pt
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW, enhancement

#420 POL-163 read info field
  Dangerfile
  Rakefile
  tools/lib/policy_parser.rb
Labels: READY-FOR-REVIEW

#421 POL-162-Date format defect fixed
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/superseded_instance.pt
Labels: bug, changelog
