Repository flexera-public/policy_templates, pull requests merged in 2019-01, with the labels that each got.

#145 Add Inputs and Actions to README's
  compliance/azure/azure_disallowed_regions/README.md
  compliance/billing_center_access_report/README.md
  compliance/tags/tag_checker/README.md
  cost/aws/reserved_instances/coverage/README.md
  cost/aws/reserved_instances/expiration/README.md
  cost/aws/reserved_instances/report_by_bc/README.md
  cost/aws/reserved_instances/utilization/README.md
  cost/downsize_instance/README.md
  cost/schedule_instances/README.md
  cost/volumes/old_snapshots/README.md
  cost/volumes/unattached_volumes/README.md
  operational/cloud_credentials/aws/README.md
  operational/dbaas/aws/rds_backup/README.md
  operational/snapshots/README.md
  security/security_groups/high_open_ports/README.md
  security/security_groups/icmp_enabled/README.md
  security/security_groups/rules_without_descriptions/README.md
  security/storage/aws/public_buckets/README.md
  security/storage/google/public_buckets/README.md
Labels: READY-FOR-REVIEW

#149 Unattached IP Addresses
  cost/unattached_addresses/CHANGELOG.md
  cost/unattached_addresses/README.md
  cost/unattached_addresses/unattached_addresses.pt
Labels: New Policy, READY-FOR-REVIEW

#150 Update index
  README.md
Labels: READY-FOR-REVIEW

#153 Scheduled report
  README.md
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
Labels: New Policy

#154 Scheduled report
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW

#164 Azure - Superseded Instance Types
  cost/azure/superseded_instance_types/CHANGELOG.md
  cost/azure/superseded_instance_types/README.md
  cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
Labels: New Policy, READY-FOR-REVIEW

#165 Fix README URLs
  README.md
Labels: repo_maintenance

#152 Update js to skip servers without monitoring data
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/README.md
  cost/downsize_instance/downsize-instance.pt
Labels: bug

#167 Azure Reserved Instances Policy
  cost/azure/reserved_instances/utilization/CHANGELOG.md
  cost/azure/reserved_instances/utilization/README.md
  cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
Labels: New Policy, READY-FOR-REVIEW

#168 Budget Alerts Policy - Initial Release
  README.md
  cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/README.md
  cost/budget_alerts/budget_alert.pt
Labels: New Policy, READY-FOR-REVIEW

#169 Tagchecker
  compliance/tags/tag_checker/CHANGELOG.md
  compliance/tags/tag_checker/tag_checker.pt
Labels: READY-FOR-REVIEW

#166 Azure Hybrid Use Benefit Policy
  README.md
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/README.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
Labels: New Policy, READY-FOR-REVIEW
