Repository flexera-public/policy_templates, pull requests merged in 2019-08, with the labels that each got.

#277 Terminate actions dont need parents
  cost/terminate_policy/CHANGELOG.md
  cost/terminate_policy/instance_terminate.pt
Labels: READY-FOR-REVIEW, bug

#270 POL-46 Updates
  operational/azure/vms_without_managed_disks/CHANGELOG.md
  operational/azure/vms_without_managed_disks/README.md
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
Labels: READY-FOR-REVIEW, enhancement

#265 POL-37 Check for Unencrypted S3 buckets
  README.md
  security/aws/unencrypted_s3_buckets/AWS_Unencrypted_S3_Buckets.pt
  security/aws/unencrypted_s3_buckets/CHANGELOG.md
  security/aws/unencrypted_s3_buckets/README.md
Labels: New Policy, READY-FOR-REVIEW

#272 Low Service Usage - Adding in Summary.
  cost/low_service_usage/CHANGELOG.md
  cost/low_service_usage/low_service_usage.pt
Labels: READY-FOR-REVIEW, enhancement

#280 AWS Instance Scheduled Events - Add .pt
  operational/aws/instance_scheduled_events/aws_instance_scheduled_events.pt
Labels: READY-FOR-REVIEW

#281 Fixing Cheaper Regions Billing Center
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
Labels: READY-FOR-REVIEW, enhancement

#282 Superseded Instance Run Rate Change
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/README.md
  cost/superseded_instance/superseded_instance.pt
Labels: READY-FOR-REVIEW, enhancement

#279 AWS Utilization Fixes
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/README.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
Labels: READY-FOR-REVIEW, enhancement

#283 update readme with timezone list
  cost/schedule_instances/README.md
Labels: DO-NOT-MERGE

#284 fix links
  cost/schedule_instances/README.md
Labels: changelog

#285 Cheaper Regions Add in Resource ID
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
Labels: READY-FOR-REVIEW, enhancement

#287 Old Snaphots - Email Always
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
Labels: READY-FOR-REVIEW, enhancement

#286 updating docs for clarity
  cost/terminate_policy/README.md
Labels: changelog, enhancement

#291 pol-45_Check_for_publicly_accessible_Azure_SQL_Managed_Instance
  README.md
  security/azure/sql_publicly_accessible_managed_instance/CHANGELOG.md
  security/azure/sql_publicly_accessible_managed_instance/Check_for_publicly_accessible_Azure_SQL_Managed_Instance.pt
  security/azure/sql_publicly_accessible_managed_instance/README.md
Labels: New Policy, READY-FOR-REVIEW

#292 Cheaper Regions Remove tag_instance_name dimension
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
Labels: READY-FOR-REVIEW, enhancement

#294 AWS Cloudwatch Utilization - Fix documentation
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/README.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
Labels: READY-FOR-REVIEW, enhancement

#293 Snapshot email
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
Labels: New Policy, READY-FOR-REVIEW, enhancement

#262 POL-62-63 Adding burst info to utilization report
  README.md
  cost/aws/burstable_instance_cloudwatch_credit_utilization/CHANGELOG.md
  cost/aws/burstable_instance_cloudwatch_credit_utilization/README.md
  cost/aws/burstable_instance_cloudwatch_credit_utilization/aws_burstable_instance_cloudwatch_credit_utilization.pt
  data/aws/instance_types.json
Labels: New Policy, READY-FOR-REVIEW

#296 Google Utilization fixing nil error
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
Labels: READY-FOR-REVIEW, enhancement

#269 Okta Inactive Users - Initial Release
  README.md
  fsm/okta/inactive_users/CHANGELOG.md
  fsm/okta/inactive_users/README.md
  fsm/okta/inactive_users/okta-inactive-users.pt
Labels: New Policy, READY-FOR-REVIEW

#295 Old Snapshot Policy - Add modifications to check for images.
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
Labels: READY-FOR-REVIEW, enhancement

#273 adding in summary on low_account_usage
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/README.md
  cost/low_account_usage/low_account_usage.pt
Labels: READY-FOR-REVIEW, enhancement

#301 Superseded Instances: Added region to output
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/superseded_instance.pt
Labels: READY-FOR-REVIEW, enhancement

#306 updating community link and rightscale policy template reference
  README.md
Labels: READY-FOR-REVIEW

#300 fix readme link for vmware tag sync
  operational/vmware/instance_tag_sync/instance_tag_sync.pt
Labels: enhancement
