Repository flexera-public/policy_templates, pull requests merged in 2019-06, with the labels that each got.

#246 Adding JSON to Readme
  README.md
Labels: READY-FOR-REVIEW, changelog

#238 Terminate Policy with End Date
  README.md
  cost/terminate_policy/CHANGELOG.md
  cost/terminate_policy/README.md
  cost/terminate_policy/instance_terminate.pt
Labels: New Policy, READY-FOR-REVIEW

#248 observer
  cost/terminate_policy/README.md
Labels: changelog

#249 fixing short description link
  cost/terminate_policy/CHANGELOG.md
  cost/terminate_policy/instance_terminate.pt
Labels: changelog

#250 Fix for Azure API Client Secret Encoding
  compliance/azure/azure_disallowed_regions/CHANGELOG.md
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
  compliance/tags/azure_rg_tags/CHANGELOG.md
  compliance/tags/azure_rg_tags/azure_resource_group_tags.pt
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  cost/azure/superseded_instance_types/CHANGELOG.md
  cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
Labels: READY-FOR-REVIEW, bug, enhancement

#254 Initial Release - AWS RI Purchase Recommendations
  README.md
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/README.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
Labels: New Policy, READY-FOR-REVIEW

#253 Initial Release - Azure RI Purchase Recommendations
  README.md
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/README.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
Labels: New Policy, READY-FOR-REVIEW

#255 POL-11 Instances with Unapproved instance types
  README.md
  compliance/unapproved_instance_types/CHANGELOG.md
  compliance/unapproved_instance_types/README.md
  compliance/unapproved_instance_types/unapproved_instance_types.pt
Labels: New Policy, READY-FOR-REVIEW

#257 Azure Instances Log Analytics Utilization
  README.md
  cost/azure/instances_log_analitics_utilization/CHANGELOG.md
  cost/azure/instances_log_analitics_utilization/README.md
  cost/azure/instances_log_analitics_utilization/azure_instance_log_analytics_utilization.pt
Labels: New Policy, READY-FOR-REVIEW

#252 Low Account Usage with Billing Center
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/README.md
  cost/low_account_usage/low_account_usage.pt
Labels: READY-FOR-REVIEW, enhancement

#256 Low Service Usage with Billing Center
  cost/low_service_usage/CHANGELOG.md
  cost/low_service_usage/README.md
  cost/low_service_usage/low_service_usage.pt
Labels: READY-FOR-REVIEW, enhancement

#258 AWS Native Utilization with params and Tag Support
  .gitignore
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/README.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
  cost/azure/instances_log_analitics_utilization/README.md
Labels: READY-FOR-REVIEW, enhancement

#233 Superseded Instances Policy
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/README.md
  cost/superseded_instance/superseded_instance.pt
  data/aws/instance_types.json
  data/azure/instance_types.json
Labels: New Policy, READY-FOR-REVIEW

#242 Part One Splitting Downsize policy into RL utilization and Multi cloud downsize
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/README.md
  cost/downsize_instance/downsize-instance-add-tags.pt
  cost/downsize_instance/downsize-instance.pt
  cost/downsize_instance/downsize_instance.pt
Labels: READY-FOR-REVIEW
