Repository flexera-public/policy_templates, pull requests merged in 2019-10, with the labels that each got.

#351 POL-64 Modified existing policies to use inferred region in AWS auth method
  compliance/aws/ecs_unused/AWS_Unused_ECS_Clusters.pt
  compliance/aws/ecs_unused/CHANGELOG.md
  cost/aws/elb/clb_unused/AWS_Delete_Unused_CLB.pt
  cost/aws/elb/clb_unused/CHANGELOG.md
  operational/aws/subnet_name_sync/CHANGELOG.md
  operational/aws/subnet_name_sync/aws_subnet_name_sync.pt
  operational/aws/vpc_name_sync/CHANGELOG.md
  operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
  operational/dbaas/aws/rds_backup/CHANGELOG.md
  operational/dbaas/aws/rds_backup/aws_rds_backup.pt
  security/aws/ebs_unencrypted_volumes/AWS_Unencrypted_Volumes.pt
  security/aws/ebs_unencrypted_volumes/CHANGELOG.md
  security/aws/loadbalancer_internet_facing/AWS_Internet-facing_ELBs.pt
  security/aws/loadbalancer_internet_facing/CHANGELOG.md
  security/storage/aws/public_buckets/CHANGELOG.md
  security/storage/aws/public_buckets/aws_public_buckets.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#356 update policy name and readme
  README.md
  cost/google/cloudsql_rightsizing/CHANGELOG.md
  cost/google/cloudsql_rightsizing/README.md
  cost/google/cloudsql_rightsizing/google_cloudsql_rightsizing.pt
Labels: READY-FOR-REVIEW

#355 POL-69 - Fnms license compliance check
  README.md
  compliance/fnms/FNMS_Licenses_At_Risk/CHANGELOG.md
  compliance/fnms/FNMS_Licenses_At_Risk/README.md
  compliance/fnms/FNMS_Licenses_At_Risk/fnms-at-risk-licenses.pt
  compliance/fnms/FNMS_Licenses_At_Risk/images/APIToken.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/CreateServeceAccount.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/FNMSCloudInstanceReport.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/MailOutput_FNMSLicense.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/ReportNumber.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/WebServiceRole.png
  compliance/fnms/fnms_licenses_at_risk/CHANGELOG.md
  compliance/fnms/fnms_licenses_at_risk/README.md
  compliance/fnms/fnms_licenses_at_risk/fnms-at-risk-licenses.pt
  compliance/fnms/fnms_licenses_at_risk/images/APIToken.png
  compliance/fnms/fnms_licenses_at_risk/images/CreateServeceAccount.png
  compliance/fnms/fnms_licenses_at_risk/images/FNMSCloudInstanceReport.png
  compliance/fnms/fnms_licenses_at_risk/images/MailOutput_FNMSLicense.png
  compliance/fnms/fnms_licenses_at_risk/images/ReportNumber.png
  compliance/fnms/fnms_licenses_at_risk/images/WebServiceRole.png
Labels: New Policy, READY-FOR-REVIEW

#358 POL-69 Remove Mixed Case directory
  compliance/fnms/FNMS_Licenses_At_Risk/CHANGELOG.md
  compliance/fnms/FNMS_Licenses_At_Risk/README.md
  compliance/fnms/FNMS_Licenses_At_Risk/fnms-at-risk-licenses.pt
  compliance/fnms/FNMS_Licenses_At_Risk/images/APIToken.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/CreateServeceAccount.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/FNMSCloudInstanceReport.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/MailOutput_FNMSLicense.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/ReportNumber.png
  compliance/fnms/FNMS_Licenses_At_Risk/images/WebServiceRole.png
Labels: READY-FOR-REVIEW

#359 POL-69 Adjustment to version and default values
  compliance/fnms/fnms_licenses_at_risk/CHANGELOG.md
  compliance/fnms/fnms_licenses_at_risk/fnms-at-risk-licenses.pt
Labels: READY-FOR-REVIEW

#361 PHX-1800_Policy_Sync_not_processing_updates Updated Rakefile to deal …
  Rakefile
Labels: READY-FOR-REVIEW, bug

#362 skip adding policies
  Rakefile
Labels: READY-FOR-REVIEW

#363 POL-123 fix broken links
  cost/downsize_instance/README.md
Labels: READY-FOR-REVIEW

#357 POL-66 Ensured all required perms are documented for each policy
  compliance/azure/ahub_manual/Azure_AHUB_Utilization_with_Manual_Entry.pt
  compliance/azure/ahub_manual/CHANGELOG.md
  compliance/azure/ahub_manual/README.md
  compliance/azure/azure_disallowed_regions/CHANGELOG.md
  compliance/azure/azure_disallowed_regions/README.md
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
  compliance/azure/azure_long_stopped_instances/CHANGELOG.md
  compliance/azure/azure_long_stopped_instances/README.md
  compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
  compliance/azure/subscription_access/CHANGELOG.md
  compliance/azure/subscription_access/azure_subscription_access.pt
  compliance/tags/azure_rg_tags/CHANGELOG.md
  compliance/tags/azure_rg_tags/README.md
  compliance/tags/azure_rg_tags/azure_resource_group_tags.pt
  compliance/unapproved_instance_types/CHANGELOG.md
  compliance/unapproved_instance_types/unapproved_instance_types.pt
  cost/aws/reserved_instances/coverage/README.md
  cost/aws/reserved_instances/expiration/README.md
  cost/aws/reserved_instances/recommendations/README.md
  cost/aws/reserved_instances/report_by_bc/README.md
  cost/aws/reserved_instances/utilization/README.md
  cost/aws/s3_bucket_size/CHANGELOG.md
  cost/aws/s3_bucket_size/README.md
  cost/aws/s3_bucket_size/aws_bucket_size.pt
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/README.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  cost/azure/instances_log_analitics_utilization/README.md
  cost/azure/reserved_instances/recommendations/README.md
  cost/azure/reserved_instances/utilization/README.md
  cost/azure/superseded_instance_types/CHANGELOG.md
  cost/azure/superseded_instance_types/README.md
  cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
  cost/google/cud_report/CHANGELOG.md
  cost/google/cud_report/Google_Committed_UseDiscount_Report.pt
  cost/google/cud_report/README.md
  fsm/okta/inactive_users/CHANGELOG.md
  fsm/okta/inactive_users/okta-inactive-users.pt
  operational/azure/vms_without_managed_disks/CHANGELOG.md
  operational/azure/vms_without_managed_disks/README.md
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
  operational/dbaas/aws/rds_backup/README.md
  operational/fnms/schedule_fnms_reports/CHANGELOG.md
  operational/fnms/schedule_fnms_reports/README.md
  operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
  operational/stranded_servers/CHANGELOG.md
  operational/stranded_servers/Stranded_Servers.pt
  security/azure/sql_publicly_accessible_managed_instance/CHANGELOG.md
  security/azure/sql_publicly_accessible_managed_instance/Check_for_publicly_accessible_Azure_SQL_Managed_Instance.pt
  security/azure/sql_publicly_accessible_managed_instance/README.md
  security/storage/aws/public_buckets/README.md
  security/storage/google/public_buckets/README.md
Labels: READY-FOR-REVIEW, changelog, enhancement

#365 POL-118 Update region datasources to use github data list
  cost/aws/s3_bucket_size/CHANGELOG.md
  cost/aws/s3_bucket_size/aws_bucket_size.pt
  security/aws/rds_publicly_accessible/AWS_Publicly_Accessible_RDS_Instances.pt
  security/aws/rds_publicly_accessible/CHANGELOG.md
  security/aws/rds_unencrypted/AWS_Unencrypted_RDS_Instances.pt
  security/aws/rds_unencrypted/CHANGELOG.md
  security/storage/aws/s3_buckets_without_server_access_logging/CHANGELOG.md
  security/storage/aws/s3_buckets_without_server_access_logging/aws_s3_buckets_without_server_access_logging.pt
Labels: READY-FOR-REVIEW, enhancement

#364 Azure Subscription Access - Fix for Users
  compliance/azure/subscription_access/CHANGELOG.md
  compliance/azure/subscription_access/README.md
  compliance/azure/subscription_access/azure_subscription_access.pt
Labels: READY-FOR-REVIEW

#367 Azure Long Stopped Instances - Fix RG tag and missing time stamp
  compliance/azure/azure_long_stopped_instances/CHANGELOG.md
  compliance/azure/azure_long_stopped_instances/README.md
  compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
Labels: READY-FOR-REVIEW, bug

#366 AzureRM Subscription Access - Root Level Assignments
  compliance/azure/subscription_access/CHANGELOG.md
  compliance/azure/subscription_access/README.md
  compliance/azure/subscription_access/azure_subscription_access.pt
Labels: READY-FOR-REVIEW, enhancement

#368 Azure Expiring RIs - Update Optima Endpoint
  cost/azure/reserved_instances/expiration/CHANGELOG.md
  cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
Labels: READY-FOR-REVIEW

#327 POL-25 Running Instance Count Anomaly
  README.md
  cost/instance_anomaly/CHANGELOG.md
  cost/instance_anomaly/README.md
  cost/instance_anomaly/instance_anomaly.pt
Labels: READY-FOR-REVIEW

#305 Pol-6 AWS Elastic Load Balancer Encryption Check Policy Template
  README.md
  security/aws/clb_unencrypted/CHANGELOG.md
  security/aws/clb_unencrypted/README.md
  security/aws/clb_unencrypted/aws_clb_encryption.pt
  security/aws/elb_unencrypted/CHANGELOG.md
  security/aws/elb_unencrypted/README.md
  security/aws/elb_unencrypted/aws_elb_encryption.pt
Labels: New Policy, READY-FOR-REVIEW

#372 Pol-103 - Monthly Actual v. Budgeted Spend Report
  README.md
  cost/budget_v_actual/CHANGELOG.md
  cost/budget_v_actual/README.md
  cost/budget_v_actual/monthly_budget_v_actual.pt
Labels: New Policy, READY-FOR-REVIEW

#369 POL-135-Updated Permission block
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/README.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
Labels: READY-FOR-REVIEW, bug, changelog

#373 POL-29 Check for usage in disallowed regions
  README.md
  compliance/aws/disallowed_regions/CHANGELOG.md
  compliance/aws/disallowed_regions/README.md
  compliance/aws/disallowed_regions/aws_disallowed_regions.pt
Labels: New Policy, READY-FOR-REVIEW

#371 POL-125 Scheduled Report With Estimates
  README.md
  cost/scheduled_reports_with_estimates/CHANGELOG.md
  cost/scheduled_reports_with_estimates/README.md
  cost/scheduled_reports_with_estimates/costs_forecasting.pt
Labels: New Policy, READY-FOR-REVIEW

#374 POL-113 Azure Unused SQL Databases
  README.md
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/README.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
Labels: New Policy, READY-FOR-REVIEW

#379 Remove budget input details from template short_description
  cost/budget_v_actual/CHANGELOG.md
  cost/budget_v_actual/monthly_budget_v_actual.pt
Labels: READY-FOR-REVIEW

#376 POL-138 New Services in Bill
  README.md
  README_GUIDELINE.md
  cost/new_service_usage/CHANGELOG.md
  cost/new_service_usage/README.md
  cost/new_service_usage/new_service_usage.pt
Labels: New Policy, READY-FOR-REVIEW

#377 Rename policies
  README.md
  cost/azure/superseded_instance_types/CHANGELOG.md
  cost/azure/superseded_instance_types/README.md
  cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
  security/azure/sql_publicly_accessible_managed_instance/CHANGELOG.md
  security/azure/sql_publicly_accessible_managed_instance/Check_for_publicly_accessible_Azure_SQL_Managed_Instance.pt
Labels: READY-FOR-REVIEW

#375 POL-128 - Schedule Report with Markup
  README.md
  cost/scheduled_report_markUpsDowns/CHANGELOG.md
  cost/scheduled_report_markUpsDowns/README.md
  cost/scheduled_report_markUpsDowns/scheduled_report_markUpsDowns.pt
Labels: New Policy, READY-FOR-REVIEW

#378 POL-130 - Master Org Scheduled Report with Currency Conversion
  msp/cost/master_org_cost_policy_currency/CHANGELOG.md
  msp/cost/master_org_cost_policy_currency/README.md
  msp/cost/master_org_cost_policy_currency/master_org_cost_policy_currency.pt
Labels: New Policy, READY-FOR-REVIEW

#380 Pol 131 compliance scores
  README.md
  compliance/azure/compliance_score/CHANGELOG.md
  compliance/azure/compliance_score/README.md
  compliance/azure/compliance_score/azure_regulatory_compliance_report.pt
Labels: READY-FOR-REVIEW

#381 Pol 134 migration recos
  README.md
  operational/compute_instance_migration/README.md
  operational/compute_instance_migration/changelog.md
  operational/compute_instance_migration/risc-compute-instance-migration-recos.pt
Labels: READY-FOR-REVIEW

#382 include missing inputs
  compliance/azure/azure_long_stopped_instances/README.md
  cost/volumes/old_snapshots/README.md
  operational/vmware/instance_tag_sync/README.md
Labels: READY-FOR-REVIEW

#385 POL-126 Instance Utilization
  README.md
  cost/rightlink_rightsize/CHANGELOG.md
  cost/rightlink_rightsize/README.md
  cost/rightlink_rightsize/rightlink-rightsize-add-tags.pt
  cost/rightlink_rightsize/rightlink_rightsize.pt
  data/vmware/instance_types.json
Labels: DO-NOT-MERGE

#384 POL-78 More flexibility on date ranges in scheduled report policy
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#387 NetFlow Top Talkers
  README.md
  operational/azure/network_flow/README.md
  operational/azure/network_flow/changelog.md
  operational/azure/network_flow/risc-netflow.pt
Labels: READY-FOR-REVIEW
