Repository flexera-public/policy_templates, pull requests merged in 2019-03, with the labels that each got.

#193 Updating the v1.1 = updated short description
  cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
  cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
Labels: READY-FOR-REVIEW, repo_maintenance

#195 Adding aws instance types: memory optimize r5, r5a, r5d, x1e,z1d / added compute optimized c5n, c5d / general purpose added m5a, m5d, a1 / added one f1, one g2, g3 family
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/downsize-instance.pt
  cost/downsize_instance/instance_types.json
Labels: READY-FOR-REVIEW, enhancement

#190 POL-38 - Google cloud cud report
  .gitattributes
  README.md
  cost/google/cud_report/CHANGELOG.md
  cost/google/cud_report/Google_Committed_UseDiscount_Report.pt
  cost/google/cud_report/README.md
  cost/schedule_instances/CHANGELOG.md
  cost/unattached_addresses/CHANGELOG.md
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/README.md
  cost/volumes/old_snapshots/old_snapshot.pt
  cost/volumes/unattached_volumes/CHANGELOG.md
Labels: Google Committed Use Discount (CUD) Report, New Policy, READY-FOR-REVIEW

#196 Add GitHub.com Available Seats Policy
  README.md
  compliance/github/available_seats/CHANGELOG.md
  compliance/github/available_seats/README.md
  compliance/github/available_seats/available_seats.pt
Labels: New Policy, READY-FOR-REVIEW

#197 Changes GitHub.com Available Seats policy to Compliance
  compliance/github/available_seats/CHANGELOG.md
  compliance/github/available_seats/available_seats.pt
Labels: READY-FOR-REVIEW

#198 Github Licensed Seats: Updating short description
  compliance/github/available_seats/CHANGELOG.md
  compliance/github/available_seats/available_seats.pt
Labels: READY-FOR-REVIEW

#200 Use Travis to build docs
  .travis.yml
  tools/travis/build_docs.sh
Labels: repo_maintenance

#201 Update build docs script path
  .travis.yml
Labels: repo_maintenance

#194 Azure: Tag Resources with Resource Group Name
  README.md
  compliance/tags/azure_rg_tags/CHANGELOG.md
  compliance/tags/azure_rg_tags/README.md
  compliance/tags/azure_rg_tags/azure_resource_group_tags.pt
Labels: New Policy, READY-FOR-REVIEW

#202 Removing Tag Checker Icon from Marketplace
  compliance/tags/tag_checker/CHANGELOG.md
  compliance/tags/tag_checker/tag_checker.pt
  operational/dbaas/aws/rds_backup/CHANGELOG.md
  operational/dbaas/aws/rds_backup/aws_rds_backup.pt
Labels: READY-FOR-REVIEW

#203 Repo Maintenance: Add Travis commit message to docs build
  tools/travis/build_docs.sh
Labels: READY-FOR-REVIEW, repo_maintenance

#204 AWS VPC and Subnet Name Sync
  README.md
  operational/aws/subnet_name_sync/README.md
  operational/aws/subnet_name_sync/changelog.md
  operational/aws/subnet_name_sync/subnets_sync.pt
  operational/aws/vpc_name_sync/README.md
  operational/aws/vpc_name_sync/changelog.md
  operational/aws/vpc_name_sync/vpc_sync.pt
Labels: New Policy, READY-FOR-REVIEW
