Repository flexera-public/policy_templates, pull requests merged in 2019-05, with the labels that each got.

#218 POL-4 AWS_Unused_ECS_Clusters
  README.md
  compliance/aws/ecs_unused/AWS_Unused_ECS_Clusters.pt
  compliance/aws/ecs_unused/CHANGELOG.md
  compliance/aws/ecs_unused/README.md
Labels: New Policy

#222 adding in codeowners
  CODEOWNERS
Labels: repo_maintenance

#225 vscode
  .gitignore
Labels: repo_maintenance

#229 bump version to update link
  cost/azure/superseded_instance_types/CHANGELOG.md
  cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
Labels: READY-FOR-REVIEW, enhancement

#228 Reduce frequency of incident creation/email
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW, enhancement

#220 POL-33_Check_for_internet_Elastic_load_Balancers
  README.md
  security/aws/loadbalancer_internet_facing/AWS_Internet-facing_ELBs.pt
  security/aws/loadbalancer_internet_facing/CHANGELOG.md
  security/aws/loadbalancer_internet_facing/README.md
Labels: New Policy, READY-FOR-REVIEW

#216 Pol 31 AWS Unencrypted Volumes Report
  README.md
  security/aws/ebs_unencrypted_volumes/AWS_Unencrypted_Volumes.pt
  security/aws/ebs_unencrypted_volumes/CHANGELOG.md
  security/aws/ebs_unencrypted_volumes/README.md
Labels: New Policy, READY-FOR-REVIEW

#231 RI Utilization Policy - add fields to incident report
  cost/aws/reserved_instances/utilization/CHANGELOG.md
  cost/aws/reserved_instances/utilization/utilization_ris.pt
Labels: READY-FOR-REVIEW, enhancement

#232 Updating Old Snapshots and adding delete
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
Labels: READY-FOR-REVIEW, enhancement

#230 Low Service Usage Policy
  README.md
  cost/low_service_usage/CHANGELOG.md
  cost/low_service_usage/README.md
  cost/low_service_usage/low_service_usage.pt
Labels: New Policy, READY-FOR-REVIEW

#227 Low Account Usage Policy
  README.md
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/README.md
  cost/low_account_usage/low_account_usage.pt
Labels: New Policy, READY-FOR-REVIEW

#226 Google unutilized ip policy
  README.md
  cost/google/unutilized_ip_addresses/CHANGELOG.md
  cost/google/unutilized_ip_addresses/README.md
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Labels: New Policy, READY-FOR-REVIEW

#223 Google Stackdriver Utilization Policy
  README.md
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/README.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
Labels: New Policy, READY-FOR-REVIEW

#219 GitHub Policy Templates
  README.md
  compliance/github/available_seats/CHANGELOG.md
  compliance/github/available_seats/README.md
  compliance/github/available_seats/available_seats.pt
  compliance/github/outside_collaborators/CHANGELOG.md
  compliance/github/outside_collaborators/README.md
  compliance/github/outside_collaborators/outside_collaborators.pt
  compliance/github/repository_admin_team/CHANGELOG.md
  compliance/github/repository_admin_team/README.md
  compliance/github/repository_admin_team/repository_admin_team.pt
  compliance/github/repository_branch_protection/CHANGELOG.md
  compliance/github/repository_branch_protection/README.md
  compliance/github/repository_branch_protection/repository_branch_protection.pt
  compliance/github/repository_naming/CHANGELOG.md
  compliance/github/repository_naming/README.md
  compliance/github/repository_naming/repository_naming.pt
  compliance/github/repository_size/CHANGELOG.md
  compliance/github/repository_size/README.md
  compliance/github/repository_size/repository_size.pt
  compliance/github/toplevel_teams/CHANGELOG.md
  compliance/github/toplevel_teams/README.md
  compliance/github/toplevel_teams/toplevel_teams.pt
Labels: New Policy, READY-FOR-REVIEW, enhancement

#215 AWS Native Utilization Policy
  README.md
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/README.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
Labels: New Policy, READY-FOR-REVIEW

#237 Adding in Amazon Regions Datasource
  data/aws/regions.json
Labels: READY-FOR-REVIEW, enhancement

#234 POL-36 AWS Unencrypted RDS instances
  security/aws/rds_unencrypted/AWS_Unencrypted_RDS_Instances.pt
  security/aws/rds_unencrypted/CHANGELOG.md
  security/aws/rds_unencrypted/README.md
Labels: New Policy, READY-FOR-REVIEW

#235 POL-35 AWS Publicly Accessible RDS Instances
  README.md
  security/aws/rds_publicly_accessible/AWS_Publicly_Accessible_RDS_Instances.pt
  security/aws/rds_publicly_accessible/CHANGELOG.md
  security/aws/rds_publicly_accessible/README.md
Labels: New Policy, READY-FOR-REVIEW

#241 Move Instance Types to Data to enrich data
  data/aws/instance_types.json
  data/azure/instance_types.json
  data/google/instance_types.json
Labels: READY-FOR-REVIEW, enhancement

#206 VMWare Instance Tag Sync
  README.md
  operational/vmware/instance_tag_sync/README.md
  operational/vmware/instance_tag_sync/changelog.md
  operational/vmware/instance_tag_sync/instance_tag_sync.pt
Labels: New Policy, READY-FOR-REVIEW, WAITING TPV

#244 Fix link
  README.md
Labels: changelog

#240 POL-53 Stranded servers, initial release
  README.md
  operational/stranded_servers/CHANGELOG.md
  operational/stranded_servers/README.md
  operational/stranded_servers/Stranded_Servers.pt
Labels: New Policy, READY-FOR-REVIEW

#239 Adding Snapshot to Volume Delete
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/README.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: READY-FOR-REVIEW, enhancement

#245 Cheaper regions with Instance only data, and column cleanup
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
Labels: READY-FOR-REVIEW, enhancement
