Repository flexera-public/policy_templates, pull requests merged in 2020-05, with the labels that each got.

#520 Pol 268
  README.md
  saas/fsm/redundant_apps/CHANGELOG.md
  saas/fsm/redundant_apps/README.md
  saas/fsm/redundant_apps/fsm-redundant_apps.pt
Labels: New Policy, READY-FOR-REVIEW

#522 POL 91: Inactive SaaS Users - Initial Release
  README.md
  saas/fsm/inactive_users_by_dept/CHANGELOG.md
  saas/fsm/inactive_users_by_dept/README.md
  saas/fsm/inactive_users_by_dept/inactive_users_by_dept.pt
Labels: READY-FOR-REVIEW

#478 POL-206 New Resource Table 1
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/azure/instances_log_analitics_utilization/CHANGELOG.md
  cost/azure/instances_log_analitics_utilization/azure_instance_log_analytics_utilization.pt
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
  cost/downsize_instance/CHANGELOG.md
  cost/downsize_instance/downsize_instance.pt
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
  cost/google/unattached_volumes/CHANGELOG.md
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
  cost/google/unutilized_ip_addresses/CHANGELOG.md
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
  cost/unattached_addresses/CHANGELOG.md
  cost/unattached_addresses/unattached_addresses.pt
  cost/volumes/old_snapshots/CHANGELOG.md
  cost/volumes/old_snapshots/old_snapshot.pt
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/uav_policy.pt
  security/storage/aws/public_buckets/CHANGELOG.md
  security/storage/aws/public_buckets/aws_public_buckets.pt
Labels: DO-NOT-MERGE, READY FOR APPROVAL

#484 POL-221 New Resource Table 2
  compliance/tags/tag_checker/CHANGELOG.md
  compliance/tags/tag_checker/tag_checker.pt
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
  cost/schedule_instances/CHANGELOG.md
  cost/schedule_instances/schedule_instances.pt
Labels: DO-NOT-MERGE, READY FOR APPROVAL, enhancement

#499 POL-264 Low License Availability
  README.md
  compliance/fnms/fnms_low_licenses_available/CHANGELOG.md
  compliance/fnms/fnms_low_licenses_available/README.md
  compliance/fnms/fnms_low_licenses_available/fnms-low-available-licenses.pt
  compliance/fnms/fnms_low_licenses_available/images/APIToken.png
  compliance/fnms/fnms_low_licenses_available/images/CreateServeceAccount.png
  compliance/fnms/fnms_low_licenses_available/images/FNMS_cv_Report.png
  compliance/fnms/fnms_low_licenses_available/images/ReportNumber.png
  compliance/fnms/fnms_low_licenses_available/images/WebServiceRole.png
Labels: New Policy, READY FOR APPROVAL, READY-FOR-REVIEW

#521 POL-276 - Update the FSM Policy to Report on Redundant Ap…
  saas/fsm/redundant_apps/CHANGELOG.md
  saas/fsm/redundant_apps/fsm-redundant_apps.pt
  saas/fsm/user_status_change/README.md
Labels: READY FOR APPROVAL, READY-FOR-REVIEW

#527 POL-273 - Unsanctioned Apps with Managed Contract
  README.md
  saas/fsm/unsanctioned_apps_with_contract/CHANGELOG.md
  saas/fsm/unsanctioned_apps_with_contract/README.md
  saas/fsm/unsanctioned_apps_with_contract/fsm-unsanctioned_with_contract.pt
Labels: READY-FOR-REVIEW

#530 Add Param to Inactive Users By Dept policy
  saas/fsm/inactive_users_by_dept/CHANGELOG.md
  saas/fsm/inactive_users_by_dept/README.md
  saas/fsm/inactive_users_by_dept/inactive_users_by_dept.pt
Labels: READY-FOR-REVIEW

#531 POL-95 update FSM Unsanctioned Spend policy
  saas/fsm/unsanctioned_spend/CHANGELOG.md
  saas/fsm/unsanctioned_spend/README.md
  saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
Labels: READY-FOR-REVIEW

#533 Fix UI Rendering of Policy Cards
  cost/instance_anomaly/CHANGELOG.md
  cost/instance_anomaly/instance_anomaly.pt
Labels: READY-FOR-REVIEW

#535 update permissions
  cost/aws/old_snapshots/README.md
Labels: READY-FOR-REVIEW

#526 POL 93 - Duplicate User Accounts
  README.md
  saas/fsm/duplicate_users/CHANGELOG.md
  saas/fsm/duplicate_users/README.md
  saas/fsm/duplicate_users/duplicate_users.pt
Labels: READY-FOR-REVIEW

#536 Scheduled Reports: add Billing Center graph dimension
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW

#409 POL-97 ServiceNow Inactive Approvers
  README.md
  saas/servicenow/inactive_approvers/CHANGELOG.md
  saas/servicenow/inactive_approvers/README.md
  saas/servicenow/inactive_approvers/servicenow_inactive_approvers.pt
Labels: New Policy, READY-FOR-REVIEW

#539 add m5ad instance types
  data/aws/instance_types.json
Labels: READY-FOR-REVIEW
