Repository flexera-public/policy_templates, pull requests merged in 2020-11, with the labels that each got.

#623 POL-394-VMWare-Tags-Sync-Policy
  operational/vmware/instance_tag_sync/README.md
  operational/vmware/instance_tag_sync/changelog.md
  operational/vmware/instance_tag_sync/instance_tag_sync.pt
Labels: changelog

#624 POL-397 - Azure Expiring Reserved Instances - Fix for 100% False-positive
  cost/azure/reserved_instances/utilization/CHANGELOG.md
  cost/azure/reserved_instances/utilization/README.md
  cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
Labels: READY-FOR-REVIEW, bug

#627 Copy-POL-394-VMWare-Tags-Sync-Policy
  operational/vmware/instance_tag_sync/README.md
Labels: READY-FOR-REVIEW

#616 Add AWS Account IDs to AWS Cost Policies
  cost/aws/burstable_instance_cloudwatch_credit_utilization/CHANGELOG.md
  cost/aws/burstable_instance_cloudwatch_credit_utilization/aws_burstable_instance_cloudwatch_credit_utilization.pt
  cost/aws/elb/clb_unused/CHANGELOG.md
  cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
  cost/aws/object_storage_optimization/CHANGELOG.md
  cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
  cost/aws/rds_instance_license_info/CHANGELOG.md
  cost/aws/rds_instance_license_info/rds_instance_license_info.pt
  cost/aws/s3_bucket_size/CHANGELOG.md
  cost/aws/s3_bucket_size/aws_bucket_size.pt
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/unused_rds.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Labels: READY-FOR-REVIEW, enhancement

#625 Use Policy Templates on a few parameters
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Labels: READY-FOR-REVIEW

#628 POL-398-Display-cost-for-each-resources-under-all-the-azure-subscription-ids-available-from-Optima-in-Azure-policies-for-Savings
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
Labels: READY-FOR-REVIEW, changelog

#632 POL 399 unable to configure low service usage policy
  cost/low_service_usage/CHANGELOG.md
  cost/low_service_usage/low_service_usage.pt
Labels: READY-FOR-REVIEW, bug, changelog

#633 POL-394-VMWare-Tags-Sync-Policy-new
  operational/vmware/instance_tag_sync/README.md
  operational/vmware/instance_tag_sync/changelog.md
  operational/vmware/instance_tag_sync/instance_tag_sync.pt
Labels: READY-FOR-REVIEW, changelog

#635 Azure Subscription Access: Fix Role Assignment ID bug
  compliance/azure/subscription_access/CHANGELOG.md
  compliance/azure/subscription_access/azure_subscription_access.pt
Labels: READY-FOR-REVIEW, bug

#638 Updated JSON file with "m5.16xlarge" instead of m5.24xlarge
  data/aws/instance_types.json
Labels: READY-FOR-REVIEW

#639 removing tabs from markdown block
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW

#634 POL-317_Updated cost details
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/README.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
Labels: enhancement
