Repository flexera-public/policy_templates, pull requests merged in 2020-03, with the labels that each got.

#466 rename polices
  cost/aws/unattached_volumes/CHANGELOG.md
  cost/aws/unattached_volumes/README.md
  cost/aws/unattached_volumes/aws_delete_unattached_volumes.pt
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/README.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
  cost/google/unattached_volumes/CHANGELOG.md
  cost/google/unattached_volumes/README.md
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
Labels: READY-FOR-REVIEW

#473 POL-226 Adding in initial code workspace items.
  .gitignore
  package-lock.json
  policy_templates.code-workspace
Labels: READY-FOR-REVIEW, enhancement

#454 POL-201 AzureAD -> Flexera CMP Group Sync
  .mdlrc
  Dangerfile
  README.md
  operational/azure/azuread_group_sync/CHANGELOG.md
  operational/azure/azuread_group_sync/README.md
  operational/azure/azuread_group_sync/azuread_group_sync.pt
Labels: New Policy, READY-FOR-REVIEW

#477 Azure Log Analytics Bug Fix
  cost/azure/instances_log_analitics_utilization/CHANGELOG.md
  cost/azure/instances_log_analitics_utilization/azure_instance_log_analytics_utilization.pt
Labels: READY-FOR-REVIEW, bug

#468 POL-32 AWS Long Running Instances
  README.md
  operational/aws/long_running_instances/CHANGELOG.md
  operational/aws/long_running_instances/README.md
  operational/aws/long_running_instances/long_running_instances.pt
Labels: New Policy, READY-FOR-REVIEW

#475 SRE1-668_fix_excudled_orgs_js
  msp/cost/master_org_cost_policy/CHANGELOG.md
  msp/cost/master_org_cost_policy/master_org_cost_policy.pt
Labels: READY-FOR-REVIEW, bug

#476 POL-227-Subscription Name is missing from Policies
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Labels: READY-FOR-REVIEW, bug

#469 PHX-2039 Basic convert_table tool
  tools/bin/convert_table
Labels: READY-FOR-REVIEW

#451 POL-194 = SRE1-195_create_a_list_of_orgs_and_accounts_policy
  msp/compliance/orgs_and_cloud_accounts_report/CHANGELOG.md
  msp/compliance/orgs_and_cloud_accounts_report/README.md
  msp/compliance/orgs_and_cloud_accounts_report/orgs_and_cloud_accounts_report.pt
Labels: New Policy

#472 POL-204-Azure Delete Old Snapshots
  README.md
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/README.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
Labels: New Policy, READY-FOR-REVIEW

#471 POL-231 - Added all Cloud with lowest cost and highlight the overall low cost
  operational/compute_instance_migration/README.md
  operational/compute_instance_migration/changelog.md
  operational/compute_instance_migration/risc-compute-instance-migration-recos.pt
Labels: READY-FOR-REVIEW, enhancement

#465 POL-223 - RDS Instance Report
  README.md
  cost/aws/rds_instance_license_info/CHANGELOG.md
  cost/aws/rds_instance_license_info/README.md
  cost/aws/rds_instance_license_info/rds_instance_license_info.pt
  data/aws/instance_types.json
Labels: READY-FOR-REVIEW

#480 POL-177- Azure Disallowed Regions - terminate instance
  compliance/azure/azure_disallowed_regions/CHANGELOG.md
  compliance/azure/azure_disallowed_regions/README.md
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
Labels: bug

#474 POL 224 - budget alert errors
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/README.md
  cost/budget_alerts/budget_alert.pt
Labels: bug

#462 Pol 222 rate exceeded aws unattached volumes
  README.md
  cost/aws/unattached_volumes/CHANGELOG.md
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/README.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Labels: READY-FOR-REVIEW, bug

#467 Pol 203 aws delete old snapshots
  README.md
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/README.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
Labels: New Policy, READY-FOR-REVIEW, changelog

#485 fixs for Graphs/Azure AD API
  compliance/azure/subscription_access/CHANGELOG.md
  compliance/azure/subscription_access/README.md
  compliance/azure/subscription_access/azure_subscription_access.pt
Labels: bug

#488 PHX-2039 Cherry Pick Tool
  tools/bin/convert_table
Labels: enhancement

#463 POL-170 - Azure Delete Unattached Volumes
  README.md
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/README.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
Labels: New Policy, READY-FOR-REVIEW

#486 POL-255- Age field mismatch issue - Azure Delete Old Snapshots
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/README.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
Labels: READY-FOR-REVIEW, bug
