Repository flexera-public/policy_templates, pull requests merged in 2020-02, with the labels that each got.

#442 Pol 179 1965254 dimension information missing
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: bug, changelog

#443 remove version from long_description
  compliance/aws/ecs_unused/aws_unused_ecs_clusters.pt
  operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
  security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes.pt
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW

#445 POL-173 Update Azure policies for credential service 2
  compliance/azure/ahub_manual/CHANGELOG.md
  compliance/azure/ahub_manual/README.md
  compliance/azure/ahub_manual/azure_ahub_utilization_with_manual_entry.pt
  compliance/azure/compliance_score/CHANGELOG.md
  compliance/azure/compliance_score/README.md
  compliance/azure/compliance_score/azure_regulatory_compliance_report.pt
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/README.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  operational/azure/vms_without_managed_disks/CHANGELOG.md
  operational/azure/vms_without_managed_disks/README.md
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
Labels: Cred, READY-FOR-REVIEW

#448 Pol 166 update google policies for credential service 1
  compliance/google/long_stopped_instances/CHANGELOG.md
  compliance/google/long_stopped_instances/README.md
  compliance/google/long_stopped_instances/google_long_stopped_instances.pt
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/README.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/README.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
  cost/google/object_storage_optimization/CHANGELOG.md
  cost/google/object_storage_optimization/README.md
  cost/google/object_storage_optimization/google_object_storage_optimization.pt
  security/storage/google/public_buckets/CHANGELOG.md
  security/storage/google/public_buckets/README.md
  security/storage/google/public_buckets/google_public_buckets.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#449 Fix pol sync
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW

#452 Pol 174 update google policies for credential service 2
  cost/google/cloudsql_rightsizing/CHANGELOG.md
  cost/google/cloudsql_rightsizing/README.md
  cost/google/cloudsql_rightsizing/google_cloudsql_rightsizing.pt
  cost/google/cud_expiration/CHANGELOG.md
  cost/google/cud_expiration/README.md
  cost/google/cud_expiration/google_cud_expiration_report.pt
  cost/google/cud_report/CHANGELOG.md
  cost/google/cud_report/README.md
  cost/google/cud_report/google_committed_usediscount_report.pt
  cost/google/unused_cloudsql_instances/CHANGELOG.md
  cost/google/unused_cloudsql_instances/README.md
  cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt
  cost/google/unutilized_ip_addresses/CHANGELOG.md
  cost/google/unutilized_ip_addresses/README.md
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Labels: READY-FOR-REVIEW, changelog, enhancement

#450 POL-193 - add minimum spend to billing center cost anomaly
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/README.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
Labels: READY-FOR-REVIEW, enhancement

#456 POL-188 Updating IAM Policies.
  cost/aws/idle_compute_instances/README.md
  cost/aws/instance_cloudwatch_utilization/README.md
Labels: READY-FOR-REVIEW

#453 POL-189 Credential Service changes
  compliance/tags/azure_rg_tags/CHANGELOG.md
  compliance/tags/azure_rg_tags/README.md
  compliance/tags/azure_rg_tags/azure_resource_group_tags.pt
Labels: Cred, READY-FOR-REVIEW

#455 POL-115 Budget Alerts - Updating to today - 3
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/README.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW

#457 POL-205 Google Old Snapshots
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/README.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
Labels: READY-FOR-REVIEW

#447 POL-182 - Delete resources error in Azure Disallowed Regions
  compliance/azure/azure_disallowed_regions/CHANGELOG.md
  compliance/azure/azure_disallowed_regions/README.md
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
Labels: bug

#458 Pol 169 AWS Delete UnAttached Volumes
  README.md
  cost/aws/unattached_volumes/CHANGELOG.md
  cost/aws/unattached_volumes/README.md
  cost/aws/unattached_volumes/aws_delete_unattached_volumes.pt
Labels: New Policy, READY-FOR-REVIEW

#459 Pol-171 Google delete unattached volumes
  README.md
  cost/google/unattached_volumes/CHANGELOG.md
  cost/google/unattached_volumes/README.md
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
Labels: READY-FOR-REVIEW

#460 Pol 218 budget alert policy evaluation exceeded maximum time
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/README.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW, bug, changelog, enhancement
