Repository flexera-public/policy_templates, pull requests merged in 2020-04, with the labels that each got.

#494 POL-224 Updating for first day.
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW

#492 POL-219 - fixing no data table defect 
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
Labels: READY-FOR-REVIEW, bug, changelog

#495 CET-11 - Add branch protection escalation action
  compliance/github/repository_branch_protection/CHANGELOG.md
  compliance/github/repository_branch_protection/README.md
  compliance/github/repository_branch_protection/repository_branch_protection.pt
Labels: READY-FOR-REVIEW, enhancement

#498 POL-260 Google unattached volumes unhandled errors when executing
  cost/google/unattached_volumes/CHANGELOG.md
  cost/google/unattached_volumes/README.md
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
Labels: READY-FOR-REVIEW, bug, changelog

#500 POL-190 - Update FSM policies with new endpoint
  saas/fsm/renewal_reminder/CHANGELOG.md
  saas/fsm/renewal_reminder/README.md
  saas/fsm/renewal_reminder/fsm-renewal_reminder.pt
  saas/fsm/suspicious_users/CHANGELOG.md
  saas/fsm/suspicious_users/README.md
  saas/fsm/suspicious_users/fsm-suspicious_users.pt
  saas/fsm/unsanctioned_spend/CHANGELOG.md
  saas/fsm/unsanctioned_spend/README.md
  saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
  saas/fsm/user_status_change/CHANGELOG.md
  saas/fsm/user_status_change/README.md
  saas/fsm/user_status_change/fsm-user_status_change.pt
Labels: Cred, READY-FOR-REVIEW, changelog, enhancement

#502 Pol 267 case 02061648 readme missing from policy details
  cost/rightlink_rightsize/CHANGELOG.md
  cost/rightlink_rightsize/rightlink_rightsize.pt
  cost/unattached_addresses/CHANGELOG.md
  cost/unattached_addresses/unattached_addresses.pt
  cost/volumes/unattached_volumes/CHANGELOG.md
  cost/volumes/unattached_volumes/uav_policy.pt
Labels: READY-FOR-REVIEW, bug, changelog

#503 POL-265 Google cloud policies ERROR when executing with multiple projects.
  compliance/google/long_stopped_instances/CHANGELOG.md
  compliance/google/long_stopped_instances/README.md
  compliance/google/long_stopped_instances/google_long_stopped_instances.pt
  cost/google/cloudsql_rightsizing/CHANGELOG.md
  cost/google/cloudsql_rightsizing/README.md
  cost/google/cloudsql_rightsizing/google_cloudsql_rightsizing.pt
  cost/google/cud_expiration/CHANGELOG.md
  cost/google/cud_expiration/README.md
  cost/google/cud_expiration/google_cud_expiration_report.pt
  cost/google/cud_report/CHANGELOG.md
  cost/google/cud_report/README.md
  cost/google/cud_report/google_committed_usediscount_report.pt
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/README.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/README.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
  cost/google/object_storage_optimization/CHANGELOG.md
  cost/google/object_storage_optimization/README.md
  cost/google/object_storage_optimization/google_object_storage_optimization.pt
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
  cost/google/unused_cloudsql_instances/CHANGELOG.md
  cost/google/unused_cloudsql_instances/README.md
  cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt
  cost/google/unutilized_ip_addresses/CHANGELOG.md
  cost/google/unutilized_ip_addresses/README.md
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
  security/storage/google/public_buckets/CHANGELOG.md
  security/storage/google/public_buckets/README.md
  security/storage/google/public_buckets/google_public_buckets.pt
Labels: READY-FOR-REVIEW, bug, changelog

#505 POL-261 - Add department to user output
  saas/fsm/user_status_change/CHANGELOG.md
  saas/fsm/user_status_change/fsm-user_status_change.pt
Labels: READY-FOR-REVIEW, enhancement

#508 POL-270 - RightSize Azure SQL: bug fix
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
Labels: READY-FOR-REVIEW

#507 POL-269 - Azure Compliance Score: bug fix
  compliance/azure/compliance_score/CHANGELOG.md
  compliance/azure/compliance_score/azure_regulatory_compliance_report.pt
Labels: READY-FOR-REVIEW

#506 Pol 167 update saa s policies for credential service
  compliance/github/available_seats/CHANGELOG.md
  compliance/github/available_seats/README.md
  compliance/github/available_seats/available_seats.pt
  compliance/github/outside_collaborators/CHANGELOG.md
  compliance/github/outside_collaborators/README.md
  compliance/github/outside_collaborators/outside_collaborators.pt
  compliance/github/repository_admin_team/CHANGELOG.md
  compliance/github/repository_admin_team/README.md
  compliance/github/repository_admin_team/repository_admin_team.pt
  compliance/github/repository_branch_protection/CHANGELOG.md
  compliance/github/repository_branch_protection/README.md
  compliance/github/repository_branch_protection/repository_branch_protection.pt
  compliance/github/repository_naming/CHANGELOG.md
  compliance/github/repository_naming/README.md
  compliance/github/repository_naming/repository_naming.pt
  compliance/github/repository_size/CHANGELOG.md
  compliance/github/repository_size/README.md
  compliance/github/repository_size/repository_size.pt
  compliance/github/toplevel_teams/CHANGELOG.md
  compliance/github/toplevel_teams/README.md
  compliance/github/toplevel_teams/toplevel_teams.pt
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/README.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/utilization/CHANGELOG.md
  cost/azure/reserved_instances/utilization/README.md
  cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
  saas/office365/security_alerts/CHANGELOG.md
  saas/office365/security_alerts/README.md
  saas/office365/security_alerts/o365-security-alerts.pt
  saas/okta/inactive_users/CHANGELOG.md
  saas/okta/inactive_users/README.md
  saas/okta/inactive_users/okta-inactive-users.pt
Labels: Cred, READY-FOR-REVIEW

#510 POL-175-Update-Non-Credential-Policy-info-field
  cost/rightlink_rightsize/rightlink-rightsize-add-tags.pt
Labels: READY-FOR-REVIEW, enhancement

#514 POL-271 Fix AWS RI policies
  cost/aws/reserved_instances/expiration/CHANGELOG.md
  cost/aws/reserved_instances/expiration/expired_ris.pt
  cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
  cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
  cost/aws/reserved_instances/utilization/CHANGELOG.md
  cost/aws/reserved_instances/utilization/utilization_ris.pt
Labels: READY-FOR-REVIEW

#518 POL-272-Google Old Snapshots to many emails
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
Labels: changelog, enhancement
