Repository flexera-public/policy_templates, pull requests merged in 2021-07, with the labels that each got.

#709 SEG-665 Azure SQL Without Elastic DB Pools
  operational/azure/azure_sql_using_elastic_pool/README.md
  operational/azure/azure_sql_using_elastic_pool/azure_sql_instances_without_elastic_pools.pt
  operational/azure/azure_sql_using_elastic_pool/changelog.md
Labels: New Policy, READY-FOR-REVIEW

#715 POL-430 add check that AWS account array name exists before assigning it
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
Labels: bug

#714 SEG-664 Azure Lifecycle Management Policy
  README.md
  cost/azure/storage_account_lifecycle_management/CHANGELOG.md
  cost/azure/storage_account_lifecycle_management/README.md
  cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management.pt
Labels: New Policy, READY-FOR-REVIEW

#716 July 7th 2021 - Add Missing RDS Instance Sizes
  data/aws/instance_types.json
Labels: READY-FOR-REVIEW, small fixes

#717 POL-445: RDS Rightsizing Policy: Update next instance size logic to account for missing size
  cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
Labels: READY-FOR-REVIEW, bug, small fixes

#719 CMLS-83: Add checks on labels field
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
Labels: bug
