Repository flexera-public/policy_templates, pull requests merged in 2021-03, with the labels that each got.

#659 AWS Unused Volumes: Sleep more to be friendly to CWF
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Labels: READY-FOR-REVIEW

#657 CET-977 Use GitHub GraphQL for enforcing branch protection
  compliance/github/repository_branch_protection/CHANGELOG.md
  compliance/github/repository_branch_protection/README.md
  compliance/github/repository_branch_protection/repository_branch_protection.pt
Labels: enhancement

#660 POL-417: top 10 cost categories not just for current month.
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: bug

#661 POL-416: Run Rate label fixed.
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/superseded_instance.pt
Labels: bug

#652 POL 395 azure mca reservation recommendations/expiration
  README.md
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/README.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
Labels: New Policy, READY-FOR-REVIEW, changelog

#663 fix readme
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
Labels: READY-FOR-REVIEW

#662 Azure hybrid use benefit linux
  README.md
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/README.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
  policy_templates.code-workspace
Labels: New Policy

#664 Ahub for linux fixes
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/README.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
Labels: small fixes

#665 POL-413: Get type from resource, and check whether it supports tags
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/README.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
  data/azure/tag-support.csv
Labels: enhancement
