Repository flexera-public/policy_templates, pull requests merged in 2021-06, with the labels that each got.

#696 Fix trim vuln
  package-lock.json
  package.json
Labels: READY-FOR-REVIEW

#700 CMLS-26 CMLS-27: Use OAuth2 FlexeraOne creds in EU region, and use rs_optima_host
  cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
  cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
  cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
Labels: enhancement

#702 POL-400 Check for VPCs without flow logs enabled
  README.md
  security/aws/vpcs_without_flow_logs_enabled/CHANGELOG.md
  security/aws/vpcs_without_flow_logs_enabled/README.md
  security/aws/vpcs_without_flow_logs_enabled/aws_vpcs_without_flow_logs_enabled.pt
Labels: New Policy

#703 POL-435 Lambda Functions with High Error Rate
  README.md
  operational/aws/lambda_functions_with_high_error_rate/CHANGELOG.md
  operational/aws/lambda_functions_with_high_error_rate/README.md
  operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate.pt
Labels: New Policy

#704 CMLS-28 CMLS-29: Replacing built-in rightscale auth with FlexeraOne OAuth2 credentials
  README.md
  cost/aws/reserved_instances/expiration/expired_ris.pt
  cost/aws/reserved_instances/utilization/utilization_ris.pt
  operational/aws/lambda_functions_with_high_error_rate/CHANGELOG.md
  operational/aws/lambda_functions_with_high_error_rate/README.md
  operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate.pt
  package-lock.json
  package.json
  security/aws/vpcs_without_flow_logs_enabled/CHANGELOG.md
  security/aws/vpcs_without_flow_logs_enabled/README.md
  security/aws/vpcs_without_flow_logs_enabled/aws_vpcs_without_flow_logs_enabled.pt
Labels: enhancement

#705 POL-441 AWS S3 Intelligent Tiering Policy
  README.md
  cost/aws/gp3_volume_upgrade/README.md
  cost/aws/s3_storage_policy/CHANGELOG.md
  cost/aws/s3_storage_policy/README.md
  cost/aws/s3_storage_policy/aws_s3_bucket_policy_check.pt
  policy_templates.code-workspace
Labels: New Policy, READY-FOR-REVIEW

#706 CMLS-31 CMLS-32 CMLS-34: RightScale auth to FlexeraOne OAuth2
  cost/budget_v_actual/monthly_budget_v_actual.pt
  cost/superseded_instance/superseded_instance.pt
Labels: enhancement

#708 CMLS-65 update aws_unused_ip_addresses.pt unused_rds.pt aws_delete_un…
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_rds/unused_rds.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Labels: bug

#710 POL-442 Adding Budget Alert Threshold
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/README.md
  cost/budget_alerts/budget_alert.pt
Labels: READY-FOR-REVIEW, enhancement

#707 CMLS-11: Make debug a param (off by default), plus other fixes.
  cost/aws/elb/clb_unused/CHANGELOG.md
  cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/instances_log_analytics_utilization/CHANGELOG.md
  cost/azure/instances_log_analytics_utilization/azure_instance_log_analytics_utilization.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
  cost/google/cloudsql_rightsizing/CHANGELOG.md
  cost/google/cloudsql_rightsizing/google_cloudsql_rightsizing.pt
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
  cost/google/unattached_volumes/CHANGELOG.md
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
  cost/google/unused_cloudsql_instances/CHANGELOG.md
  cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt
  cost/google/unutilized_ip_addresses/CHANGELOG.md
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Labels: enhancement

#712 CMLS-69: rightscale auth to FlexeraOne OAuth2 credentials.
  cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/schedule_instance/azure_schedule_instance.pt
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
  cost/google/schedule_instance/google_schedule_instance.pt
Labels: enhancement

#713 Cmls 66 budget alerts by account
  cost/budget_alerts_by_account/CHANGELOG.md
  cost/budget_alerts_by_account/budget_alerts_by_account.pt
Labels: bug

#698 Policy Readme Permission Tweaks.
  cost/google/instances_stackdriver_utilization/README.md
  security/aws/unencrypted_s3_buckets/README.md
Labels: small fixes
