Repository flexera-public/policy_templates, pull requests merged in 2021-04, with the labels that each got.

#669 IND-4243: Policies can't log to CM audit entries in EU, so disable that (e.g. via param).
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
Labels: enhancement

#670 IND-4215: OAuth2 pols Sched.reports and BC cost anomalies
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/README.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
Labels: enhancement

#671 POL-424: Cleaning up "deadwood" code.
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
Labels: enhancement

#673 IND-4219: Fixed HERE doc markdown alignment.
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: bug

#672 POL-425: Drop namespace from resource type when looking up API versions.
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
Labels: bug

#674 POL-424: Added missing pagination to GCP request for snapshot list.
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
Labels: bug

#667 changes for filter
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
Labels: bug

#676 Pol 426 policy low account usage
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/low_account_usage.pt
Labels: bug

#675 POL-427: for metrics, right api-version, and one-day interval.
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Labels: bug

#677 Initial release AHUB for SQL
  README.md
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/README.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
Labels: New Policy

#679 Google Inefficient Instance Utilization Policy - Mem 'NaN' Bug Fix
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
Labels: READY-FOR-REVIEW, bug

#680 POL-428: Fixing superseded instances policy template.
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/superseded_instance.pt
Labels: bug

#682 updated doc link and version
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
Labels: changelog

#681 IND-4269: OAuth creds for low service usage
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
  cost/low_service_usage/CHANGELOG.md
  cost/low_service_usage/low_service_usage.pt
Labels: enhancement

#683 CMLS-9 POL-418: ensure >= 1 mo cost data retrieved
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/superseded_instance.pt
Labels: bug
