Repository flexera-public/policy_templates, pull requests merged in 2021-09, with the labels that each got.

#726 POL-461 AWS Prevent Password Reuse
  security/aws/iam_prevent_password_reuse/CHANGELOG.md
  security/aws/iam_prevent_password_reuse/README.md
  security/aws/iam_prevent_password_reuse/iam_prevent_password_reuse.pt
Labels: READY-FOR-REVIEW

#724 POL-458 AWS 1.6 Ensure hardware MFA is enabled for the 'root' user account
  README.md
  security/aws/iam_hwmfa_enabled_for_root/CHANGELOG.md
  security/aws/iam_hwmfa_enabled_for_root/README.md
  security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
Labels: READY-FOR-REVIEW

#723 POL-454 No Root Account Access Key
  README.md
  security/aws/iam_no_root_access_keys/CHANGELOG.md
  security/aws/iam_no_root_access_keys/README.md
  security/aws/iam_no_root_access_keys/aws_iam_no_root_access_keys.pt
Labels: READY-FOR-REVIEW

#728 POL-457 Adding CFT for ReadOnly rights
  README.md
  cost/aws/FlexeraReadOnlyPolicy.template
Labels: READY-FOR-REVIEW

#730 POL-464 Adding in Google Recommender Policy
  cost/google/recommender/CHANGELOG.md
  cost/google/recommender/README.md
  cost/google/recommender/recommender.pt
Labels: READY-FOR-REVIEW, New Policy

#733 POL-449: Convert resource type to lowercase for comparisons
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
Labels: bug

#734 Pol 459 no root for everyday tasks
  package-lock.json
  package.json
  security/aws/iam_no_root_for_tasks/CHANGELOG.md
  security/aws/iam_no_root_for_tasks/README.md
  security/aws/iam_no_root_for_tasks/iam_no_root_for_tasks.pt
Labels: READY-FOR-REVIEW

#738 Updated Azure Instance Sizes
  data/azure/instance_types.json
Labels: READY-FOR-REVIEW, READY FOR APPROVAL

#737 Pol 468 rotate access keys
  README.md
  security/aws/iam_rotate_access_keys/CHANGELOG.md
  security/aws/iam_rotate_access_keys/README.md
  security/aws/iam_rotate_access_keys/iam_rotate_access_keys.pt
Labels: READY-FOR-REVIEW

#736 Pol 462 ensure mfa for all iam users
  README.md
  security/aws/iam_mfa_enabled_for_iam_users/CHANGELOG.md
  security/aws/iam_mfa_enabled_for_iam_users/README.md
  security/aws/iam_mfa_enabled_for_iam_users/iam_mfa_enabled_for_iam_users.pt
Labels: READY-FOR-REVIEW

#739 fixed version numbers and metadata
  security/aws/iam_hwmfa_enabled_for_root/CHANGELOG.md
  security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
  security/aws/iam_mfa_enabled_for_iam_users/CHANGELOG.md
  security/aws/iam_mfa_enabled_for_iam_users/iam_mfa_enabled_for_iam_users.pt
  security/aws/iam_min_password_length/CHANGELOG.md
  security/aws/iam_min_password_length/iam_min_password_length.pt
  security/aws/iam_no_root_access_keys/CHANGELOG.md
  security/aws/iam_no_root_access_keys/aws_iam_no_root_access_keys.pt
  security/aws/iam_no_root_for_tasks/CHANGELOG.md
  security/aws/iam_no_root_for_tasks/iam_no_root_for_tasks.pt
  security/aws/iam_prevent_password_reuse/CHANGELOG.md
  security/aws/iam_prevent_password_reuse/iam_prevent_password_reuse.pt
  security/aws/iam_rotate_access_keys/CHANGELOG.md
  security/aws/iam_rotate_access_keys/iam_rotate_access_keys.pt
Labels: READY-FOR-REVIEW

#743 Google Recommender Policy - Updating short description
  cost/google/recommender/CHANGELOG.md
  cost/google/recommender/README.md
  cost/google/recommender/recommender.pt
Labels: READY-FOR-REVIEW

#742 IAM Rotate Access Keys - Fix Subject Header
  security/aws/iam_rotate_access_keys/CHANGELOG.md
  security/aws/iam_rotate_access_keys/iam_rotate_access_keys.pt
Labels: READY-FOR-REVIEW

#747 Updating Danger
  Gemfile
  Gemfile.lock
Labels: READY-FOR-REVIEW

#735 Pol 467 disable 45 day creds
  README.md
  security/aws/iam_disable_45_day_creds/CHANGELOG.md
  security/aws/iam_disable_45_day_creds/README.md
  security/aws/iam_disable_45_day_creds/iam_disable_45_day_creds.pt
Labels: READY-FOR-REVIEW

#722 POL-480 deprecating Azure RI with new version, supporting more RI Types
  .nvmrc
  .travis.yml
  README.md
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/README.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/README.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
  package-lock.json
  package.json
Labels: READY-FOR-REVIEW

#744 IND-4576 Azure Unused Volumes - Adding filter for results
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
Labels: READY-FOR-REVIEW

#751 POL-484 EU Policy Updates
  .nvmrc
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
  compliance/azure/subscription_access/CHANGELOG.md
  compliance/azure/subscription_access/azure_subscription_access.pt
  cost/aws/FlexeraReadOnlyPolicy.template
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/README.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/README.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
  cost/google/recommender/CHANGELOG.md
  cost/google/recommender/README.md
  cost/google/recommender/recommender.pt
  data/azure/instance_types.json
  package-lock.json
  package.json
  security/aws/iam_disable_45_day_creds/CHANGELOG.md
  security/aws/iam_disable_45_day_creds/README.md
  security/aws/iam_disable_45_day_creds/iam_disable_45_day_creds.pt
  security/aws/iam_hwmfa_enabled_for_root/CHANGELOG.md
  security/aws/iam_hwmfa_enabled_for_root/README.md
  security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
  security/aws/iam_mfa_enabled_for_iam_users/CHANGELOG.md
  security/aws/iam_mfa_enabled_for_iam_users/README.md
  security/aws/iam_mfa_enabled_for_iam_users/iam_mfa_enabled_for_iam_users.pt
  security/aws/iam_min_password_length/CHANGELOG.md
  security/aws/iam_min_password_length/README.md
  security/aws/iam_min_password_length/iam_min_password_length.pt
  security/aws/iam_no_root_access_keys/CHANGELOG.md
  security/aws/iam_no_root_access_keys/README.md
  security/aws/iam_no_root_access_keys/aws_iam_no_root_access_keys.pt
  security/aws/iam_no_root_for_tasks/CHANGELOG.md
  security/aws/iam_no_root_for_tasks/README.md
  security/aws/iam_no_root_for_tasks/iam_no_root_for_tasks.pt
  security/aws/iam_prevent_password_reuse/CHANGELOG.md
  security/aws/iam_prevent_password_reuse/README.md
  security/aws/iam_prevent_password_reuse/iam_prevent_password_reuse.pt
  security/aws/iam_rotate_access_keys/CHANGELOG.md
  security/aws/iam_rotate_access_keys/README.md
  security/aws/iam_rotate_access_keys/iam_rotate_access_keys.pt
Labels: READY-FOR-REVIEW
