Repository flexera-public/policy_templates, pull requests merged in 2022-04, with the labels that each got.

#942 POL-584 Add AWS Savings Plan Utilization
  README.md
  cost/aws/savings_plan/utilization/CHANGELOG.md
  cost/aws/savings_plan/utilization/README.md
  cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
Labels: DO-NOT-MERGE, New Policy

#976 Azure CIS 2.13 Ensure 'Additional email addresses' is Configured with a Security Contact Email
  README.md
  security/azure/security_contact_email/CHANGELOG.md
  security/azure/security_contact_email/README.md
  security/azure/security_contact_email/security_contact_email.pt
Labels: READY-FOR-REVIEW

#978 Azure CIS 2.14 Ensure That 'Notify about alerts with the following severity' is Set to 'High'
  README.md
  security/azure/high_severity_alerts/CHANGELOG.md
  security/azure/high_severity_alerts/README.md
  security/azure/high_severity_alerts/high_severity_alerts.pt
Labels: READY-FOR-REVIEW

#979 2.15 Ensure That 'All users with the following roles' is set to 'Owner'
  README.md
  security/azure/security_alert_owners/CHANGELOG.md
  security/azure/security_alert_owners/README.md
  security/azure/security_alert_owners/security_alert_owners.pt
Labels: READY-FOR-REVIEW

#982 Azure CIS 3.1 Ensure that 'Secure transfer required' is set to 'Enabled'
  README.md
  security/azure/secure_transfer_required/CHANGELOG.md
  security/azure/secure_transfer_required/README.md
  security/azure/secure_transfer_required/secure_transfer_required.pt
Labels: READY-FOR-REVIEW

#987 Azure CIS 3.3 Ensure Storage Logging is Enabled for Queue Service for 'Read', 'Write', and 'Delete' requests
  README.md
  security/azure/queue_storage_logging/CHANGELOG.md
  security/azure/queue_storage_logging/README.md
  security/azure/queue_storage_logging/queue_storage_logging.pt
Labels: READY-FOR-REVIEW

#988 3.5 Ensure that 'Public access level' is set to Private for blob containers
  README.md
  security/azure/private_blob_containers/CHANGELOG.md
  security/azure/private_blob_containers/README.md
  security/azure/private_blob_containers/private_blob_containers.pt
Labels: READY-FOR-REVIEW

#989 Azure CIS 3.6 Ensure Default Network Access Rule for Storage Accounts is Set to Deny
  README.md
  security/azure/storage_network_deny/CHANGELOG.md
  security/azure/storage_network_deny/README.md
  security/azure/storage_network_deny/storage_network_deny.pt
Labels: READY-FOR-REVIEW

#994 Azure CIS 3.7 Ensure 'Trusted Microsoft Services' are Enabled for Storage Account Access
  README.md
  security/azure/storage_trusted_services/CHANGELOG.md
  security/azure/storage_trusted_services/README.md
  security/azure/storage_trusted_services/storage_trusted_services.pt
Labels: READY-FOR-REVIEW

#995 POL-608 Azure CIS 3.8 Ensure Soft Delete is Enabled for Azure Storage
  README.md
  security/azure/storage_soft_delete/CHANGELOG.md
  security/azure/storage_soft_delete/README.md
  security/azure/storage_soft_delete/storage_soft_delete.pt
Labels: READY-FOR-REVIEW

#1003 POL-615 Adding rs_governance_host
  operational/applied_policy_error_notification/CHANGELOG.md
  operational/applied_policy_error_notification/applied_policy_error_notification.pt
Labels: READY-FOR-REVIEW

#999 Azure CIS 3.10/3.11 Ensure Storage logging is Enabled for Blob/Table Service for 'Read', 'Write', and 'Delete' requests
  README.md
  security/azure/blob_storage_logging/CHANGELOG.md
  security/azure/blob_storage_logging/README.md
  security/azure/blob_storage_logging/blob_storage_logging.pt
  security/azure/table_storage_logging/CHANGELOG.md
  security/azure/table_storage_logging/README.md
  security/azure/table_storage_logging/table_storage_logging.pt
Labels: READY-FOR-REVIEW

#1000 Azure CIS 3.12 Ensure the "Minimum TLS version" is set to "Version 1.2"
  README.md
  security/azure/storage_tls_version/CHANGELOG.md
  security/azure/storage_tls_version/README.md
  security/azure/storage_tls_version/storage_tls_version.pt
Labels: READY-FOR-REVIEW

#1001 POL-611 Invert AWS Disallowed Regions Policy
  compliance/aws/disallowed_regions/CHANGELOG.md
  compliance/aws/disallowed_regions/README.md
  compliance/aws/disallowed_regions/aws_disallowed_regions.pt
Labels: READY-FOR-REVIEW

#1002 Azure CIS 4.1.1 Ensure that 'Auditing' is set to 'On'
  README.md
  security/azure/sql_server_auditing/CHANGELOG.md
  security/azure/sql_server_auditing/README.md
  security/azure/sql_server_auditing/sql_server_auditing.pt
Labels: READY-FOR-REVIEW

#1009 Pol 619 adding subscription name
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
Labels: READY-FOR-REVIEW

#1017 Azure CIS 4.2.2 Ensure that Vulnerability Assessment (VA) is enabled on a SQL server by setting a Storage Account
  README.md
  security/azure/sql_server_va/CHANGELOG.md
  security/azure/sql_server_va/README.md
  security/azure/sql_server_va/sql_server_va.pt
Labels: READY-FOR-REVIEW

#1015 POL-620 Update Azure RI Recommendations (Add Instance Group attributes)
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
Labels: READY-FOR-REVIEW, small fixes

#1020 Azure CIS 4.2.4 4.2.5
  README.md
  security/azure/sql_server_va_admins/CHANGELOG.md
  security/azure/sql_server_va_admins/README.md
  security/azure/sql_server_va_admins/sql_server_va_admins.pt
  security/azure/sql_server_va_emails/CHANGELOG.md
  security/azure/sql_server_va_emails/README.md
  security/azure/sql_server_va_emails/sql_server_va_emails.pt
Labels: READY-FOR-REVIEW

#1028 Azure CIS 4.5 Ensure that Azure Active Directory Admin is configured
  README.md
  security/azure/sql_ad_admin/CHANGELOG.md
  security/azure/sql_ad_admin/README.md
  security/azure/sql_ad_admin/sql_ad_admin.pt
Labels: READY-FOR-REVIEW

#1026 Azure CIS 4.4.1 Ensure 'Enforce SSL connection' is set to 'Enabled' for Standard MySQL Database Server
  README.md
  security/azure/mysql_ssl/CHANGELOG.md
  security/azure/mysql_ssl/README.md
  security/azure/mysql_ssl/mysql_ssl.pt
Labels: READY-FOR-REVIEW

#1025 Azure CIS 4.3.8 Ensure 'Infrastructure double encryption' for PostgreSQL Database Server is 'Enabled'
  README.md
  security/azure/pg_infra_encryption/CHANGELOG.md
  security/azure/pg_infra_encryption/README.md
  security/azure/pg_infra_encryption/pg_infra_encryption.pt
Labels: READY-FOR-REVIEW

#1029 POL-637 Straight Line Forecast policy enhancements
  README.md
  cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
  cost/forecasting/straight_line_forecast/linear_regression/README.md
  cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
  cost/forecasting/straight_line_forecast/simple/README.md
  cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
  cost/forecasting/straight_line_forecast/straight_line_forecast.pt
Labels: enhancement, READY-FOR-REVIEW, New Policy

#1035 Azure CIS 6.1 Restrict azure rdp from inet
  README.md
  security/azure/restrict_rdp_internet/CHANGELOG.md
  security/azure/restrict_rdp_internet/README.md
  security/azure/restrict_rdp_internet/azure_restrict_rdp_inet.pt
Labels: READY-FOR-REVIEW, New Policy

#1036 Pol 641 ssh ports open to the internet
  README.md
  security/azure/restrict_ssh_internet/CHANGELOG.md
  security/azure/restrict_ssh_internet/README.md
  security/azure/restrict_ssh_internet/azure_restrict_ssh_inet.pt
Labels: READY-FOR-REVIEW, New Policy
