Repository flexera-public/policy_templates, pull requests merged in 2022-02, with the labels that each got.

#916 Pol 554 AWS RI and Savings Plan Currency Adjustments
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/README.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/README.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
Labels: READY-FOR-REVIEW, Cred

#922 POL-570 straight line forecast
  README.md
  cost/forecasting/straight_line_forecast/CHANGELOG.md
  cost/forecasting/straight_line_forecast/README.md
  cost/forecasting/straight_line_forecast/straight_line_forecast.pt
Labels: READY-FOR-REVIEW, New Policy

#872 FINOPS-112 Use AWS Pricing API for AWS Unused IP Addresses
  .vscode/settings.json
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/README.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
Labels: READY-FOR-REVIEW

#921 Lawrethao patch pol 554
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
Labels: READY FOR APPROVAL

#926 POL-569 Removed ds_session and synced ds_billing_center
  cost/budget_alerts_by_account/CHANGELOG.md
  cost/budget_alerts_by_account/budget_alerts_by_account.pt
Labels: READY-FOR-REVIEW
