Repository flexera-public/policy_templates, pull requests merged in 2022-03, with the labels that each got.

#933 Pol 571 moving average forecast
  README.md
  cost/forecasting/moving_average/CHANGELOG.md
  cost/forecasting/moving_average/README.md
  cost/forecasting/moving_average/moving_average_forecast.pt
Labels: DO-NOT-MERGE

#929 Pol 563 Make Azure policies ready for spend recommendations
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/README.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/README.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/README.md
  cost/aws/unused_rds/unused_rds.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/README.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/README.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/README.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/README.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/README.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/README.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
Labels: READY-FOR-REVIEW

#940 Pol 569 correcting top level billing center
  cost/budget_alerts_by_account/CHANGELOG.md
  cost/budget_alerts_by_account/budget_alerts_by_account.pt
Labels: READY-FOR-REVIEW

#941 POL-579 Bill Processing Status Policy
  README.md
  operational/bill_processing_errors_notification/CHANGELOG.md
  operational/bill_processing_errors_notification/README.md
  operational/bill_processing_errors_notification/bill_processing_errors_notification.pt
Labels: READY-FOR-REVIEW, New Policy

#944 POL-585 ITAM Missing Active Machines
  README.md
  compliance/fnms/missing_active_machines/CHANGELOG.md
  compliance/fnms/missing_active_machines/README.md
  compliance/fnms/missing_active_machines/missing_active_machines.pt
Labels: READY-FOR-REVIEW

#955 Updated Documentation
  operational/bill_processing_errors_notification/README.md
Labels: enhancement

#956 Pol 589 budget alert issue
  cost/budget_alerts_by_account/CHANGELOG.md
  cost/budget_alerts_by_account/budget_alerts_by_account.pt
Labels: READY-FOR-REVIEW

#948 ITAM Policy: VMs Without Host ID
  README.md
  compliance/fnms/vms_missing_hostid/CHANGELOG.md
  compliance/fnms/vms_missing_hostid/README.md
  compliance/fnms/vms_missing_hostid/vms_missing_hostid.pt
Labels: READY-FOR-REVIEW

#954 FNMS Overused Licenses Policy
  README.md
  compliance/fnms/overused_licenses/CHANGELOG.md
  compliance/fnms/overused_licenses/README.md
  compliance/fnms/overused_licenses/overused_licenses.pt
Labels: READY-FOR-REVIEW

#964 Azure CIS 1.3 Ensure guest users are reviewed on a monthly basis
  README.md
  security/azure/guest_users/CHANGELOG.md
  security/azure/guest_users/README.md
  security/azure/guest_users/guest_users.pt
Labels: READY-FOR-REVIEW

#957 Optima.rightscale.com redaction
  cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
  cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/unused_rds.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
  cost/forecasting/straight_line_forecast/CHANGELOG.md
  cost/forecasting/straight_line_forecast/straight_line_forecast.pt
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/low_account_usage.pt
  cost/low_service_usage/CHANGELOG.md
  cost/low_service_usage/low_service_usage.pt
  cost/new_service_usage/CHANGELOG.md
  cost/new_service_usage/new_service_usage.pt
  operational/azure/sync_tags_with_optima/CHANGELOG.md
  operational/azure/sync_tags_with_optima/sync_azure_tags.pt
Labels: READY-FOR-REVIEW

#972 Pol 596 rs optima host keyword
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Labels: READY-FOR-REVIEW

#950 POL-586 Add AWS Number of Hours per Instance Family
  cost/aws/total_instance_hours/CHANGELOG.md
  cost/aws/total_instance_hours/README.md
  cost/aws/total_instance_hours/number_of_hours_per_instance_family.pt
  data/aws/instance_types.json
Labels: READY-FOR-REVIEW, New Policy

#951 POL-590 Add AWS Number of vCPUs per Instance Family
  README.md
  cost/aws/total_instance_vcpus/CHANGELOG.md
  cost/aws/total_instance_vcpus/README.md
  cost/aws/total_instance_vcpus/number_of_vcpus_per_instance_family.pt
Labels: DO-NOT-MERGE, New Policy
