Repository flexera-public/policy_templates, pull requests merged in 2022-01, with the labels that each got.

#759 POL-414 Adding AzureMCA and Google to Superseded and Cheaper Regions
  cost/cheaper_regions/CHANGELOG.md
  cost/cheaper_regions/cheaper_regions.pt
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/superseded_instance.pt
Labels: enhancement, READY-FOR-REVIEW

#871 FINOPS-119 Improve AWS Upgrade to GP3
  cost/aws/gp3_volume_upgrade/CHANGELOG.md
  cost/aws/gp3_volume_upgrade/README.md
  cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume.pt
Labels: READY-FOR-REVIEW

#873 feat: Migrate to GitHub Actions
  .github/workflows/test-policies.yaml
  .github/workflows/upload-files.yaml
  .travis.yml
Labels: READY-FOR-REVIEW

#889 SEG-887 - Updating ACL
  .github/workflows/upload-files.yaml
Labels: READY-FOR-REVIEW

#891 SEG-788 Fixing Long-Stopped Instances to report instances with uptime
  compliance/google/long_stopped_instances/CHANGELOG.md
  compliance/google/long_stopped_instances/google_long_stopped_instances.pt
  policy_templates.code-workspace
Labels: READY-FOR-REVIEW

#895 updating markdown-it
  package-lock.json
  package.json
Labels: READY-FOR-REVIEW

#896 POL-557 - Update Azure Policies to ignore non-Azure Subscriptions
  compliance/azure/ahub_manual/CHANGELOG.md
  compliance/azure/ahub_manual/azure_ahub_utilization_with_manual_entry.pt
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/storage_account_lifecycle_management/CHANGELOG.md
  cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management.pt
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
  security/azure/sql_publicly_accessible_managed_instance/CHANGELOG.md
  security/azure/sql_publicly_accessible_managed_instance/check_for_publicly_accessible_azure_sql_managed_instance.pt
  security/azure/webapp_tls_version_support/CHANGELOG.md
  security/azure/webapp_tls_version_support/azure_webapp_min_tls_version.pt
Labels: changelog, READY-FOR-REVIEW

#875 Create inactive_users_for_integrated_apps.pt
  saas/fsm/inactive_users_for_integrated_apps/CHANGELOG.md
  saas/fsm/inactive_users_for_integrated_apps/README.md
  saas/fsm/inactive_users_for_integrated_apps/inactive_users_for_integrated_apps.pt
Labels: READY-FOR-REVIEW, New Policy

#901 Update vpc name sync to stop publishing
  operational/aws/subnet_name_sync/CHANGELOG.md
  operational/aws/subnet_name_sync/aws_subnet_name_sync.pt
  operational/aws/vpc_name_sync/CHANGELOG.md
  operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW

#905 updating policy_sync for flexera-public and setting scheduled report …
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW

#903 POL-559 Update SaaS Manager Inactive Users for Integrated Apps
  saas/fsm/inactive_users_for_integrated_apps/CHANGELOG.md
  saas/fsm/inactive_users_for_integrated_apps/inactive_users_for_integrated_apps.pt
Labels: READY-FOR-REVIEW, small fixes

#899 Adding pricing:GetProducts to ReadOnly cft
  .github/workflows/cfn-lint.yaml
  cost/aws/FlexeraReadOnlyPolicy.template
Labels: READY-FOR-REVIEW

#912 added WSL2 support
  .vscode/settings.json
Labels: READY-FOR-REVIEW

#887 POL-501 Google CUD Recommendations
  README.md
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/README.md
  cost/google/cud_recommendations/google_cud_recommendations.pt
Labels: READY-FOR-REVIEW

#849 POL-521 - Make AWS policies ready for spend recommendations
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/unused_rds.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Labels: READY-FOR-REVIEW

#907 POL-560 Update SaaS Manager - Suspicious Users - email field and pagination fix
  saas/fsm/suspicious_users/CHANGELOG.md
  saas/fsm/suspicious_users/fsm-suspicious_users.pt
Labels: READY-FOR-REVIEW, small fixes
