Repository flexera-public/policy_templates, pull requests merged in 2022-05, with the labels that each got.

#1043 POL-643 Changes to Forecast/Usage Report Policy Names
  README.md
  cost/aws/total_instance_hours/CHANGELOG.md
  cost/aws/total_instance_vcpus/CHANGELOG.md
  cost/forecasting/commitment_forecast/README.md
  cost/forecasting/moving_average/CHANGELOG.md
  cost/forecasting/moving_average/README.md
  cost/forecasting/moving_average/moving_average_forecast.pt
  cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
  cost/forecasting/straight_line_forecast/linear_regression/README.md
  cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
  cost/forecasting/straight_line_forecast/simple/README.md
  cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
  operational/aws/total_instance_hours/CHANGELOG.md
  operational/aws/total_instance_hours/README.md
  operational/aws/total_instance_hours/number_of_hours_per_instance_family.pt
  operational/aws/total_instance_vcpus/CHANGELOG.md
  operational/aws/total_instance_vcpus/README.md
  operational/aws/total_instance_vcpus/number_of_vcpus_per_instance_family.pt
Labels: READY-FOR-REVIEW, small fixes

#945 POL-576 Add Azure Savings Realized
  README.md
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/README.md
  cost/azure/savings_realized/azure_savings_realized.pt
Labels: READY-FOR-REVIEW, New Policy

#1048 IND-5216 updated fields for savings and updated changelog
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_vm_recommendations/CHANGELOG.md
  cost/google/idle_vm_recommendations/google_vm_recommendations.pt
Labels: bug, READY-FOR-REVIEW

#1054 POL-650 Update Image Charts URL for Savings Realized policies
  cost/aws/savings_realized/CHANGELOG.md
  cost/aws/savings_realized/aws_savings_realized.pt
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
Labels: READY-FOR-REVIEW, small fixes

#1051 POL-648 Update Image Charts URL for policies
  cost/aws/savings_plan/utilization/CHANGELOG.md
  cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
  cost/forecasting/commitment_forecast/CHANGELOG.md
  cost/forecasting/commitment_forecast/commitment_forecast.pt
  cost/forecasting/moving_average/CHANGELOG.md
  cost/forecasting/moving_average/moving_average_forecast.pt
  cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
  cost/forecasting/straight_line_forecast/linear_regression/README.md
  cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
  cost/forecasting/straight_line_forecast/simple/README.md
  cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
  operational/aws/total_instance_hours/CHANGELOG.md
  operational/aws/total_instance_hours/number_of_hours_per_instance_family.pt
  operational/aws/total_instance_vcpus/CHANGELOG.md
  operational/aws/total_instance_vcpus/number_of_vcpus_per_instance_family.pt
Labels: enhancement, READY-FOR-REVIEW, small fixes

#1052 POL-646 Add AWS Usage Report Forecasting
  README.md
  operational/aws/total_instance_hours_forecast/CHANGELOG.md
  operational/aws/total_instance_hours_forecast/README.md
  operational/aws/total_instance_hours_forecast/aws_total_instance_hrs_forecast.pt
  operational/aws/total_instance_vcpus_forecast/CHANGELOG.md
  operational/aws/total_instance_vcpus_forecast/README.md
  operational/aws/total_instance_vcpus_forecast/aws_total_instance_vcpus_forecast.pt
Labels: READY-FOR-REVIEW, New Policy
