Repository flexera-public/policy_templates, pull requests merged in 2022-09, with the labels that each got.

#1112 POL-697 Deprecate Authentication - Forecast and Usage Report policies
  cost/aws/savings_plan/utilization/CHANGELOG.md
  cost/aws/savings_plan/utilization/README.md
  cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
  cost/aws/savings_realized/CHANGELOG.md
  cost/aws/savings_realized/README.md
  cost/aws/savings_realized/aws_savings_realized.pt
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/README.md
  cost/azure/savings_realized/azure_savings_realized.pt
  cost/forecasting/commitment_forecast/CHANGELOG.md
  cost/forecasting/commitment_forecast/README.md
  cost/forecasting/commitment_forecast/commitment_forecast.pt
  cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
  cost/forecasting/straight_line_forecast/linear_regression/README.md
  cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
  cost/forecasting/straight_line_forecast/simple/README.md
  cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
  operational/aws/total_instance_hours/CHANGELOG.md
  operational/aws/total_instance_hours/README.md
  operational/aws/total_instance_hours/number_of_hours_per_instance_family.pt
  operational/aws/total_instance_hours_forecast/CHANGELOG.md
  operational/aws/total_instance_hours_forecast/README.md
  operational/aws/total_instance_hours_forecast/aws_total_instance_hrs_forecast.pt
  operational/aws/total_instance_vcpus/CHANGELOG.md
  operational/aws/total_instance_vcpus/README.md
  operational/aws/total_instance_vcpus/number_of_vcpus_per_instance_family.pt
  operational/aws/total_instance_vcpus_forecast/CHANGELOG.md
  operational/aws/total_instance_vcpus_forecast/README.md
  operational/aws/total_instance_vcpus_forecast/aws_total_instance_vcpus_forecast.pt
Labels: READY-FOR-REVIEW

#1115 Fill in the policySet field to populate the new total potential savin…
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
Labels: enhancement, small fixes

#1116 Google policy set & correct auth_rs -> auth_flexera
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
Labels: enhancement

#1114 Tag cardinality
  README.md
  operational/aws/tag_cardinality/CHANGELOG.md
  operational/aws/tag_cardinality/README.md
  operational/aws/tag_cardinality/aws_tag_cardinality.pt
  operational/azure/tag_cardinality/CHANGELOG.md
  operational/azure/tag_cardinality/README.md
  operational/azure/tag_cardinality/azure_tag_cardinality.pt
Labels: READY-FOR-REVIEW

#1113 Pol 679 Cost Anomaly Detection Redux
  README.md
  cost/billing_center_cost_anomaly/CHANGELOG.md
  cost/billing_center_cost_anomaly/README.md
  cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
  cost/cloud_cost_anomalies/CHANGELOG.md
  cost/cloud_cost_anomalies/README.md
  cost/cloud_cost_anomalies/cloud_cost_anomalies.pt
Labels: READY-FOR-REVIEW

#1117 Pol 691
  data/azure/instance_types.json
Labels: READY-FOR-REVIEW
