Repository flexera-public/policy_templates, pull requests merged in 2023-06, with the labels that each got.

#1301 Oracle Bill Ingestion README Update
  cost/oracle/oracle_cbi/README.md
Labels: READY-FOR-REVIEW

#1303 Google Committed Use Discount Recommender Catalog Fix
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
Labels: READY-FOR-REVIEW

#1296 FOPTS-835 - Unpublish Google cost policy duplicates of Google Recommender policies
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
  cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Labels: READY-FOR-REVIEW

#1299 FOPTS-957 Google Idle Compute Instances policy timing out
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
Labels: enhancement, READY-FOR-REVIEW

#1312 Update Meta Policy Parameters
  cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
  cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
  cost/aws/unused_rds/unused_rds_meta_parent.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Labels: READY-FOR-REVIEW

#1309 FOPTS-841 Update: Provider from GCP to Google in Turbonomic policies
  README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/delete_unattached_volumes/gcp/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/gcp/README.md
  cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/rightsize_databases_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/gcp/README.md
  cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/README.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/README.md
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
  tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Labels: enhancement, READY-FOR-REVIEW

#1314 Meta Policy Publish Fix
  README_META_POLICIES.md
  cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
  cost/aws/unused_rds/unused_rds_meta_parent.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Labels: READY-FOR-REVIEW

#1313 FOPTS-1079 Update Usage Reduction Policies (Azure Unused Volumes and AWS old snapshots)
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
Labels: enhancement

#1315 FOPTS-1082 - Add MetaPolicy logic to Azure Unused Volumes policy
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
Labels: enhancement

#1298 FOPTS-710 Excessive escalation triggering
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Labels: READY-FOR-REVIEW

#1320 FOPTS-1035 Update Rate Reduction Policies (AWS and Azure RI Recommendations, and Azure Savings Plan)
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/savings_plan/recommendations/CHANGELOG.md
  cost/azure/savings_plan/recommendations/azure_savings_plan_recommendations.pt
Labels: enhancement

#1310 FOPTS-939 - Add policy to refresh Turbonomic authentication token
  cost/turbonomics/credential_refresh/CHANGELOG.md
  cost/turbonomics/credential_refresh/README.md
  cost/turbonomics/credential_refresh/turbonomic_cred_refresh.pt
Labels: enhancement

#1261 FOPTS-618 Budget Alerts - Filter on dimensions Policy Template
  cost/budget_report_alerts/CHANGELOG.md
  cost/budget_report_alerts/README.md
  cost/budget_report_alerts/budget_report_alerts.pt
Labels: enhancement, READY-FOR-REVIEW

#1322 FOPTS-1121 Azure Usage Reduction Policies (Azure Unused Compute Instances and Rightsize Compute Instances)
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Labels: enhancement

#1323 FOPTS-1123 Add the required fields to 3 Google policies
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_vm_recommendations/CHANGELOG.md
  cost/google/idle_vm_recommendations/google_vm_recommendations.pt
Labels: enhancement, changelog, READY-FOR-REVIEW

#1329 Fix: AWS Rightsize Compute Instances Pt Tags output
  cost/aws/rightsize_compute_instances/CHANGELOG.md
  cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
Labels: bug

#1330 FOPTS-1121 Azure Usage Reduction Policies (Azure Old Snapshots, Azure Unused Databases and Azure Rightsize SQL Databases - Fields Updates for several policies)
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/savings_plan/recommendations/CHANGELOG.md
  cost/azure/savings_plan/recommendations/azure_savings_plan_recommendations.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
Labels: enhancement

#1325 FOPTS-1035 Update Rate Reduction Policies (AWS Savings Plan and Google CUD Recommender)
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
Labels: enhancement

#1327 FOPTS-1083 - Add parent meta policy for azure unused volumes
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
Labels: enhancement, READY FOR APPROVAL

#1333 FOPTS-1122 Update AWS Usage Reduction Policies (Rightsize)
  cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
  cost/aws/rightsize_compute_instances/CHANGELOG.md
  cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
  cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
Labels: enhancement

#1335 Oracle Bill Upload Fix
  cost/oracle/oracle_cbi/CHANGELOG.md
  cost/oracle/oracle_cbi/oracle_cbi.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#1336 FOPTS-911 Cost Anomaly Alerts Billing Center as Dimension
  cost/cloud_cost_anomaly_alerts/CHANGELOG.md
  cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Labels: bug, READY-FOR-REVIEW, READY FOR APPROVAL, small fixes
