Repository flexera-public/policy_templates, pull requests merged in 2023-02, with the labels that each got.

#1119 POL-723 Add Oracle Cloud Common Bill Ingestion
  README.md
  cost/oracle/oracle_cbi/CHANGELOG.md
  cost/oracle/oracle_cbi/README.md
  cost/oracle/oracle_cbi/oracle_cbi.pt
Labels: READY-FOR-REVIEW, New Policy

#1170 README.md Fix
  cost/aws/rds_instance_cloudwatch_utilization/README.md
Labels: READY-FOR-REVIEW

#1169 POL-754 - Improve exception handling azure
  compliance/azure/azure_long_stopped_instances/CHANGELOG.md
  compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
  operational/azure/vms_without_managed_disks/CHANGELOG.md
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
Labels: enhancement, READY-FOR-REVIEW

#1174 For for Graph when using "Week"
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW

#1175 HCLIND-47 Fix: ITAM policies are hardcoded for NAM
  compliance/fnms/fnms_licenses_expiring/CHANGELOG.md
  compliance/fnms/fnms_licenses_expiring/expiring_licenses.pt
  compliance/fnms/ignored_recent_inventory_dates/CHANGELOG.md
  compliance/fnms/ignored_recent_inventory_dates/ignored_recent_inventory_dates.pt
  compliance/fnms/missing_active_machines/CHANGELOG.md
  compliance/fnms/missing_active_machines/missing_active_machines.pt
  compliance/fnms/overused_licenses/CHANGELOG.md
  compliance/fnms/overused_licenses/overused_licenses.pt
  compliance/fnms/vms_missing_hostid/CHANGELOG.md
  compliance/fnms/vms_missing_hostid/vms_missing_hostid.pt
Labels: bug, READY-FOR-REVIEW

#1163 HCLIND-7 Remove already expired instances from the report generated by Azure Expiring Reserved Instances PT
  cost/azure/reserved_instances/expiration/CHANGELOG.md
  cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
Labels: bug, READY-FOR-REVIEW

#1161 HCLIND-4 Fix: Hardcoded TLD in cloud_cost_anomaly_alerts.pt to US
  cost/cloud_cost_anomaly_alerts/CHANGELOG.md
  cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Labels: bug, READY-FOR-REVIEW

#1156 HCLIND-3 Add Azure long running instances
  README.md
  operational/azure/azure_long_running_instances/CHANGELOG.md
  operational/azure/azure_long_running_instances/README.md
  operational/azure/azure_long_running_instances/azure_long_running_instances.pt
Labels: READY-FOR-REVIEW, New Policy

#1176 adjusted jq expression to correctly grab status code not based on pos…
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
Labels: bug, READY-FOR-REVIEW

#1164 HCLIND-1 AWS reserved instance option to exclude compute
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/README.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
Labels: bug, READY-FOR-REVIEW

#1171 POL-756 Update Forecasting Policies - fix start/end date clash
  cost/forecasting/moving_average/CHANGELOG.md
  cost/forecasting/moving_average/moving_average_forecast.pt
  cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
  cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
  cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
  operational/aws/total_instance_hours_forecast/CHANGELOG.md
  operational/aws/total_instance_hours_forecast/aws_total_instance_hrs_forecast.pt
  operational/aws/total_instance_vcpus_forecast/CHANGELOG.md
  operational/aws/total_instance_vcpus_forecast/aws_total_instance_vcpus_forecast.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#1140 POL-693 AWS Instance Rightsizing - Merge Idle Instances and Inefficient Instance Utilization
  README.md
  cost/aws/rightsize_compute_instances/CHANGELOG.md
  cost/aws/rightsize_compute_instances/README.md
  cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
Labels: READY-FOR-REVIEW, New Policy

#1173 docs: update link to CloudFormation Template
  README.md
Labels: READY-FOR-REVIEW, repo_maintenance

#1159 Fix dependabot error update npm packages
  package-lock.json
  package.json
Labels: repo_maintenance, READY FOR APPROVAL, small fixes

#1167 POL-693 AWS Instance Rightsizing - Add Meta Policy
  cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt
Labels: READY-FOR-REVIEW, New Policy

#1182 HCLIND-48 Fix SubscriptionName empty
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
Labels: bug, READY-FOR-REVIEW

#1185 POL-765 Vendor Commitment Forecast fix: incident table not populating
  cost/forecasting/commitment_forecast/CHANGELOG.md
  cost/forecasting/commitment_forecast/commitment_forecast.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#1187 HCLIND-54 Please check and update Azure instance types
  data/azure/instance_types.json
Labels: enhancement

#1179 HCLIND-21 Case-insensitive matching of computerName from report with Azure VM name
  compliance/azure/instances_without_fnm_agent/CHANGELOG.md
  compliance/azure/instances_without_fnm_agent/azure_instances_not_running_flexnet_inventory_agent.pt
Labels: small fixes

#1177 POL-752 Add AWS Rightsize Disks (EBS Volumes)
  README.md
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/README.md
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
Labels: READY-FOR-REVIEW, New Policy

#1180 POL-752 AWS Rightsize EBS Volumes - Add Meta Policy
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
Labels: READY-FOR-REVIEW, New Policy

#1192 POL-771 azure idle compute CWF fix
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Labels: bug, READY-FOR-REVIEW
