Repository flexera-public/policy_templates, pull requests merged in 2023-03, with the labels that each got.

#1193 POL-764 limit raise
  cost/aws/elb/clb_unused/CHANGELOG.md
  cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
  cost/aws/gp3_volume_upgrade/CHANGELOG.md
  cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/unused_rds.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightisizing.pt
  cost/azure/unattached_volumes/CHANGELOG.md
  cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
Labels: enhancement, READY-FOR-REVIEW

#1186 HCLIND-38 Add field source to turbonomics
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/turbonomics_allocate_virtual_machines.pt
Labels: enhancement

#1198 Add Azure VM Pricing File
  data/azure/azure_vm_pricing.json
  data/azure/azure_vm_pricing.py
Labels: READY-FOR-REVIEW

#1018 Azure CIS 4.2.3 Ensure that VA setting 'Periodic recurring scans' to 'on' for each SQL server
  README.md
  security/azure/sql_server_va_scans/CHANGELOG.md
  security/azure/sql_server_va_scans/README.md
  security/azure/sql_server_va_scans/sql_server_va_scans.pt
Labels: READY-FOR-REVIEW

#1022 Azure CIS 4.3.2 / 4.3.3 / 4.3.4 Ensure Server Parameter 'log_checkpoints' / 'log_connections' / 'log_disconnections'is set to 'ON' for PostgreSQL Database Server
  README.md
  security/azure/pg_log_settings/CHANGELOG.md
  security/azure/pg_log_settings/README.md
  security/azure/pg_log_settings/pg_log_settings.pt
Labels: READY-FOR-REVIEW

#1023 Azure CIS 4.3.5 Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server
  README.md
  security/azure/pg_conn_throttling/CHANGELOG.md
  security/azure/pg_conn_throttling/README.md
  security/azure/pg_conn_throttling/pg_conn_throttling.pt
Labels: READY-FOR-REVIEW

#1188 HCLIND-50 Add: Turbonomic Rightsize Databases Recommendations PT
  cost/turbonomics/rightsize_databases_recommendations/aws/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/aws/README.md
  cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/azure/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/azure/README.md
  cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/gcp/README.md
  cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
Labels: READY-FOR-REVIEW, New Policy

#1121 Modified functionality to be correct
  operational/aws/tag_cardinality/CHANGELOG.md
  operational/aws/tag_cardinality/README.md
  operational/aws/tag_cardinality/aws_tag_cardinality.pt
  operational/azure/tag_cardinality/CHANGELOG.md
  operational/azure/tag_cardinality/README.md
  operational/azure/tag_cardinality/azure_tag_cardinality.pt
Labels: READY-FOR-REVIEW, small fixes

#1200 HCLIND-38 Fix data representation
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/turbonomics_allocate_virtual_machines.pt
Labels: enhancement, READY-FOR-REVIEW

#1210 HCLIND-62 Fix: Prevent publish Turbonomic Rightsize Databases/Virtual Volumes policies
  cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
Labels: bug, READY-FOR-REVIEW

#1194 POL-726 update azure untagged resources
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/README.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
Labels: enhancement, READY-FOR-REVIEW

#1178 POL-725 Update AWS Untagged Resources
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/README.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
Labels: enhancement, READY-FOR-REVIEW

#1196 HCLIND-54 Please check and update Azure instance types - v2
  data/azure/instance_types.json
Labels: enhancement

#1212 feat: automate generate azure pricing json
  .github/workflows/generate-azure-pricing-json.yaml
  data/azure/requirements.txt
Labels: enhancement

#1208 Pol 747 Budget Alerts
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
  cost/budget_alerts_by_account/CHANGELOG.md
  cost/budget_alerts_by_account/budget_alerts_by_account.pt
Labels: READY-FOR-REVIEW

#1216 POL-770 fixing indentations for chart generation in policy incident emails
  cost/aws/savings_realized/CHANGELOG.md
  cost/aws/savings_realized/aws_savings_realized.pt
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
  cost/forecasting/commitment_forecast/CHANGELOG.md
  cost/forecasting/commitment_forecast/commitment_forecast.pt
  cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
  cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
  cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
  operational/aws/total_instance_hours/CHANGELOG.md
  operational/aws/total_instance_hours/number_of_hours_per_instance_family.pt
  operational/aws/total_instance_hours_forecast/CHANGELOG.md
  operational/aws/total_instance_hours_forecast/aws_total_instance_hrs_forecast.pt
  operational/aws/total_instance_vcpus/CHANGELOG.md
  operational/aws/total_instance_vcpus/number_of_vcpus_per_instance_family.pt
  operational/aws/total_instance_vcpus_forecast/CHANGELOG.md
  operational/aws/total_instance_vcpus_forecast/aws_total_instance_vcpus_forecast.pt
Labels: READY-FOR-REVIEW

#1181 HCLIND-39 Turbonomics Buy Reserved Instances Recommendations.
  cost/turbonomics/buy_reserved_instances_recommendations/aws/CHANGELOG.md
  cost/turbonomics/buy_reserved_instances_recommendations/aws/README.md
  cost/turbonomics/buy_reserved_instances_recommendations/aws/turbonomics_buy_reserved_instances.pt
  cost/turbonomics/buy_reserved_instances_recommendations/azure/CHANGELOG.md
  cost/turbonomics/buy_reserved_instances_recommendations/azure/README.md
  cost/turbonomics/buy_reserved_instances_recommendations/azure/turbonomics_buy_reserved_instances.pt
Labels: READY-FOR-REVIEW, New Policy
