Repository flexera-public/policy_templates, pull requests merged in 2023-01, with the labels that each got.

#1129 POL-731 Update Azure Unused IP Addresses
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Labels: READY-FOR-REVIEW, small fixes

#1120 POL-716 Update Azure Reserved Instance Utilization
  cost/azure/reserved_instances/utilization/CHANGELOG.md
  cost/azure/reserved_instances/utilization/README.md
  cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
Labels: READY-FOR-REVIEW, small fixes

#1128 POL-714 Add Azure China Common Bill Ingestion
  README.md
  cost/azure/azure_china_cbi/CHANGELOG.md
  cost/azure/azure_china_cbi/README.md
  cost/azure/azure_china_cbi/azure_china_cbi.pt
Labels: READY-FOR-REVIEW, New Policy

#1139 POL-741 Update AWS/Azure Savings Realized - period start/end parameters showing Fastly
  cost/aws/savings_realized/CHANGELOG.md
  cost/aws/savings_realized/aws_savings_realized.pt
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#1155 HCLIND-22 added aws instance types
  data/aws/instance_types.json
Labels: enhancement, READY-FOR-REVIEW
