Repository flexera-public/policy_templates, pull requests merged in 2023-04, with the labels that each got.

#1217 FOPTS-198 Performance Boost for Google Idle Persistent Disk Recommender
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1224 FOPTS-212 - Cloud Cost Anomaly Alerts - Filter on dimensions
  cost/cloud_cost_anomaly_alerts/CHANGELOG.md
  cost/cloud_cost_anomaly_alerts/README.md
  cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Labels: enhancement, READY-FOR-REVIEW

#1228 FOPTS-198 Optimize Google Idle Persistent Disk Recommender policy
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
Labels: bug, enhancement, READY-FOR-REVIEW

#1211 FOPTS-215 - Budget Alerts Policy Redux
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/README.md
  cost/budget_alerts/budget_alert.pt
  cost/budget_report_alerts/CHANGELOG.md
  cost/budget_report_alerts/README.md
  cost/budget_report_alerts/budget_report_alerts.pt
Labels: enhancement, READY-FOR-REVIEW

#1231 Azure Rightsize Compute Instances Fix
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Labels: READY-FOR-REVIEW

#1013 Azure CIS 4.1.2 Ensure that 'Data encryption' is set to 'On' on a SQL Database
  README.md
  security/azure/sql_db_encryption/CHANGELOG.md
  security/azure/sql_db_encryption/README.md
  security/azure/sql_db_encryption/sql_db_encryption.pt
Labels: READY-FOR-REVIEW

#1016 Azure CIS 4.2.1 Ensure that Advanced Threat Protection (ATP) on a SQL Server is Set to 'Enabled'
  README.md
  security/azure/sql_server_atp/CHANGELOG.md
  security/azure/sql_server_atp/README.md
  security/azure/sql_server_atp/sql_server_atp.pt
Labels: READY-FOR-REVIEW

#1014 Azure CIS 4.1.3 Ensure that 'Auditing' Retention is 'greater than 90 days'
  README.md
  security/azure/sql_auditing_retention/CHANGELOG.md
  security/azure/sql_auditing_retention/README.md
  security/azure/sql_auditing_retention/sql_auditing_retention.pt
Labels: READY-FOR-REVIEW

#1024 Azure CIS 4.3.6 Ensure server parameter 'log_retention_days' is greater than 3 days for PostgreSQL Database Server
  README.md
  security/azure/pg_log_retention/CHANGELOG.md
  security/azure/pg_log_retention/README.md
  security/azure/pg_log_retention/pg_log_retention.pt
Labels: READY-FOR-REVIEW

#1229 Add Child Policy Code to AWS Object Storage Optimization Policy
  cost/aws/object_storage_optimization/CHANGELOG.md
  cost/aws/object_storage_optimization/README.md
  cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
Labels: READY-FOR-REVIEW

#1238 docs: Add Latest S3 URL to README header
  tools/cloudformation-template/README.md
Labels: documentation

#1239 docs: Add notice PT must be deployed to AWS Master
  compliance/aws/scp_audit/README.md
  cost/aws/reserved_instances/recommendations/README.md
  cost/aws/savings_plan/recommendations/README.md
  cost/aws/savings_plan/utilization/README.md
  operational/aws/tag_cardinality/README.md
Labels: documentation

#1218 FOPTS-228 Added a filter at instances for free SQL Developer & Express versions in Azure VM
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
Labels: enhancement, READY-FOR-REVIEW

#1232 POL-799 Generate Policy ToC and add Optimization
  .github/workflows/generate-readme-policy-table-of-contents.yaml
  .gitignore
  README.md
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  tools/readme_policy_table_of_contents/README.md
  tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Labels: enhancement, documentation

#1240 Fix for AWS Tag Cardinality
  operational/aws/tag_cardinality/CHANGELOG.md
  operational/aws/tag_cardinality/aws_tag_cardinality.pt
Labels: READY-FOR-REVIEW

#1226 POL-787 Add Schedule ITAM Report Policy
  operational/itam/schedule_itam_report/CHANGELOG.md
  operational/itam/schedule_itam_report/README.md
  operational/itam/schedule_itam_report/images/APIToken.png
  operational/itam/schedule_itam_report/images/CMP_NewToken.png
  operational/itam/schedule_itam_report/images/CreateServeceAccount.png
  operational/itam/schedule_itam_report/images/FNMS_cv_Report.png
  operational/itam/schedule_itam_report/images/ReportNumber.png
  operational/itam/schedule_itam_report/images/WebServiceRole.png
  operational/itam/schedule_itam_report/images/email_output.png
  operational/itam/schedule_itam_report/schedule-itam-report.pt
Labels: enhancement, New Policy

#1230 Meta Policy Support for AWS Object Storage Optimization
  cost/aws/object_storage_optimization/aws_object_storage_optimization_meta_parent.pt
Labels: READY-FOR-REVIEW

#1244 task: Docs, Template Metadata, and other repo maintenance
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/generate-azure-pricing-json.yaml
  .github/workflows/generate-readme-policy-table-of-contents.yaml
  Dangerfile
  README.md
  cost/aws/reserved_instances/compute_purchase_recommendation/CHANGELOG.md
  cost/aws/reserved_instances/compute_purchase_recommendation/README.md
  cost/aws/reserved_instances/compute_purchase_recommendation/aws_reserved_instance_recommendations_with_purchase.pt
  tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Labels: documentation

#1219 FOPTS-200 Optimize Google Idle IP Recommender policy
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/README.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1247 AWS Unused Volumes: Updating meta policy to support changes in child policy
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Labels: READY-FOR-REVIEW

#1214 FOPTS-199 Optimize Google Idle VM Recommender policy
  cost/google/idle_vm_recommendations/CHANGELOG.md
  cost/google/idle_vm_recommendations/google_vm_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1248 AWS Unused Volumes: Minor Incident Fix
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Labels: READY-FOR-REVIEW

#1215 FOPTS-201 Optimize Google Cloud SQL Idle Instance Recommender policy
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/README.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1252 FOPTS-698 Deprecated Message
  cost/budget_alerts/CHANGELOG.md
  cost/budget_alerts/budget_alert.pt
Labels: bug
