Repository flexera-public/policy_templates, pull requests merged in 2023-05, with the labels that each got.

#1260 FOPTS-714 Add instance types to EC2 reference file
  data/aws/instance_types.json
Labels: enhancement

#1257 FOPTS-717 Remove limit for the threshold parameter for Budget Alert Policy
  cost/budget_report_alerts/CHANGELOG.md
  cost/budget_report_alerts/README.md
  cost/budget_report_alerts/budget_report_alerts.pt
Labels: enhancement

#1253 POL-809: Enhancements for AWS Savings Plan Utilization
  cost/aws/savings_plan/utilization/CHANGELOG.md
  cost/aws/savings_plan/utilization/README.md
  cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
Labels: enhancement

#1256 Adds Azure MySQL Instance Size Data (Related to POL-793)
  data/azure/mysql_flexible_tier_types.json
Labels: READY-FOR-REVIEW

#1264 FOPTS-761 Publish Turbonomic Policies To Catalog
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/gcp/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/buy_reserved_instances_recommendations/aws/turbonomics_buy_reserved_instances.pt
  cost/turbonomics/buy_reserved_instances_recommendations/azure/turbonomics_buy_reserved_instances.pt
  cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/azure/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
Labels: DO-NOT-MERGE, READY-FOR-REVIEW, READY FOR APPROVAL

#1270 FOPTS-761 Updrade Turbonomic Policies Version Number
  cost/turbonomics/delete_unattached_volumes/aws/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/azure/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/gcp/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/rightsize_databases_recommendations/aws/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/azure/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/scale_virtual_machines_recommendations/aws/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/azure/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/azure/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
Labels: READY-FOR-REVIEW, documentation

#1271 mysql_flexible_tier_types.json Updates/Fixes
  data/azure/mysql_flexible_tier_types.json
Labels: READY-FOR-REVIEW

#1276 quick fix to change results to result
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Labels: READY-FOR-REVIEW, small fixes

#1273 FOPTS-829 FIX Broken Readme Links
  cost/turbonomics/delete_unattached_volumes/aws/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/azure/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/gcp/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/scale_virtual_machines_recommendations/aws/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/azure/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/azure/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
Labels: bug, READY-FOR-REVIEW

#1243 FOPTS-180 Kubecost Cluster Sizing Recommendations Policy
  cost/kubecost/cluster/CHANGELOG.md
  cost/kubecost/cluster/README.md
  cost/kubecost/cluster/kubecost_cluster_rightsizing_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1237 FOPTS-182 Kubecost request sizing recommendations policy template
  cost/kubecost/sizing/CHANGELOG.md
  cost/kubecost/sizing/README.md
  cost/kubecost/sizing/kubecost_resizing_recommendation.pt
Labels: enhancement, READY-FOR-REVIEW

#1282 FOPTS-180 Corrected Kubecost Cluster Sizing Recommendations Policy
  cost/kubecost/cluster/CHANGELOG.md
  cost/kubecost/cluster/kubecost_cluster_rightsizing_recommendations.pt
Labels: small fixes

#1269 FOPTS-805 Fix the method used to match recommendation and resource data at GCP Recommender policies
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_vm_recommendations/CHANGELOG.md
  cost/google/idle_vm_recommendations/google_vm_recommendations.pt
Labels: DO-NOT-MERGE, READY-FOR-REVIEW

#1287 FOPTS-834 Add X2iedn AWS instance types
  data/aws/instance_types.json
Labels: READY-FOR-REVIEW, data

#1288 Azure Unused Volumes - Bug Fixes
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
Labels: READY-FOR-REVIEW

#1233 POL-797 Update Straight-Line forecasting policies with BC Dimension
  cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
  cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
  cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
Labels: enhancement, READY-FOR-REVIEW, small fixes

#1290 Updating Cost Savings Policies For Scraping
  cost/aws/idle_compute_instances/CHANGELOG.md
  cost/aws/idle_compute_instances/idle_compute_instances.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/unused_rds.pt
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_vm_recommendations/CHANGELOG.md
  cost/google/idle_vm_recommendations/google_vm_recommendations.pt
Labels: READY-FOR-REVIEW

#1285 Pol 796 superseded policy detect upgrades
  cost/superseded_instance/CHANGELOG.md
  cost/superseded_instance/superseded_instance.pt
Labels: READY-FOR-REVIEW

#1281 FOPTS-846 Kubecost request rightsizing policy - unable to apply with default parameter values
  cost/kubecost/sizing/CHANGELOG.md
  cost/kubecost/sizing/README.md
  cost/kubecost/sizing/kubecost_resizing_recommendation.pt
Labels: READY-FOR-REVIEW

#1293 FOPTS-776 Google CUD policy is double counting projected savings
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/README.md
  cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
Labels: bug, DO-NOT-MERGE, READY-FOR-REVIEW

#1300 AWS Rightsize Cost Gathering Date Fix
  cost/aws/rightsize_compute_instances/CHANGELOG.md
  cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
Labels: READY-FOR-REVIEW
