Repository flexera-public/policy_templates, pull requests merged in 2023-07, with the labels that each got.

#1342 FOPTS-1064 Billing Center Cost Anomaly Detection Policy - broken link in readme
  cost/billing_center_cost_anomaly/README.md
Labels: documentation

#1343 FOPTS-681 Homologate the requests to GCP recommender API before waiting to prevent API limit quota errors
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_vm_recommendations/CHANGELOG.md
  cost/google/idle_vm_recommendations/google_vm_recommendations.pt
  cost/google/recommender/CHANGELOG.md
  cost/google/recommender/recommender.pt
  cost/google/rightsize_vm_recommendations/CHANGELOG.md
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW, javascript

#1338 FOPTS-765 Low-usage Account Policy
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/low_account_usage.pt
Labels: enhancement

#1352 fix: Meta Parent Parser GitHub README URLs
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: bug

#1340 FOPTS-1072 - Turbonomic policies with token refreshed follow schedule
  cost/turbonomics/credential_refresh/CHANGELOG.md
  cost/turbonomics/credential_refresh/README.md
  cost/turbonomics/credential_refresh/turbonomic_cred_refresh.pt
Labels: enhancement

#1341 FOPTS-807 AWS Unused RDS Policy Github pre-requisites update request
  cost/aws/unused_rds/README.md
  tools/cloudformation-template/FlexeraAutomationPolicies.template
Labels: READY-FOR-REVIEW, documentation

#1354 POL-878: Azure Rightsize Compute Instances Memory Support and General Improvements
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/README.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Labels: READY-FOR-REVIEW

#1348 POL-868 Remove Deprecated Azure RI Recommendations Policy
  cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
  cost/azure/reserved_instances/mca_recommendations/README.md
  cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/README.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
Labels: READY-FOR-REVIEW

#1355 FOPTS-682 Google recommender policies update readme
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/README.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/README.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/README.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_vm_recommendations/CHANGELOG.md
  cost/google/idle_vm_recommendations/README.md
  cost/google/idle_vm_recommendations/google_vm_recommendations.pt
Labels: changelog, READY-FOR-REVIEW, documentation

#1358 POL-880 AWS Long-Stopped Instances - Create Meta Parent - Update Child Policy
  compliance/aws/long_stopped_instances/CHANGELOG.md
  compliance/aws/long_stopped_instances/README.md
  compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt
  compliance/aws/long_stopped_instances/aws_long_stopped_instances_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: enhancement, READY-FOR-REVIEW

#1363 POL-886 Azure Unused IP Policy Fix
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Labels: READY-FOR-REVIEW

#1367 Meta Generator Fixes
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1371 FOPTS-1441 Google Cloud SQL Idle Instance Recommender: fix the method to match the recommendations with the SQL instances at the
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
Labels: bug, READY-FOR-REVIEW, small fixes, javascript

#1376 POL-887 Meta Policy for AWS Lambda Function high error rate
  operational/aws/lambda_functions_with_high_error_rate/CHANGELOG.md
  operational/aws/lambda_functions_with_high_error_rate/README.md
  operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate.pt
  operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: enhancement, READY-FOR-REVIEW

#1362 FOPTS-1324 Turbonomic Unattached Volumes (Azure)
  cost/turbonomics/delete_unattached_volumes/aws/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/azure/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
Labels: enhancement, DO-NOT-MERGE

#1373 POL-744 Meta Policy for AWS Untagged Resources (Sub-Task 1 POL-890)
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/README.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
Labels: enhancement, READY-FOR-REVIEW

#1378 POL-888 Meta Policy for AWS Publicly Accessible RDS Instances
  security/aws/rds_publicly_accessible/CHANGELOG.md
  security/aws/rds_publicly_accessible/README.md
  security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
  security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: enhancement, READY-FOR-REVIEW

#1381 Azure Meta Policies: Dimension Filtering
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit_meta_parent.pt
  cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
  cost/azure/hybrid_use_benefit_sql/ahub_sql_meta_parent.pt
  cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt
  cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
  cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management_meta_parent.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
  cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
  operational/azure/azure_certificates/azure_certificates_meta_parent.pt
  operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt
  operational/azure/tag_cardinality/azure_tag_cardinality_meta_parent.pt
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks_meta_parent.pt
  tools/meta_parent_policy_compiler/azure_meta_parent.pt.template
Labels: READY-FOR-REVIEW
