Repository flexera-public/policy_templates, pull requests merged in 2023-09, with the labels that each got.

#1441 Azure Unused Volumes Revamp
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/README.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
Labels: READY-FOR-REVIEW

#1444 FOPTS-1577 AWS Unused RDS Instances: update policy name in the README
  cost/aws/unused_rds/README.md
Labels: READY-FOR-REVIEW, small fixes

#1443 FOPTS-1542 Azure Idle Compute Instances - incident and recommendations showing error for tags
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Labels: enhancement, READY-FOR-REVIEW

#1446 POL-847 Policy Automated Updates On Releases 2
  tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
Labels: READY-FOR-REVIEW, small fixes

#1436 FOPTS-1332 Turbonomic Rightsize VMs (GCP)
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
Labels: enhancement, READY-FOR-REVIEW

#1452 POL 847 Policy Automated Updates on Releases 2
  .github/workflows/generate-policy-release-notifications.yaml
  tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
Labels: enhancement, READY-FOR-REVIEW, ruby

#1405 POL-841 Azure Old Snapshots Revamp
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/README.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt
Labels: READY-FOR-REVIEW

#1454 FOPTS-1336 Turbonomic Buy RI (AWS)
  cost/turbonomics/buy_reserved_instances_recommendations/aws/CHANGELOG.md
  cost/turbonomics/buy_reserved_instances_recommendations/aws/turbonomics_buy_reserved_instances.pt
Labels: enhancement, READY-FOR-REVIEW

#1461 POL-847 Policy Automated Updates on Releases 2
  .github/workflows/generate-policy-release-notifications.yaml
Labels: enhancement, READY-FOR-REVIEW, ruby

#1464 FOPTS-1816 Handle updating applied and aggregated policies
  cost/turbonomics/credential_refresh/CHANGELOG.md
  cost/turbonomics/credential_refresh/turbonomic_cred_refresh.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#1455 POL-840 Azure Rightsize SQL Databases Revamp
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/README.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1370 POL-749 Azure Hybrid Use Benefit for Windows/Linux Server Revamp
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/README.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit_meta_parent.pt
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/README.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
  cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
Labels: READY-FOR-REVIEW

#1463 fix: Refactor Azure Unused Volume and Unused IP Actions
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
Labels: bug

#1474 Azure AHUB Linux README Link Fix
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
  cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
Labels: READY-FOR-REVIEW

#1460 FOPTS-1815 Low Account Usage Policy optimization
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/low_account_usage.pt
Labels: enhancement, READY-FOR-REVIEW

#1478 POL-847 Policy Automated Updates on Releases 2
  .github/workflows/generate-policy-release-notifications.yaml
Labels: READY-FOR-REVIEW, small fixes, automation

#1453 POL-911 AWS Long Running Instances Revamp
  operational/aws/long_running_instances/CHANGELOG.md
  operational/aws/long_running_instances/README.md
  operational/aws/long_running_instances/long_running_instances.pt
  operational/aws/long_running_instances/long_running_instances_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1479 POL-910 AWS Rightsize EBS Volumes - Remove GP3 Recommendations and Empty Recommendations
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
Labels: READY-FOR-REVIEW, small fixes

#1466 POL-919 Azure Long Running Instances Revamp
  operational/azure/azure_long_running_instances/CHANGELOG.md
  operational/azure/azure_long_running_instances/README.md
  operational/azure/azure_long_running_instances/azure_long_running_instances.pt
  operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1476 POL-920 Azure Unused Volumes Read/Write Metrics Support
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/README.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
Labels: READY-FOR-REVIEW

#1486 POL-924 Oracle Cloud CBI Broken Upload Fix
  cost/oracle/oracle_cbi/CHANGELOG.md
  cost/oracle/oracle_cbi/oracle_cbi.pt
Labels: READY-FOR-REVIEW

#1477 POL-921 Add Region Filtering to Azure Rightsizing Compute
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/README.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
Labels: READY-FOR-REVIEW

#1494 FOPTS-2108 Rework Low Account Usage Policy Optimization
  cost/low_account_usage/CHANGELOG.md
  cost/low_account_usage/low_account_usage.pt
Labels: enhancement, DO-NOT-MERGE, READY-FOR-REVIEW

#1481 POL-922 AWS Superseded EC2 Instances
  cost/aws/superseded_instances/CHANGELOG.md
  cost/aws/superseded_instances/README.md
  cost/aws/superseded_instances/aws_superseded_instances.pt
  cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1483 POL-923 Azure Superseded Compute Instances
  cost/azure/superseded_instances/CHANGELOG.md
  cost/azure/superseded_instances/README.md
  cost/azure/superseded_instances/azure_superseded_instances.pt
  cost/azure/superseded_instances/azure_superseded_instances_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1498 FOPTS-1858 Azure Savings Realized fails for customers with no RI coverage
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
Labels: READY-FOR-REVIEW, READY FOR APPROVAL

#1497 POL-913 Google Idle IP Address Recommender Revamp / Google Meta Policy Automation
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/README.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations_meta_parent.pt
  tools/meta_parent_policy_compiler/google_meta_parent.pt.template
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW
