Repository flexera-public/policy_templates, pull requests merged in 2023-12, with the labels that each got.

#1657 POL-978 Update Default Frequency of Children to "Weekly"
  compliance/aws/disallowed_regions/aws_disallowed_regions_meta_parent.pt
  compliance/aws/instances_without_fnm_agent/aws_instances_not_running_flexnet_inventory_agent_meta_parent.pt
  compliance/aws/long_stopped_instances/aws_long_stopped_instances_meta_parent.pt
  compliance/azure/ahub_manual/azure_ahub_utilization_with_manual_entry_meta_parent.pt
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions_meta_parent.pt
  compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure_meta_parent.pt
  compliance/azure/instances_without_fnm_agent/azure_instances_not_running_flexnet_inventory_agent_meta_parent.pt
  cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume_meta_parent.pt
  cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
  cost/aws/object_storage_optimization/aws_object_storage_optimization_meta_parent.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
  cost/aws/rds_instance_license_info/rds_instance_license_info_meta_parent.pt
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  cost/aws/s3_storage_policy/aws_s3_bucket_policy_check_meta_parent.pt
  cost/aws/schedule_instance/aws_schedule_instance_meta_parent.pt
  cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
  cost/aws/unused_rds/unused_rds_meta_parent.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit_meta_parent.pt
  cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
  cost/azure/hybrid_use_benefit_sql/ahub_sql_meta_parent.pt
  cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt
  cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
  cost/azure/schedule_instance/azure_schedule_instance_meta_parent.pt
  cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management_meta_parent.pt
  cost/azure/superseded_instances/azure_superseded_instances_meta_parent.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
  cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations_meta_parent.pt
  cost/google/cud_recommendations/google_committed_use_discount_recommendations_meta_parent.pt
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations_meta_parent.pt
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations_meta_parent.pt
  cost/google/old_snapshots/google_delete_old_snapshots_meta_parent.pt
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations_meta_parent.pt
  operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate_meta_parent.pt
  operational/aws/long_running_instances/long_running_instances_meta_parent.pt
  operational/aws/tag_cardinality/aws_tag_cardinality_meta_parent.pt
  operational/azure/azure_certificates/azure_certificates_meta_parent.pt
  operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt
  operational/azure/tag_cardinality/azure_tag_cardinality_meta_parent.pt
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks_meta_parent.pt
  security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes_meta_parent.pt
  security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances_meta_parent.pt
  tools/meta_parent_policy_compiler/aws_meta_parent.pt.template
  tools/meta_parent_policy_compiler/azure_meta_parent.pt.template
  tools/meta_parent_policy_compiler/google_meta_parent.pt.template
Labels: READY-FOR-REVIEW

#1656 POL-977 AWS Rightsize RDS: Change Parameter Default Value
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1625 POL-745 SaaS Manager - Deactivated Users for Integrated Applications Revamp
  saas/fsm/deactivated_users_for_integrated_apps/CHANGELOG.md
  saas/fsm/deactivated_users_for_integrated_apps/README.md
  saas/fsm/deactivated_users_for_integrated_apps/deactivated_users_for_integrated_apps.pt
  saas/fsm/inactive_users_for_integrated_apps/CHANGELOG.md
  saas/fsm/inactive_users_for_integrated_apps/README.md
  saas/fsm/inactive_users_for_integrated_apps/inactive_users_for_integrated_apps.pt
Labels: READY-FOR-REVIEW

#1655 POL-889 AWS Open S3 Buckets Revamp / Meta
  security/storage/aws/public_buckets/CHANGELOG.md
  security/storage/aws/public_buckets/README.md
  security/storage/aws/public_buckets/aws_public_buckets.pt
  security/storage/aws/public_buckets/aws_public_buckets_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1583 POL-853 - Azure Databricks Rightsize Compute Instances
  cost/azure/databricks/rightsize_compute/CHANGELOG.md
  cost/azure/databricks/rightsize_compute/README.md
  cost/azure/databricks/rightsize_compute/azure_databricks_rightsize_compute.pt
  cost/azure/databricks/rightsize_compute/azure_databricks_rightsize_compute_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW, New Policy

#1667 POL-836 AWS Unused Classic Load Balancers Revamp
  cost/aws/elb/clb_unused/README.md
  cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
  cost/aws/unused_clbs/CHANGELOG.md
  cost/aws/unused_clbs/README.md
  cost/aws/unused_clbs/aws_unused_clbs.pt
  cost/aws/unused_clbs/aws_unused_clbs_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1670 POL-969 - Update Azure instance_type.json file for Eas series
  data/azure/instance_types.json
Labels: READY-FOR-REVIEW, azure

#1681 POL-757 Azure Rightsize Compute Fixes/Improvements
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/README.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
Labels: READY-FOR-REVIEW

#1688 POL-984 Fix AWS README Permissions
  compliance/aws/disallowed_regions/README.md
  cost/aws/savings_plan/expiration/README.md
Labels: READY-FOR-REVIEW

#1682 POL-466 Remove ce:* Permissions from AWS READMEs
  cost/aws/reserved_instances/compute_purchase_recommendation/README.md
  cost/aws/reserved_instances/coverage/README.md
  cost/aws/savings_plan/utilization/README.md
Labels: READY-FOR-REVIEW

#1666 POL-971 Azure Reserved Instances Utilization - update to use Modern Azure APIs
  cost/azure/reserved_instances/utilization/CHANGELOG.md
  cost/azure/reserved_instances/utilization/README.md
  cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
Labels: READY-FOR-REVIEW

#1691 POL-1006 Google Idle Persistent Disk Recommender Permissions Update
  cost/google/idle_persistent_disk_recommendations/README.md
Labels: READY-FOR-REVIEW

#1690 POL-817 AWS instance_types.json Casing Fix
  data/aws/instance_types.json
Labels: READY-FOR-REVIEW

#1683 POL-566 Policy Update Notification Revamp
  compliance/policy_update_notification/CHANGELOG.md
  compliance/policy_update_notification/README.md
  compliance/policy_update_notification/changelog.md
  compliance/policy_update_notification/policy_update_notification.pt
Labels: READY-FOR-REVIEW

#1693 feat: improved logging error handling schedule instance PTs
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/README.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/google/schedule_instance/CHANGELOG.md
  cost/google/schedule_instance/README.md
  cost/google/schedule_instance/google_schedule_instance.pt
Labels: READY-FOR-REVIEW

#1701 POL-1012 AWS Rightsize RDS Dash Fix
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1697 POL-1008 Google Idle Persistent Disk Recommender: Add 'Days Unattached' Parameter
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/README.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations_meta_parent.pt
Labels: READY-FOR-REVIEW

#1706 POL-982 Hybrid Use Benefit Policy - currency separator symbol shown as undefined
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
Labels: READY-FOR-REVIEW, READY FOR APPROVAL

#1704 POL-1010 Scheduled Report Policy Revamp
  cost/scheduled_reports/CHANGELOG.md
  cost/scheduled_reports/README.md
  cost/scheduled_reports/scheduled_report.pt
Labels: READY-FOR-REVIEW
