Repository flexera-public/policy_templates, pull requests merged in 2023-08, with the labels that each got.

#1383 FOPTS-1325 Turbonomic Unattached Volumes (GCP)
  cost/turbonomics/delete_unattached_volumes/gcp/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
Labels: enhancement

#1385 POL-896 Update "Bill Processing Errors" Policy And Add To Catalog
  operational/bill_processing_errors_notification/CHANGELOG.md
  operational/bill_processing_errors_notification/README.md
  operational/bill_processing_errors_notification/bill_processing_errors_notification.pt
Labels: READY-FOR-REVIEW

#1384 POL-894 Currency Conversion API Update & Tweaks
  cost/currency_conversion/CHANGELOG.md
  cost/currency_conversion/README.md
  cost/currency_conversion/currency_conversion.pt
Labels: READY-FOR-REVIEW

#1388 POL-861 Google Cost Policy README Permissions Updates
  cost/google/cloud_sql_idle_instance_recommendations/README.md
  cost/google/cud_recommendations/README.md
  cost/google/idle_ip_address_recommendations/README.md
  cost/google/idle_persistent_disk_recommendations/README.md
  cost/google/idle_vm_recommendations/README.md
Labels: READY-FOR-REVIEW

#1386 FOPTS-172 Add: Azure MCA RI Utilization PT
  cost/azure/reserved_instances/utilization_mca/CHANGELOG.md
  cost/azure/reserved_instances/utilization_mca/README.md
  cost/azure/reserved_instances/utilization_mca/azure_reserved_instance_utilization_mca.pt
Labels: READY-FOR-REVIEW, New Policy

#1308 AWS Rightsize EC2 Instances Revamp
  cost/aws/rightsize_compute_instances/CHANGELOG.md
  cost/aws/rightsize_compute_instances/README.md
  cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
  cost/aws/rightsize_ec2_instances/CHANGELOG.md
  cost/aws/rightsize_ec2_instances/README.md
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
  tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.6.0.template
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: DO-NOT-MERGE

#1364 AWS Old Snapshots Revamp
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/README.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
Labels: DO-NOT-MERGE

#1365 AWS Unused IP Addresses Revamp
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/README.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
Labels: DO-NOT-MERGE

#1366 AWS Unused Volumes Revamp
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/README.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Labels: DO-NOT-MERGE

#1372 AWS Unused RDS Instances Revamp
  cost/aws/unused_rds/CHANGELOG.md
  cost/aws/unused_rds/README.md
  cost/aws/unused_rds/unused_rds.pt
  cost/aws/unused_rds/unused_rds_meta_parent.pt
Labels: DO-NOT-MERGE

#1390 POL-861 Azure Readme Permissions Updates
  cost/azure/idle_compute_instances/README.md
  cost/azure/old_snapshots/README.md
  cost/azure/savings_plan/recommendations/README.md
  cost/azure/unused_ip_addresses/README.md
  cost/azure/unused_sql_databases/README.md
  cost/azure/unused_volumes/README.md
Labels: READY-FOR-REVIEW

#1382 FOPTS-1333 Turbonomic Rightsize DBs (AWS) - Bring recommendation supporting information
  cost/turbonomics/rightsize_databases_recommendations/aws/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1392 FOPTS-1327 Turbonomic Rightsize Volumes (AWS)
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
Labels: enhancement, READY FOR APPROVAL, small fixes

#1205 POL-779 Add RBD Generation Policies
  automation/aws/aws_rbd_from_tag/CHANGELOG.md
  automation/aws/aws_rbd_from_tag/README.md
  automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
  automation/azure/azure_rbd_from_rg_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_rg_tag/README.md
  automation/azure/azure_rbd_from_rg_tag/azure_rbd_from_rg_tag.pt
  automation/azure/azure_rbd_from_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_tag/README.md
  automation/azure/azure_rbd_from_tag/azure_rbd_from_tag.pt
  automation/google/google_rbd_from_label/CHANGELOG.md
  automation/google/google_rbd_from_label/README.md
  automation/google/google_rbd_from_label/google_rbd_from_label.pt
Labels: READY-FOR-REVIEW

#1396 POL-899 Use New API for AWS RBD Policy
  automation/aws/aws_rbd_from_tag/CHANGELOG.md
  automation/aws/aws_rbd_from_tag/README.md
  automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
Labels: READY-FOR-REVIEW

#1400 FOPTS-1329 Turbonomic Rightsize Volumes (GCP)
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1404 POL-842 Azure Unused IPs Revamp
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/README.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
Labels: READY-FOR-REVIEW

#1397 FOPTS-1328 Turbonomic Rightsize Volumes (Azure)
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW

#1408 POL-903 Fixed Cost Data Issue with New Azure APIs
  cost/azure/idle_compute_instances/CHANGELOG.md
  cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
  cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
  cost/azure/unused_sql_databases/CHANGELOG.md
  cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
  cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
Labels: READY-FOR-REVIEW

#1410 POL-904 Fixes for AWS Unused IP Policy
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
Labels: READY-FOR-REVIEW

#1413 fix: fpt install from source
  .github/workflows/test-policies.yaml
Labels: bug, small fixes, automation

#1402 FOPTS-1578 Allow Retrieving Recommendations "per cluster"
  cost/kubecost/sizing/CHANGELOG.md
  cost/kubecost/sizing/README.md
  cost/kubecost/sizing/kubecost_resizing_recommendation.pt
Labels: enhancement, READY-FOR-REVIEW, READY FOR APPROVAL, javascript

#1414 POL-906: fix `ds_describe_snapshots` tag collect
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
Labels: small fixes

#1415 POL-905 Update policy_sync.pt to use Github instead of S3
  .github/workflows/upload-files.yaml
  data/active_policy_list/active_policy_list.json
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW, repo_maintenance, automation

#1416 POL-905 Fix the name of the active policy list file
  .github/workflows/upload-files.yaml
Labels: bug, repo_maintenance, automation

#1417 POL-905 Fix permissions of the GitHub workflow
  .github/workflows/upload-files.yaml
Labels: repo_maintenance, automation

#1406 FOPTS-1584 Turbonomic Right size DBs ( Azure ) Need to add request to check Price Model
  cost/turbonomics/rightsize_databases_recommendations/azure/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW, READY FOR APPROVAL

#1420 Fix AWS Old Snapshots Version #
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
Labels: READY-FOR-REVIEW

#1412 feat: Add Dev Container
  .devcontainer/devcontainer.json
  .gitignore
Labels: enhancement, READY-FOR-REVIEW, READY FOR APPROVAL

#1431 FOPTS-1632 Fix the broken link for the README for Schedule ITAM Report policy
  operational/itam/schedule_itam_report/CHANGELOG.md
  operational/itam/schedule_itam_report/schedule-itam-report.pt
Labels: READY-FOR-REVIEW, small fixes, documentation

#1398 FOPTS-1335 Turbonomic Rightsize DBs (GCP) - Bring recommendation supporting information
  cost/turbonomics/rightsize_databases_recommendations/gcp/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
Labels: enhancement, READY-FOR-REVIEW, READY FOR APPROVAL

#1433 FOPTS-1330 Turbonomic Rightsize VMs (AWS)
  cost/turbonomics/scale_virtual_machines_recommendations/aws/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
Labels: enhancement, READY-FOR-REVIEW

#1440 POL-847 Policy Automated Updates On Releases (Part 1)
  .github/workflows/generate-policy-release-notifications.yaml
  tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
Labels: READY-FOR-REVIEW, ruby
