Repository flexera-public/policy_templates, pull requests merged in 2024-06, with the labels that each got.

#2243 POL-1075 AWS Reserved Instances Utilization Revamp
  cost/aws/reserved_instances/utilization/CHANGELOG.md
  cost/aws/reserved_instances/utilization/README.md
  cost/aws/reserved_instances/utilization/utilization_ris.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2288 POL-1249 fix: AWS/Azure Usage Reports - fix chart not rendering in email for Memory Used
  operational/aws/total_instance_usage_forecast/CHANGELOG.md
  operational/aws/total_instance_usage_forecast/aws_total_instance_usage_forecast.pt
  operational/aws/total_instance_usage_report/CHANGELOG.md
  operational/aws/total_instance_usage_report/aws_total_instance_usage_report.pt
  operational/azure/total_instance_usage_report/CHANGELOG.md
  operational/azure/total_instance_usage_report/azure_total_instance_usage_report.pt
Labels: bug, DO-NOT-MERGE, small fixes

#2279 POL-1234 New Policy: AWS Idle NAT Gateways
  cost/aws/idle_nat_gateways/CHANGELOG.md
  cost/aws/idle_nat_gateways/README.md
  cost/aws/idle_nat_gateways/aws_idle_nat_gateways.pt
  cost/aws/idle_nat_gateways/aws_idle_nat_gateways_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2221 POL-1230 Policy Template Synchronization Revamp
  .spellignore
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/catalog_management/hidden_policies/CHANGELOG.md
  tools/catalog_management/hidden_policies/README.md
  tools/catalog_management/hidden_policies/hidden_policies.pt
  tools/catalog_management/policy_sync/CHANGELOG.md
  tools/catalog_management/policy_sync/README.md
  tools/catalog_management/policy_sync/policy_sync.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
  tools/policy_sync/README.md
  tools/policy_sync/policy_sync.png
  tools/policy_sync/policy_sync.pt
Labels: READY-FOR-REVIEW

#2295 Fixing issue with disk name calculation
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
Labels: bug, DO-NOT-MERGE

#2292 POL-1251 Unpublish Unused Deprecated Policies
  operational/aws/total_instance_memory/CHANGELOG.md
  operational/aws/total_instance_memory/aws_usage_instance_memory_used.pt
  operational/azure/azure_migrate/CHANGELOG.md
  operational/azure/azure_migrate/risc-azure-migrate.pt
  operational/flexera/risc/compute_instance_migration/CHANGELOG.md
  operational/flexera/risc/compute_instance_migration/risc-compute-instance-migration-recos.pt
  operational/flexera/risc/network_flow/CHANGELOG.md
  operational/flexera/risc/network_flow/risc-netflow.pt
  saas/fsm/user_status_change/CHANGELOG.md
  saas/fsm/user_status_change/fsm-user_status_change.pt
Labels: READY-FOR-REVIEW

#2307 FOPTS-4199 Fixing calculation of the Premium SSD price
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
Labels: bug, DO-NOT-MERGE, READY-FOR-REVIEW

#2294 FOPTS-3682 Refactor Turbonomic Authentication: cookies to token-base
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/aws/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/azure/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/allocate_virtual_machines_recommendations/google/CHANGELOG.md
  cost/turbonomics/allocate_virtual_machines_recommendations/google/README.md
  cost/turbonomics/allocate_virtual_machines_recommendations/google/turbonomics_allocate_virtual_machines.pt
  cost/turbonomics/buy_reserved_instances_recommendations/aws/CHANGELOG.md
  cost/turbonomics/buy_reserved_instances_recommendations/aws/README.md
  cost/turbonomics/buy_reserved_instances_recommendations/aws/turbonomics_buy_reserved_instances.pt
  cost/turbonomics/buy_reserved_instances_recommendations/azure/CHANGELOG.md
  cost/turbonomics/buy_reserved_instances_recommendations/azure/README.md
  cost/turbonomics/buy_reserved_instances_recommendations/azure/turbonomics_buy_reserved_instances.pt
  cost/turbonomics/credential_refresh/CHANGELOG.md
  cost/turbonomics/credential_refresh/README.md
  cost/turbonomics/credential_refresh/turbonomic_cred_refresh.pt
  cost/turbonomics/delete_unattached_volumes/aws/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/aws/README.md
  cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/azure/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/azure/README.md
  cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/delete_unattached_volumes/google/CHANGELOG.md
  cost/turbonomics/delete_unattached_volumes/google/README.md
  cost/turbonomics/delete_unattached_volumes/google/turbonomics_delete_virtual_volumes.pt
  cost/turbonomics/rightsize_databases_recommendations/aws/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/aws/README.md
  cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/azure/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/azure/README.md
  cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_databases_recommendations/google/CHANGELOG.md
  cost/turbonomics/rightsize_databases_recommendations/google/README.md
  cost/turbonomics/rightsize_databases_recommendations/google/turbonomics_rightsize_databases_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/README.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/README.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/rightsize_virtual_volumes_recommendations/google/CHANGELOG.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/google/README.md
  cost/turbonomics/rightsize_virtual_volumes_recommendations/google/turbonomics_rightsize_virtual_volumes_recommendations.pt
  cost/turbonomics/scale_virtual_machines_recommendations/aws/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/aws/README.md
  cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/azure/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/azure/README.md
  cost/turbonomics/scale_virtual_machines_recommendations/azure/turbonomics_scale_virtual_machines.pt
  cost/turbonomics/scale_virtual_machines_recommendations/google/CHANGELOG.md
  cost/turbonomics/scale_virtual_machines_recommendations/google/README.md
  cost/turbonomics/scale_virtual_machines_recommendations/google/turbonomics_scale_virtual_machines.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/generate_policy_master_permissions.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: DO-NOT-MERGE, READY-FOR-REVIEW, javascript, ruby

#2314 POL-1081 Azure China Common Bill Ingestion Revamp
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  .spellignore
  cost/azure/azure_china_cbi/CHANGELOG.md
  cost/azure/azure_china_cbi/README.md
  cost/azure/azure_china_cbi/azure_china_cbi.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/generate_policy_master_permissions.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2320 POL-1263 AWS Cost Report - EC2 Instance Cost Per Hour
  cost/aws/instance_cost_per_hour/CHANGELOG.md
  cost/aws/instance_cost_per_hour/README.md
  cost/aws/instance_cost_per_hour/aws_instance_cost_per_hour.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2306 POL-1239 New Policy: Azure Rightsize SQL Database Storage
  .github/workflows/generate-azure-db-storage-pricing-json.yaml
  .spellignore
  cost/azure/rightsize_sql_storage/CHANGELOG.md
  cost/azure/rightsize_sql_storage/README.md
  cost/azure/rightsize_sql_storage/azure_rightsize_sql_storage.pt
  cost/azure/rightsize_sql_storage/azure_rightsize_sql_storage_meta_parent.pt
  data/azure/azure_db_storage_pricing.json
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/cloud_data/README.md
  tools/cloud_data/azure/azure_db_storage_pricing.py
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2308 POL-1078 AWS Expiring Savings Plans Revamp
  cost/aws/savings_plan/expiration/CHANGELOG.md
  cost/aws/savings_plan/expiration/README.md
  cost/aws/savings_plan/expiration/aws_savings_plan_expiration.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2312 POL-1080 AWS Savings Realized From Rate Reduction Purchases Revamp
  .dangerfile/policy_tests.rb
  cost/aws/savings_realized/CHANGELOG.md
  cost/aws/savings_realized/README.md
  cost/aws/savings_realized/aws_savings_realized.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2317 POL-1255 Cloud Bill Processing Error Notification Revamp
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/cco/bill_processing_errors_notification/CHANGELOG.md
  operational/flexera/cco/bill_processing_errors_notification/README.md
  operational/flexera/cco/bill_processing_errors_notification/bill_processing_errors_notification.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2336 POL-1259 Cloud Spend Moving Average Report Revamp
  cost/flexera/cco/forecasting/moving_average/README.md
  cost/flexera/cco/forecasting/moving_average/moving_average_forecast.pt
  cost/flexera/cco/moving_average/CHANGELOG.md
  cost/flexera/cco/moving_average/README.md
  cost/flexera/cco/moving_average/moving_average.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2351 POL-1273 Meta Parent Global README Fix
  README.md
  tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Labels: READY-FOR-REVIEW

#2345 POL-1260 Cloud Spend Forecast - Straight-Line Revamp
  cost/flexera/cco/forecasting/straight_line_forecast/CHANGELOG.md
  cost/flexera/cco/forecasting/straight_line_forecast/README.md
  cost/flexera/cco/forecasting/straight_line_forecast/linear_regression/README.md
  cost/flexera/cco/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
  cost/flexera/cco/forecasting/straight_line_forecast/straight_line_forecast.pt
  cost/flexera/cco/forecasting/straight_line_forecast_simple/CHANGELOG.md
  cost/flexera/cco/forecasting/straight_line_forecast_simple/README.md
  cost/flexera/cco/forecasting/straight_line_forecast_simple/straight_line_forecast_simple.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2354 POL-1270 GitHub Policy Revamps
  compliance/github/available_seats/CHANGELOG.md
  compliance/github/available_seats/README.md
  compliance/github/available_seats/available_seats.pt
  compliance/github/outside_collaborators/CHANGELOG.md
  compliance/github/outside_collaborators/README.md
  compliance/github/outside_collaborators/outside_collaborators.pt
  compliance/github/repository_admin_team/CHANGELOG.md
  compliance/github/repository_admin_team/README.md
  compliance/github/repository_admin_team/repository_admin_team.pt
  compliance/github/repository_branch_protection/CHANGELOG.md
  compliance/github/repository_branch_protection/README.md
  compliance/github/repository_branch_protection/repository_branch_protection.pt
  compliance/github/repository_naming/CHANGELOG.md
  compliance/github/repository_naming/README.md
  compliance/github/repository_naming/repository_naming.pt
  compliance/github/repository_size/CHANGELOG.md
  compliance/github/repository_size/README.md
  compliance/github/repository_size/repository_size.pt
  compliance/github/toplevel_teams/CHANGELOG.md
  compliance/github/toplevel_teams/README.md
  compliance/github/toplevel_teams/toplevel_teams.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/generate_policy_master_permissions.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2261 FOPTS-3684 Azure Synapse SQL Pools
  README.md
  cost/azure/rightsize_synapse_sql_pools/CHANGELOG.md
  cost/azure/rightsize_synapse_sql_pools/README.md
  cost/azure/rightsize_synapse_sql_pools/azure_rightsize_synapse_sql_pools.pt
  cost/azure/rightsize_synapse_sql_pools/azure_rightsize_synapse_sql_pools_meta_parent.pt
  data/azure/azure_synapse_tier_types.json
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: enhancement, READY-FOR-REVIEW
