Repository flexera-public/policy_templates, pull requests merged in 2024-11, with the labels that each got.

#2802 POL-1397 Flexera One API Event Report
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/iam/api_event_report/CHANGELOG.md
  operational/flexera/iam/api_event_report/README.md
  operational/flexera/iam/api_event_report/api_event_report.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2799 FOPTS-4819 Added `hide_skip_approvals` to AWS Right Size policies
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes.pt
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes_meta_parent.pt
  cost/aws/rightsize_ec2_instances/CHANGELOG.md
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
  cost/aws/rightsize_elasticache/CHANGELOG.md
  cost/aws/rightsize_elasticache/aws_rightsize_elasticache.pt
  cost/aws/rightsize_elasticache/aws_rightsize_elasticache_meta_parent.pt
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  cost/aws/rightsize_redshift/CHANGELOG.md
  cost/aws/rightsize_redshift/aws_rightsize_redshift.pt
  cost/aws/rightsize_redshift/aws_rightsize_redshift_meta_parent.pt
Labels: DO-NOT-MERGE, READY-FOR-REVIEW

#2808 POL-1402 Azure Rightsizing Compute: Consider Managed Disk
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/README.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2829 FOPTS-5505 Fixed consumption calculation for ITAM Overused Licenses
  compliance/flexera/fnms/overused_licenses/CHANGELOG.md
  compliance/flexera/fnms/overused_licenses/overused_licenses.pt
Labels: bug, READY-FOR-REVIEW

#2838 FLEX-5397 - Fix Google Meta Parent Template
  tools/meta_parent_policy_compiler/google_meta_parent.pt.template
Labels: bug, READY-FOR-REVIEW, small fixes

#2722 FOPTS-5124 Added batch processing for some Policies with high memory consumption
  cost/azure/databricks/rightsize_compute/CHANGELOG.md
  cost/azure/databricks/rightsize_compute/azure_databricks_rightsize_compute.pt
  cost/azure/databricks/rightsize_compute/azure_databricks_rightsize_compute_meta_parent.pt
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations_meta_parent.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: enhancement, READY-FOR-REVIEW

#2841 POL-1416 New Policy: AWS S3 Incomplete Multi-Part Uploads
  cost/aws/s3_multipart_uploads/CHANGELOG.md
  cost/aws/s3_multipart_uploads/README.md
  cost/aws/s3_multipart_uploads/aws_s3_multipart_uploads.pt
  cost/aws/s3_multipart_uploads/aws_s3_multipart_uploads_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2837 POL-1417 Azure Savings Realized from Reservations - fix NaN issue related to incident creation
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: bug, READY-FOR-REVIEW, small fixes

#2847 FOPTS-5666 Handle properly null values in Google Rightsize VM Recommender Policy
  cost/google/rightsize_vm_recommendations/CHANGELOG.md
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations_meta_parent.pt
Labels: READY-FOR-REVIEW

#2859 POL-1419 Bug Fix for Azure Publicly-Accessible Blob Containers
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/azure/private_blob_containers/CHANGELOG.md
  security/azure/private_blob_containers/private_blob_containers.pt
  security/azure/private_blob_containers/private_blob_containers_meta_parent.pt
Labels: READY-FOR-REVIEW
