Repository flexera-public/policy_templates, pull requests merged in 2024-04, with the labels that each got.

#1999 POL-1157 Add Region Filtering to AWS/Azure Tag Cardinality Policies
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/tag_cardinality/CHANGELOG.md
  operational/aws/tag_cardinality/README.md
  operational/aws/tag_cardinality/aws_tag_cardinality.pt
  operational/aws/tag_cardinality/aws_tag_cardinality_meta_parent.pt
  operational/azure/tag_cardinality/CHANGELOG.md
  operational/azure/tag_cardinality/README.md
  operational/azure/tag_cardinality/azure_tag_cardinality.pt
  operational/azure/tag_cardinality/azure_tag_cardinality_meta_parent.pt
Labels: READY-FOR-REVIEW

#1960 SQ-7195 Spelling errors within 'ignored_recent_inventory_dates' policy template
  compliance/flexera/fnms/ignored_recent_inventory_dates/CHANGELOG.md
  compliance/flexera/fnms/ignored_recent_inventory_dates/ignored_recent_inventory_dates.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, READY FOR APPROVAL, small fixes

#2014 POL-1189 Change History Schedule Fix
  .github/workflows/generate-aws-ec2-pricing-json.yaml
  .github/workflows/generate-aws-rds-pricing-json.yaml
  .github/workflows/generate-azure-md-pricing-json.yaml
  .github/workflows/generate-azure-vm-pricing-json.yaml
  .github/workflows/update-change-history.yaml
  tools/change_history/generate_change_history.rb
Labels: READY-FOR-REVIEW

#2017 POL-1190 Bug Fix: Job Names for Github Workflow
  .github/workflows/generate-aws-ec2-pricing-json.yaml
  .github/workflows/generate-aws-rds-pricing-json.yaml
  .github/workflows/generate-azure-md-pricing-json.yaml
Labels: READY-FOR-REVIEW

#1958 feat: Add params for github repo for Policy Sync PT
  tools/policy_master_permission_generation/validated_policy_templates.yaml
  tools/policy_sync/CHANGELOG.md
  tools/policy_sync/policy_sync.pt
Labels: enhancement, READY-FOR-REVIEW

#2020 POL-1191 Azure Hybrid Use Benefit Policy for SQL Revamp
  .dangerfile/policy_tests.rb
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/README.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
  cost/azure/hybrid_use_benefit_sql/ahub_sql_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2022 POL-1192 Policy Metadata Fixes
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  Dangerfile
  cost/aws/reserved_instances/coverage/CHANGELOG.md
  cost/aws/reserved_instances/coverage/README.md
  cost/aws/reserved_instances/coverage/reserved_instance_coverage.pt
  cost/aws/reserved_instances/expiration/CHANGELOG.md
  cost/aws/reserved_instances/expiration/expired_ris.pt
  cost/aws/reserved_instances/utilization/CHANGELOG.md
  cost/aws/reserved_instances/utilization/utilization_ris.pt
  cost/aws/savings_plan/expiration/CHANGELOG.md
  cost/aws/savings_plan/expiration/README.md
  cost/aws/savings_plan/expiration/aws_savings_plan_expiration.pt
  cost/aws/savings_plan/utilization/CHANGELOG.md
  cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/total_instance_hours/CHANGELOG.md
  operational/aws/total_instance_hours/number_of_hours_per_instance_family.pt
  operational/aws/total_instance_hours_forecast/CHANGELOG.md
  operational/aws/total_instance_hours_forecast/aws_total_instance_hrs_forecast.pt
  operational/aws/total_instance_vcpus/CHANGELOG.md
  operational/aws/total_instance_vcpus/number_of_vcpus_per_instance_family.pt
  operational/aws/total_instance_vcpus_forecast/CHANGELOG.md
  operational/aws/total_instance_vcpus_forecast/aws_total_instance_vcpus_forecast.pt
  saas/fsm/deactivated_users/CHANGELOG.md
  saas/fsm/deactivated_users/README.md
  saas/fsm/deactivated_users/deactivated_users.pt
  saas/fsm/deactivated_users_for_integrated_apps/CHANGELOG.md
  saas/fsm/deactivated_users_for_integrated_apps/README.md
  saas/fsm/deactivated_users_for_integrated_apps/deactivated_users_for_integrated_apps.pt
  saas/fsm/duplicate_users/CHANGELOG.md
  saas/fsm/duplicate_users/README.md
  saas/fsm/duplicate_users/duplicate_users.pt
  saas/fsm/redundant_apps/CHANGELOG.md
  saas/fsm/redundant_apps/README.md
  saas/fsm/redundant_apps/fsm-redundant_apps.pt
  saas/fsm/renewal_reminder/CHANGELOG.md
  saas/fsm/renewal_reminder/README.md
  saas/fsm/renewal_reminder/fsm-renewal_reminder.pt
  saas/fsm/suspicious_users/CHANGELOG.md
  saas/fsm/suspicious_users/README.md
  saas/fsm/suspicious_users/fsm-suspicious_users.pt
  saas/fsm/unsanctioned_apps_with_contract/CHANGELOG.md
  saas/fsm/unsanctioned_apps_with_contract/README.md
  saas/fsm/unsanctioned_apps_with_contract/fsm-unsanctioned_with_contract.pt
  saas/fsm/unsanctioned_spend/CHANGELOG.md
  saas/fsm/unsanctioned_spend/README.md
  saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
  saas/fsm/user_status_change/CHANGELOG.md
  saas/fsm/user_status_change/README.md
  saas/fsm/user_status_change/fsm-user_status_change.pt
  saas/fsm/users_by_category/CHANGELOG.md
  saas/fsm/users_by_category/README.md
  saas/fsm/users_by_category/users_by_category.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1969 POL-600 Add Azure Usage Report - Number of Instance vCPUs Used
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/azure/total_instance_vcpus/CHANGELOG.md
  operational/azure/total_instance_vcpus/README.md
  operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#1970 POL-1179 Add Azure Usage Report - Amount of Instance Memory Used
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/azure/total_instance_memory/CHANGELOG.md
  operational/azure/total_instance_memory/README.md
  operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2036 POL-1193 New Policy: Flexera FOCUS Report
  .spellignore
  cost/flexera/cco/focus_report/CHANGELOG.md
  cost/flexera/cco/focus_report/README.md
  cost/flexera/cco/focus_report/focus_report.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2040 POL-1077 AWS S3 Intelligent Tiering Policy Revamp
  cost/aws/s3_storage_policy/CHANGELOG.md
  cost/aws/s3_storage_policy/README.md
  cost/aws/s3_storage_policy/aws_s3_bucket_policy_check.pt
  cost/aws/s3_storage_policy/aws_s3_bucket_policy_check_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2045 POL-1085 Azure Storage Accounts without Lifecycle Management Policies Revamp
  cost/azure/storage_account_lifecycle_management/CHANGELOG.md
  cost/azure/storage_account_lifecycle_management/README.md
  cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management.pt
  cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management_meta_parent.pt
Labels: READY-FOR-REVIEW

#2037 feat: add savings, param consider tag dimensions to AWS Untagged Resources PT
  .dangerfile/policy_tests.rb
  .spellignore
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/README.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
  compliance/aws/untagged_resources/aws_untagged_resources_meta_parent.pt
Labels: enhancement, READY-FOR-REVIEW

#2018 FOPTS-3624 Add support for MCA accounts
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
Labels: bug, READY-FOR-REVIEW

#2061 POL-1195 New Policy: AWS Resources Under Extended Support
  cost/aws/extended_support/CHANGELOG.md
  cost/aws/extended_support/README.md
  cost/aws/extended_support/aws_extended_support.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2071 POL-1199 Dangerfile False Positives with policy_blocks_ungrouped? Test Fix
  .dangerfile/policy_tests.rb
  Dangerfile
Labels: READY-FOR-REVIEW

#2075 POL-1201 Convert "AWS Resources Under Extended Support" into Savings Policy
  cost/aws/extended_support/CHANGELOG.md
  cost/aws/extended_support/README.md
  cost/aws/extended_support/aws_extended_support.pt
Labels: READY-FOR-REVIEW

#2081 POL-1203 Dangerfile Consolidated Output
  .dangerfile/changelog_tests.rb
  .dangerfile/code_tests.rb
  .dangerfile/general_tests.rb
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  Dangerfile
Labels: READY-FOR-REVIEW

#2062 POL-1198 Fix Scheduled Report Filtering
  cost/flexera/cco/scheduled_reports/CHANGELOG.md
  cost/flexera/cco/scheduled_reports/scheduled_report.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2079 POL-1202 Currency Conversion Fix
  cost/flexera/cco/currency_conversion/CHANGELOG.md
  cost/flexera/cco/currency_conversion/README.md
  cost/flexera/cco/currency_conversion/currency_conversion.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2055 POL-1194 Update Azure Usage Report policies to include BC Filter
  operational/azure/total_instance_hours/CHANGELOG.md
  operational/azure/total_instance_hours/README.md
  operational/azure/total_instance_hours/azure_usage_instance_hours_used.pt
  operational/azure/total_instance_memory/CHANGELOG.md
  operational/azure/total_instance_memory/README.md
  operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt
  operational/azure/total_instance_vcpus/CHANGELOG.md
  operational/azure/total_instance_vcpus/README.md
  operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt
Labels: enhancement, READY-FOR-REVIEW

#2060 POL-1196 Update AWS Usage Report policies to include BC Filter and Region Filter
  operational/aws/total_instance_hours/CHANGELOG.md
  operational/aws/total_instance_hours/README.md
  operational/aws/total_instance_hours/aws_usage_instance_hours_used.pt
  operational/aws/total_instance_memory/CHANGELOG.md
  operational/aws/total_instance_memory/README.md
  operational/aws/total_instance_memory/aws_usage_instance_memory_used.pt
  operational/aws/total_instance_vcpus/CHANGELOG.md
  operational/aws/total_instance_vcpus/README.md
  operational/aws/total_instance_vcpus/aws_usage_instance_vcpus_used.pt
Labels: enhancement, READY-FOR-REVIEW

#2082 FOPTS-3836 Fix: cloud_cost_anomaly_alerts.pt incident link
  cost/flexera/cco/cloud_cost_anomaly_alerts/CHANGELOG.md
  cost/flexera/cco/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Labels: bug, READY-FOR-REVIEW

#2091 POL-1205 Dangerfile Improvements
  .dangerfile/general_tests.rb
  .dangerfile/policy_tests.rb
  Dangerfile
Labels: READY-FOR-REVIEW

#2095 POL-1206 Semantic Versioning: Dangerfile and Documentation
  .dangerfile/policy_tests.rb
  .spellignore
  Dangerfile
  VERSIONING.md
Labels: READY-FOR-REVIEW

#2100 POL-1210 AWS Missing Regions Meta Policy Fix
  automation/aws/aws_missing_regions/CHANGELOG.md
  automation/aws/aws_missing_regions/README.md
  automation/aws/aws_missing_regions/aws_missing_regions.pt
  automation/aws/aws_missing_regions/aws_missing_regions_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2113 POL-1100 Policy Deprecations
  .dangerfile/changelog_tests.rb
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  Dangerfile
  operational/azure/azure_migrate/CHANGELOG.md
  operational/azure/azure_migrate/README.md
  operational/azure/azure_migrate/risc-azure-migrate.pt
  operational/azure/azuread_group_sync/CHANGELOG.md
  operational/azure/azuread_group_sync/README.md
  operational/azure/azuread_group_sync/azuread_group_sync.pt
  operational/azure/sync_tags_with_optima/CHANGELOG.md
  operational/azure/sync_tags_with_optima/README.md
  operational/azure/sync_tags_with_optima/sync_azure_tags.pt
  operational/flexera/risc/compute_instance_migration/CHANGELOG.md
  operational/flexera/risc/compute_instance_migration/README.md
  operational/flexera/risc/compute_instance_migration/risc-compute-instance-migration-recos.pt
  operational/flexera/risc/network_flow/CHANGELOG.md
  operational/flexera/risc/network_flow/README.md
  operational/flexera/risc/network_flow/risc-netflow.pt
Labels: READY-FOR-REVIEW

#2124 POL-1114 Google Policy Deprecations
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/README.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
  cost/google/unattached_volumes/CHANGELOG.md
  cost/google/unattached_volumes/README.md
  cost/google/unattached_volumes/google_delete_unattached_volumes.pt
  cost/google/unused_cloudsql_instances/CHANGELOG.md
  cost/google/unused_cloudsql_instances/README.md
  cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt
  cost/google/unutilized_ip_addresses/CHANGELOG.md
  cost/google/unutilized_ip_addresses/README.md
  cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Labels: READY-FOR-REVIEW

#2128 POL-1214 - fix: error for tag_dimension_tag_keys not defined
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
Labels: READY-FOR-REVIEW, small fixes

#2132 POL-1216 New Policy: Azure Unused Firewalls
  cost/azure/unused_firewalls/CHANGELOG.md
  cost/azure/unused_firewalls/README.md
  cost/azure/unused_firewalls/azure_unused_firewalls.pt
  cost/azure/unused_firewalls/azure_unused_firewalls_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2137 POL-1217 Email Cost Optimization Recommendations: Always Send Incident
  cost/flexera/cco/email_recommendations/CHANGELOG.md
  cost/flexera/cco/email_recommendations/README.md
  cost/flexera/cco/email_recommendations/email_recommendations.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2138 POL-1219 Update policies referencing Microsoft ISF Ratio CSV
  cost/azure/reserved_instances/utilization/CHANGELOG.md
  cost/azure/reserved_instances/utilization/README.md
  cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
  operational/azure/total_instance_hours/CHANGELOG.md
  operational/azure/total_instance_hours/azure_usage_instance_hours_used.pt
  operational/azure/total_instance_memory/CHANGELOG.md
  operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt
  operational/azure/total_instance_vcpus/CHANGELOG.md
  operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#2123 POL-1213 Google Old Snapshots: Add Savings
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/README.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
  cost/google/old_snapshots/google_delete_old_snapshots_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW
