Repository flexera-public/policy_templates, pull requests merged in 2024-02, with the labels that each got.

#1751 POL-1042 AWS Untagged Resources Revamp
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/README.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
  compliance/aws/untagged_resources/aws_untagged_resources_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1743 POL-995 Google Long Stopped Instances Revamp
  compliance/google/long_stopped_instances/CHANGELOG.md
  compliance/google/long_stopped_instances/README.md
  compliance/google/long_stopped_instances/google_long_stopped_instances.pt
  compliance/google/long_stopped_instances/google_long_stopped_instances_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1737 POL-994 Azure Disallowed Regions Revamp
  compliance/azure/azure_disallowed_regions/CHANGELOG.md
  compliance/azure/azure_disallowed_regions/README.md
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
  compliance/azure/azure_disallowed_regions/azure_disallowed_regions_meta_parent.pt
Labels: READY-FOR-REVIEW

#1746 POL-1000 AWS Long Running Instances Action Revamp
  operational/aws/long_running_instances/CHANGELOG.md
  operational/aws/long_running_instances/long_running_instances.pt
  operational/aws/long_running_instances/long_running_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1677 FOPTS-2607 Deployment of rightsize azure managed disks policy
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/README.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
  data/azure/azure_md_pricing.json
  data/azure/azure_md_pricing.py
  data/azure/azure_md_tier_types.json
  data/azure/azure_md_tier_types.py
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW, New Policy

#1747 POL-1003 Azure Long Running Instances Action Revamp
  operational/azure/azure_long_running_instances/CHANGELOG.md
  operational/azure/azure_long_running_instances/README.md
  operational/azure/azure_long_running_instances/azure_long_running_instances.pt
  operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1793 POL-999 Azure Blob Storage Optimization Revamp
  cost/azure/object_storage_optimization/CHANGELOG.md
  cost/azure/object_storage_optimization/README.md
  cost/azure/object_storage_optimization/azure_object_storage_optimization.pt
  cost/azure/object_storage_optimization/azure_object_storage_optimization_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1786 POL-1053 Custom Dimension Names in RBD Policies
  automation/aws/aws_rbd_from_tag/CHANGELOG.md
  automation/aws/aws_rbd_from_tag/README.md
  automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
  automation/azure/azure_rbd_from_rg_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_rg_tag/README.md
  automation/azure/azure_rbd_from_rg_tag/azure_rbd_from_rg_tag.pt
  automation/azure/azure_rbd_from_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_tag/README.md
  automation/azure/azure_rbd_from_tag/azure_rbd_from_tag.pt
  automation/google/google_rbd_from_label/CHANGELOG.md
  automation/google/google_rbd_from_label/README.md
  automation/google/google_rbd_from_label/google_rbd_from_label.pt
Labels: READY-FOR-REVIEW

#1799 POL-1055 Correct Path for Azure Blob Storage Optimization Policy
  cost/azure/blob_storage_optimization/CHANGELOG.md
  cost/azure/blob_storage_optimization/README.md
  cost/azure/blob_storage_optimization/azure_blob_storage_optimization.pt
  cost/azure/blob_storage_optimization/azure_blob_storage_optimization_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1805 POL-1056 New Policy: Azure Missing Subscriptions
  automation/azure/azure_missing_subscriptions/CHANGELOG.md
  automation/azure/azure_missing_subscriptions/README.md
  automation/azure/azure_missing_subscriptions/azure_missing_subscriptions.pt
Labels: READY-FOR-REVIEW

#1809 NVF/POL-918 - Add AWS Rightsize RDS Instances and Azure Rightsize SQL Instances
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1810 NVF/POL-918 Add AWS Rightsize EBS Volumes and Azure Rightsize Managed Disks
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1811 NVF/POL-918 Add Azure Reserved Instances Utilization
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1812 NVF/POL-918 Add Untagged Resources (AWS and Azure)
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1813 POL-1057 Google Unlabeled Resources - Update Permissions in README
  compliance/google/unlabeled_resources/README.md
Labels: READY-FOR-REVIEW

#1814 NVF/POL-918 Add Google Unlabeled Resources
  compliance/google/unlabeled_resources/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1815 NVF/POL-918 Add Azure Untagged Virtual Machines
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1820 NVF/POL-918 Add Long Running Instances (AWS and Azure), AWS Long Stopped EC2 Instances
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1819 POL-1005 Google Schedule Instance Revamp
  cost/google/schedule_instance/CHANGELOG.md
  cost/google/schedule_instance/README.md
  cost/google/schedule_instance/google_schedule_instance.pt
  cost/google/schedule_instance/google_schedule_instance_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#1816 POL-918 Create Master Policy Permissions List (2) Continued
  .github/workflows/generate-policy-master-permissions-json.yaml
  Dangerfile
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/generate_policy_master_permissions.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1808 POL-998 AWS Schedule Instance Revamp
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/README.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/aws/schedule_instance/aws_schedule_instance_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1817 POL-1004 Azure Schedule Instance Revamp
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/README.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
  cost/azure/schedule_instance/azure_schedule_instance_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1825 NVF/POL-918 (POL-1059) Add Google Long Stopped VM Instances
  compliance/google/long_stopped_instances/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1830 POL-1061 New Policy: Flexera Automation Outdated Applied Policies
  automation/flexera/outdated_applied_policies/CHANGELOG.md
  automation/flexera/outdated_applied_policies/README.md
  automation/flexera/outdated_applied_policies/outdated_applied_policies.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1834 Master Policy Permissions Update
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/generate_policy_master_permissions.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1829 FOPTS-3031 Update parameters of Azure Rightsize Managed Disk policy
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/README.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
Labels: enhancement, READY-FOR-REVIEW, READY FOR APPROVAL, small fixes

#1828 POL-1054 New Policy: Azure Bring-Your-Own-License (BYOL) Report
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/azure/byol_report/CHANGELOG.md
  operational/azure/byol_report/README.md
  operational/azure/byol_report/azure_byol_report.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#1847 Currency Conversion Fixes
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
  cost/aws/superseded_instances/CHANGELOG.md
  cost/aws/superseded_instances/aws_superseded_instances.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  cost/azure/superseded_instances/CHANGELOG.md
  cost/azure/superseded_instances/azure_superseded_instances.pt
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  cost/google/cud_recommendations/CHANGELOG.md
  cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/rightsize_vm_recommendations/CHANGELOG.md
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt
Labels: READY-FOR-REVIEW

#1840 POL-996 AWS Burstable EC2 Instances Revamp
  cost/aws/burstable_ec2_instances/CHANGELOG.md
  cost/aws/burstable_ec2_instances/README.md
  cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances.pt
  cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances_meta_parent.pt
  cost/aws/burstable_instance_cloudwatch_credit_utilization/README.md
  cost/aws/burstable_instance_cloudwatch_credit_utilization/aws_burstable_instance_cloudwatch_credit_utilization.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1841 POL-1017 AWS Old Snapshots Regex Support
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/README.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
Labels: READY-FOR-REVIEW

#1856 POL-1067 Add Required Flexera Permissions to Meta Policy README
  README_META_POLICIES.md
Labels: READY-FOR-REVIEW

#1707 FOPTS-2025 Deployment of Rightsize Azure NetApp Files Policy
  cost/azure/rightsize_netapp_files/CHANGELOG.md
  cost/azure/rightsize_netapp_files/README.md
  cost/azure/rightsize_netapp_files/azure_rightsize_netapp_files.pt
  cost/azure/rightsize_netapp_files/azure_rightsize_netapp_files_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: New Policy

#1842 POL-1018 AWS Policy Regex Support
  compliance/aws/long_stopped_instances/CHANGELOG.md
  compliance/aws/long_stopped_instances/README.md
  compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt
  compliance/aws/long_stopped_instances/aws_long_stopped_instances_meta_parent.pt
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/README.md
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
  cost/aws/rightsize_ec2_instances/CHANGELOG.md
  cost/aws/rightsize_ec2_instances/README.md
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/README.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/README.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/aws/schedule_instance/aws_schedule_instance_meta_parent.pt
  cost/aws/superseded_instances/CHANGELOG.md
  cost/aws/superseded_instances/README.md
  cost/aws/superseded_instances/aws_superseded_instances.pt
  cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt
  cost/aws/unused_clbs/CHANGELOG.md
  cost/aws/unused_clbs/README.md
  cost/aws/unused_clbs/aws_unused_clbs.pt
  cost/aws/unused_clbs/aws_unused_clbs_meta_parent.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/README.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/README.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
  operational/aws/long_running_instances/CHANGELOG.md
  operational/aws/long_running_instances/README.md
  operational/aws/long_running_instances/long_running_instances.pt
  operational/aws/long_running_instances/long_running_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1864 POL-1068 Cloud Cost Anomaly Alerts Link Fix
  cost/cloud_cost_anomaly_alerts/CHANGELOG.md
  cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Labels: READY-FOR-REVIEW

#1846 POL-1035 Google Policy Regex Support
  compliance/google/long_stopped_instances/CHANGELOG.md
  compliance/google/long_stopped_instances/README.md
  compliance/google/long_stopped_instances/google_long_stopped_instances.pt
  compliance/google/long_stopped_instances/google_long_stopped_instances_meta_parent.pt
  cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
  cost/google/cloud_sql_idle_instance_recommendations/README.md
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
  cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations_meta_parent.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/README.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations_meta_parent.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/README.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations_meta_parent.pt
  cost/google/object_storage_optimization/CHANGELOG.md
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/README.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
  cost/google/old_snapshots/google_delete_old_snapshots_meta_parent.pt
  cost/google/rightsize_vm_recommendations/CHANGELOG.md
  cost/google/rightsize_vm_recommendations/README.md
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations_meta_parent.pt
  cost/google/schedule_instance/CHANGELOG.md
  cost/google/schedule_instance/README.md
  cost/google/schedule_instance/google_schedule_instance.pt
  cost/google/schedule_instance/google_schedule_instance_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/storage/google/public_buckets/CHANGELOG.md
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#1833 POL-1062 Deprecate CMP Policies
  cost/aws/reserved_instances/expiration/CHANGELOG.md
  cost/aws/reserved_instances/expiration/README.md
  cost/aws/reserved_instances/expiration/expired_ris.pt
  cost/azure/reserved_instances/expiration/CHANGELOG.md
  cost/azure/reserved_instances/expiration/README.md
  cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
  operational/aws/subnet_name_sync/CHANGELOG.md
  operational/aws/subnet_name_sync/README.md
  operational/aws/subnet_name_sync/aws_subnet_name_sync.pt
  operational/aws/vpc_name_sync/CHANGELOG.md
  operational/aws/vpc_name_sync/README.md
  operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
Labels: READY-FOR-REVIEW

#1874 POL-1070 Deprecate AWS Inefficient Instance Utilization using CloudWatch
  cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
  cost/aws/instance_cloudwatch_utilization/README.md
  cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
Labels: READY-FOR-REVIEW

#1870 FOPTS-3238 Update `short_description` of the policy Azure Rightsize NetApp Files
  cost/azure/rightsize_netapp_files/CHANGELOG.md
  cost/azure/rightsize_netapp_files/azure_rightsize_netapp_files.pt
Labels: READY-FOR-REVIEW, READY FOR APPROVAL, small fixes, documentation

#1873 POL-973 Azure Unused IPs Better Filtering
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/README.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
Labels: enhancement, READY-FOR-REVIEW

#1875 POL-1071 Merge 'AWS RDS Instances' policy into 'AWS Rightsize RDS Instances'
  cost/aws/rds_instance_license_info/CHANGELOG.md
  cost/aws/rds_instance_license_info/README.md
  cost/aws/rds_instance_license_info/rds_instance_license_info.pt
  cost/aws/rds_instance_license_info/rds_instance_license_info_meta_parent.pt
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#1867 POL-1046 Google Open Buckets Revamp
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/storage/google/public_buckets/CHANGELOG.md
  security/storage/google/public_buckets/README.md
  security/storage/google/public_buckets/google_public_buckets.pt
  security/storage/google/public_buckets/google_public_buckets_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW
