Repository flexera-public/policy_templates, pull requests merged in 2024-08, with the labels that each got.

#2501 POL-1309 Vendor Spend Commitment Forecast Revamp
  cost/flexera/cco/forecasting/commitment_forecast/CHANGELOG.md
  cost/flexera/cco/forecasting/commitment_forecast/README.md
  cost/flexera/cco/forecasting/commitment_forecast/commitment_forecast.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2502 POL-1316 - feat: Generally Recommend Policy Templates List
  .gitignore
  Rakefile
  data/active_policy_list/README.md
  data/active_policy_list/generally_recommended_templates.json
Labels: enhancement, READY-FOR-REVIEW

#2508 fix: minor wording fix on incident detail template
  automation/flexera/outdated_applied_policies/CHANGELOG.md
  automation/flexera/outdated_applied_policies/outdated_applied_policies.pt
Labels: READY-FOR-REVIEW, small fixes

#2503 POL-1313 SaaS Policy Revamps
  .spellignore
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  saas/office365/security_alerts/CHANGELOG.md
  saas/office365/security_alerts/README.md
  saas/office365/security_alerts/o365-security-alerts.pt
  saas/office365/security_alerts/o365_security_alerts.pt
  saas/okta/inactive_users/CHANGELOG.md
  saas/okta/inactive_users/README.md
  saas/okta/inactive_users/okta-inactive-users.pt
  saas/okta/inactive_users/okta_inactive_users.pt
  saas/servicenow/inactive_approvers/CHANGELOG.md
  saas/servicenow/inactive_approvers/README.md
  saas/servicenow/inactive_approvers/servicenow_inactive_approvers.pt
  tools/policy_master_permission_generation/generate_policy_master_permissions.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2474 POL-1302 New Usage Revamp
  cost/flexera/cco/new_service_usage/README.md
  cost/flexera/cco/new_service_usage/new_service_usage.pt
  cost/flexera/cco/new_usage/CHANGELOG.md
  cost/flexera/cco/new_usage/README.md
  cost/flexera/cco/new_usage/new_usage.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2472 POL-1297 Azure Security Policy Revamps: Part 4
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/azure/storage_account_https_enabled/CHANGELOG.md
  security/azure/storage_account_https_enabled/README.md
  security/azure/storage_account_https_enabled/azure_storage_account_https_enabled.pt
  security/azure/storage_network_deny/CHANGELOG.md
  security/azure/storage_network_deny/README.md
  security/azure/storage_network_deny/storage_network_deny.pt
  security/azure/storage_network_deny/storage_network_deny_meta_parent.pt
  security/azure/storage_soft_delete/CHANGELOG.md
  security/azure/storage_soft_delete/README.md
  security/azure/storage_soft_delete/storage_soft_delete.pt
  security/azure/storage_soft_delete/storage_soft_delete_meta_parent.pt
  security/azure/storage_tls_version/CHANGELOG.md
  security/azure/storage_tls_version/README.md
  security/azure/storage_tls_version/storage_tls_version.pt
  security/azure/storage_tls_version/storage_tls_version_meta_parent.pt
  security/azure/storage_trusted_services/CHANGELOG.md
  security/azure/storage_trusted_services/README.md
  security/azure/storage_trusted_services/storage_trusted_services.pt
  security/azure/storage_trusted_services/storage_trusted_services_meta_parent.pt
  security/azure/table_storage_logging/CHANGELOG.md
  security/azure/table_storage_logging/README.md
  security/azure/table_storage_logging/table_storage_logging.pt
  security/azure/table_storage_logging/table_storage_logging_meta_parent.pt
  security/azure/webapp_tls_version_support/CHANGELOG.md
  security/azure/webapp_tls_version_support/README.md
  security/azure/webapp_tls_version_support/azure_webapp_min_tls_version.pt
  security/azure/webapp_tls_version_support/azure_webapp_min_tls_version_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2506 POL-1317 AWS Superseded EC2 Instances Fix/Improvement
  Gemfile
  Gemfile.lock
  cost/aws/superseded_instances/CHANGELOG.md
  cost/aws/superseded_instances/README.md
  cost/aws/superseded_instances/aws_superseded_instances.pt
  cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#2505 POL-1315 AWS Rightsize RDS Instances: Additional Metrics
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#2527 POL-1319: Fix Spelling Issue In Description: AWS Unused Classic Load Balancers
  cost/aws/unused_clbs/CHANGELOG.md
  cost/aws/unused_clbs/aws_unused_clbs.pt
  cost/aws/unused_clbs/aws_unused_clbs_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2529 POL-1320 Azure RI/SP Policy API Update
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations_meta_parent.pt
  cost/azure/savings_plan/recommendations/CHANGELOG.md
  cost/azure/savings_plan/recommendations/azure_savings_plan_recommendations.pt
  cost/azure/savings_plan/recommendations/azure_savings_plan_recommendations_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2494 POL-1310 New Policy: AWS EC2 Compute Optimizer Recommendations
  cost/aws/ec2_compute_optimizer/CHANGELOG.md
  cost/aws/ec2_compute_optimizer/README.md
  cost/aws/ec2_compute_optimizer/aws_ec2_compute_optimizer.pt
  cost/aws/ec2_compute_optimizer/aws_ec2_compute_optimizer_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2496 POL-1311 New Policy: Azure Advisor Compute Instances Recommendations
  cost/azure/advisor_compute/CHANGELOG.md
  cost/azure/advisor_compute/README.md
  cost/azure/advisor_compute/azure_advisor_compute.pt
  cost/azure/advisor_compute/azure_advisor_compute_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2534 POL-1294 RBD Policy Logic Fix
  automation/aws/aws_rbd_from_tag/CHANGELOG.md
  automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
  automation/azure/azure_rbd_from_rg_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_rg_tag/azure_rbd_from_rg_tag.pt
  automation/azure/azure_rbd_from_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_tag/azure_rbd_from_tag.pt
  automation/google/google_rbd_from_label/CHANGELOG.md
  automation/google/google_rbd_from_label/google_rbd_from_label.pt
Labels: READY-FOR-REVIEW

#2511 POL-1308 New Policy: Flexera One User Access Report
  data/flexera/iam_roles.json
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/iam/iam_user_report/CHANGELOG.md
  operational/flexera/iam/iam_user_report/README.md
  operational/flexera/iam/iam_user_report/iam_user_report.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2521 POL-1318 New Policy: AWS CloudTrails With Read Logging Enabled
  cost/aws/cloudtrail_read_logging/CHANGELOG.md
  cost/aws/cloudtrail_read_logging/README.md
  cost/aws/cloudtrail_read_logging/aws_cloudtrail_read_logging.pt
  cost/aws/cloudtrail_read_logging/aws_cloudtrail_read_logging_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2547 POL-1322 New Policy: Google Label Cardinality Report
  .spellignore
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/google/label_cardinality/CHANGELOG.md
  operational/google/label_cardinality/README.md
  operational/google/label_cardinality/google_label_cardinality.pt
  operational/google/label_cardinality/google_label_cardinality_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2557 POL-1323 - fix: AWS Rightsize EC2 get memory metrics for Autoscaling groups
  cost/aws/rightsize_ec2_instances/CHANGELOG.md
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
Labels: READY-FOR-REVIEW, small fixes

#2566 POL-1324 AWS Burstable EC2 Instances: Switch to GetMetricData
  cost/aws/burstable_ec2_instances/CHANGELOG.md
  cost/aws/burstable_ec2_instances/README.md
  cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances.pt
  cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2567 POL-1325 AWS Oversized S3 Buckets: Switch to GetMetricData
  cost/aws/s3_bucket_size/CHANGELOG.md
  cost/aws/s3_bucket_size/README.md
  cost/aws/s3_bucket_size/aws_bucket_size.pt
  cost/aws/s3_bucket_size/aws_bucket_size_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#1917 POL-727 Azure Savings Plan Utilization v0.1.0
  cost/azure/savings_plan/utilization/CHANGELOG.md
  cost/azure/savings_plan/utilization/README.md
  cost/azure/savings_plan/utilization/azure_savings_plan_utilization.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2578 POL-1333 Dangerfile Enhancements
  .dangerfile/changelog_tests.rb
  .dangerfile/code_tests.rb
  .dangerfile/general_tests.rb
  .dangerfile/github_tests.rb
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  .github/workflows/test-policies.yaml
  .ruby-version
  .spellignore
  Dangerfile
  Gemfile
  Gemfile.lock
  requirements.txt
Labels: READY-FOR-REVIEW

#2580 POL-1333 Dangerfile Enhancements (Minor Fix)
  .dangerfile/general_tests.rb
  .spellignore
Labels: READY-FOR-REVIEW

#2543 POL-803 New Policy: Azure Unused App Service Plans
  cost/azure/unused_app_service_plans/CHANGELOG.md
  cost/azure/unused_app_service_plans/README.md
  cost/azure/unused_app_service_plans/azure_unused_app_service_plans.pt
  cost/azure/unused_app_service_plans/azure_unused_app_service_plans_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2544 POL-802 New Policy: Azure Unused Virtual Network Gateways
  cost/azure/unused_vngs/CHANGELOG.md
  cost/azure/unused_vngs/README.md
  cost/azure/unused_vngs/azure_unused_vngs.pt
  cost/azure/unused_vngs/azure_unused_vngs_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy
