Repository flexera-public/policy_templates, pull requests merged in 2024-05, with the labels that each got.

#2118 POL-1106 Google Unlabeled Resources Revamp
  .dangerfile/policy_tests.rb
  compliance/google/unlabeled_resources/CHANGELOG.md
  compliance/google/unlabeled_resources/README.md
  compliance/google/unlabeled_resources/unlabeled_resources.pt
  compliance/google/unlabeled_resources/unlabeled_resources_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#2108 POL-1087 AWS IAM Role Audit Revamp
  .spellignore
  compliance/aws/iam_role_audit/CHANGELOG.md
  compliance/aws/iam_role_audit/README.md
  compliance/aws/iam_role_audit/aws_iam_role_audit.pt
  compliance/aws/iam_role_audit/aws_iam_role_audit_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2099 POL-1209 Add "newResourceType" field to idle/unused incidents for multi-incident Recommendation policies
  .dangerfile/policy_tests.rb
  Dangerfile
  cost/aws/rightsize_ec2_instances/CHANGELOG.md
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
  cost/google/rightsize_vm_recommendations/CHANGELOG.md
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt
  cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2112 POL-1090 Azure Regulatory Compliance Revamp
  compliance/azure/compliance_score/CHANGELOG.md
  compliance/azure/compliance_score/README.md
  compliance/azure/compliance_score/azure_regulatory_compliance_report.pt
  compliance/azure/compliance_score/azure_regulatory_compliance_report_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2117 POL-1105 Azure VMs Not Using Managed Disks Revamp
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/azure/vms_without_managed_disks/CHANGELOG.md
  operational/azure/vms_without_managed_disks/README.md
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
  operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks_meta_parent.pt
Labels: READY-FOR-REVIEW

#2152 POL-1220 Fix AWS Untagged Resources in EU/AU
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
  compliance/aws/untagged_resources/aws_untagged_resources_meta_parent.pt
Labels: READY-FOR-REVIEW

#2153 POL-1221 Usage Report Policies - Update BC Filter to support Child Billing Centers
  operational/aws/total_instance_hours/CHANGELOG.md
  operational/aws/total_instance_hours/aws_usage_instance_hours_used.pt
  operational/aws/total_instance_memory/CHANGELOG.md
  operational/aws/total_instance_memory/aws_usage_instance_memory_used.pt
  operational/aws/total_instance_vcpus/CHANGELOG.md
  operational/aws/total_instance_vcpus/aws_usage_instance_vcpus_used.pt
  operational/azure/total_instance_hours/CHANGELOG.md
  operational/azure/total_instance_hours/azure_usage_instance_hours_used.pt
  operational/azure/total_instance_memory/CHANGELOG.md
  operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt
  operational/azure/total_instance_vcpus/CHANGELOG.md
  operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt
Labels: enhancement, READY-FOR-REVIEW

#2127 POL-1113 Google Recommenders Revamp
  .spellignore
  cost/google/recommender/CHANGELOG.md
  cost/google/recommender/README.md
  cost/google/recommender/recommender.pt
  cost/google/recommender/recommender_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2147 POL-1094 AWS Lambda Functions With High Error Rate Revamp
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/lambda_functions_with_high_error_rate/CHANGELOG.md
  operational/aws/lambda_functions_with_high_error_rate/README.md
  operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate.pt
  operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate_meta_parent.pt
Labels: READY-FOR-REVIEW

#2161 POL-1204 Fix Outdated image-charts.com Links
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  Dangerfile
  cost/flexera/cco/budget_alerts/CHANGELOG.md
  cost/flexera/cco/budget_alerts/budget_alert.pt
  cost/flexera/cco/budget_v_actual/CHANGELOG.md
  cost/flexera/cco/budget_v_actual/monthly_budget_v_actual.pt
  cost/flexera/cco/budget_v_actual_spend_report/CHANGELOG.md
  cost/flexera/cco/budget_v_actual_spend_report/budget_v_actual_spend_report.pt
  cost/flexera/cco/scheduled_reports/CHANGELOG.md
  cost/flexera/cco/scheduled_reports/scheduled_report.pt
  cost/flexera/cco/scheduled_reports_with_estimates/CHANGELOG.md
  cost/flexera/cco/scheduled_reports_with_estimates/README.md
  cost/flexera/cco/scheduled_reports_with_estimates/costs_forecasting.pt
  cost/flexera/msp/master_org_cost_policy/CHANGELOG.md
  cost/flexera/msp/master_org_cost_policy/README.md
  cost/flexera/msp/master_org_cost_policy/master_org_cost_policy.pt
  cost/flexera/msp/master_org_cost_policy_currency/CHANGELOG.md
  cost/flexera/msp/master_org_cost_policy_currency/README.md
  cost/flexera/msp/master_org_cost_policy_currency/master_org_cost_policy_currency.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2163 POL-1224 Fix Google Recommender/Policy List Generation
  .dangerfile/policy_tests.rb
  Dangerfile
  cost/google/recommender/CHANGELOG.md
  cost/google/recommender/recommender.pt
  cost/google/recommender/recommender_meta_parent.pt
Labels: READY-FOR-REVIEW

#2173 POL-1225 Azure Rightsize SQL Databases: New Incident Fields
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/README.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2169 POL-1223 New Policy: AWS EKS Clusters Without Spot Instances
  cost/aws/eks_without_spot/CHANGELOG.md
  cost/aws/eks_without_spot/README.md
  cost/aws/eks_without_spot/aws_eks_without_spot.pt
  cost/aws/eks_without_spot/aws_eks_without_spot_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2164 SQ-7228 Incorrect currency code and inflated savings bug
  cost/azure/savings_realized/CHANGELOG.md
  cost/azure/savings_realized/azure_savings_realized.pt
Labels: READY-FOR-REVIEW, small fixes

#2183 POL-1092 Update/Deprecate Azure Subscription Access
  compliance/azure/subscription_access/CHANGELOG.md
  compliance/azure/subscription_access/README.md
  compliance/azure/subscription_access/azure_subscription_access.pt
Labels: READY-FOR-REVIEW

#2176 POL-1111 Deprecate Google Inefficient Instance Utilization using StackDriver Policy
  cost/google/instances_stackdriver_utilization/CHANGELOG.md
  cost/google/instances_stackdriver_utilization/README.md
  cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
Labels: READY-FOR-REVIEW

#2175 POL-1112 Google Object Storage Optimization Revamp
  cost/google/object_storage_optimization/CHANGELOG.md
  cost/google/object_storage_optimization/README.md
  cost/google/object_storage_optimization/google_object_storage_optimization.pt
  cost/google/object_storage_optimization/google_object_storage_optimization_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2184 POL-1226 AWS Untagged Resources Improvements
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/README.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
  compliance/aws/untagged_resources/aws_untagged_resources_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2188 POL-1109 Google Committed Use Discount Report Revamp
  cost/google/cud_report/CHANGELOG.md
  cost/google/cud_report/README.md
  cost/google/cud_report/google_committed_use_discount_report.pt
  cost/google/cud_report/google_committed_use_discount_report_meta_parent.pt
  cost/google/cud_report/google_committed_usediscount_report.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2189 POL-1108 Google Expiring Committed Use Discounts (CUD) Revamp
  cost/google/cud_expiration/CHANGELOG.md
  cost/google/cud_expiration/README.md
  cost/google/cud_expiration/google_cud_expiration_report.pt
  cost/google/cud_expiration/google_cud_expiration_report_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2195 POL-1228 feat: Unallocated Cost Report enhancements
  cost/scheduled_report_unallocated/CHANGELOG.md
  cost/scheduled_report_unallocated/README.md
  cost/scheduled_report_unallocated/scheduled_report_unallocated.pt
Labels: enhancement, READY-FOR-REVIEW

#2194 POL-1224 Azure RightsizeSQL bug fix
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
Labels: READY FOR APPROVAL

#2187 FOPTS-3939 Update: List of cheaper regions for Azure and AWS vendors
  cost/flexera/cco/cheaper_regions/CHANGELOG.md
  cost/flexera/cco/cheaper_regions/README.md
  cost/flexera/cco/cheaper_regions/cheaper_regions.pt
  data/aws/regions.json
  data/azure/regions.json
  data/google/regions.json
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: bug, READY-FOR-REVIEW

#2208 POL-1229 Dangerfile Update: Enforce Directory Structure
  .dangerfile/policy_tests.rb
  Dangerfile
  cost/flexera/cco/scheduled_report_unallocated/CHANGELOG.md
  cost/flexera/cco/scheduled_report_unallocated/README.md
  cost/flexera/cco/scheduled_report_unallocated/example_report.png
  cost/flexera/cco/scheduled_report_unallocated/scheduled_report_unallocated.pt
Labels: READY-FOR-REVIEW

#2216 POL-1074 Deprecate Policy: AWS Reserved Instance Report by Billing Center
  cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
  cost/aws/reserved_instances/report_by_bc/README.md
  cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
Labels: READY-FOR-REVIEW

#2219 POL-1079 AWS Savings Plan Utilization Revamp
  cost/aws/savings_plan/utilization/CHANGELOG.md
  cost/aws/savings_plan/utilization/README.md
  cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2228 POL-1232 New Policy: AWS EC2 Instances Time Stopped Report
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/ec2_stopped_report/CHANGELOG.md
  operational/aws/ec2_stopped_report/README.md
  operational/aws/ec2_stopped_report/aws_ec2_stopped_report.pt
  operational/aws/ec2_stopped_report/aws_ec2_stopped_report_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2193 POL-1093 AWS Scheduled EC2 Events Revamp
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/instance_scheduled_events/README.md
  operational/aws/instance_scheduled_events/aws_instance_scheduled_events.pt
  operational/aws/scheduled_ec2_events/CHANGELOG.md
  operational/aws/scheduled_ec2_events/README.md
  operational/aws/scheduled_ec2_events/aws_scheduled_ec2_events.pt
  operational/aws/scheduled_ec2_events/aws_scheduled_ec2_events_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2225 POL-1231 New Policy: Azure Usage Report - Instance Time Used
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/azure/total_instance_hours/CHANGELOG.md
  operational/azure/total_instance_hours/README.md
  operational/azure/total_instance_hours/azure_usage_instance_hours_used.pt
  operational/azure/total_instance_memory/CHANGELOG.md
  operational/azure/total_instance_memory/README.md
  operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt
  operational/azure/total_instance_usage_report/CHANGELOG.md
  operational/azure/total_instance_usage_report/README.md
  operational/azure/total_instance_usage_report/azure_total_instance_usage_report.pt
  operational/azure/total_instance_vcpus/CHANGELOG.md
  operational/azure/total_instance_vcpus/README.md
  operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2136 POL-1215 Azure Web Apps With Unoptimized Scaling
  .spellignore
  cost/azure/unoptimized_web_app_scaling/CHANGELOG.md
  cost/azure/unoptimized_web_app_scaling/README.md
  cost/azure/unoptimized_web_app_scaling/azure_unoptimized_web_app_scaling.pt
  cost/azure/unoptimized_web_app_scaling/azure_unoptimized_web_app_scaling_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: DO-NOT-MERGE, New Policy

#2249 FOPTS-4009 add cumulative report option
  cost/flexera/cco/budget_v_actual_spend_report/CHANGELOG.md
  cost/flexera/cco/budget_v_actual_spend_report/README.md
  cost/flexera/cco/budget_v_actual_spend_report/budget_v_actual_spend_report.pt
Labels: DO-NOT-MERGE, READY-FOR-REVIEW, javascript

#2246 POL-1244 Update 'resourceType' Incident Fields
  .dangerfile/policy_tests.rb
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
  cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
  cost/aws/unused_clbs/CHANGELOG.md
  cost/aws/unused_clbs/aws_unused_clbs.pt
  cost/aws/unused_clbs/aws_unused_clbs_meta_parent.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
  cost/azure/old_snapshots/CHANGELOG.md
  cost/azure/old_snapshots/azure_delete_old_snapshots.pt
  cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
  cost/azure/unoptimized_web_app_scaling/CHANGELOG.md
  cost/azure/unoptimized_web_app_scaling/azure_unoptimized_web_app_scaling.pt
  cost/azure/unoptimized_web_app_scaling/azure_unoptimized_web_app_scaling_meta_parent.pt
  cost/azure/unused_firewalls/CHANGELOG.md
  cost/azure/unused_firewalls/azure_unused_firewalls.pt
  cost/azure/unused_firewalls/azure_unused_firewalls_meta_parent.pt
  cost/azure/unused_ip_addresses/CHANGELOG.md
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
  cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
  cost/azure/unused_volumes/CHANGELOG.md
  cost/azure/unused_volumes/azure_unused_volumes.pt
  cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
  cost/google/idle_ip_address_recommendations/CHANGELOG.md
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
  cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations_meta_parent.pt
  cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
  cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations_meta_parent.pt
  cost/google/old_snapshots/CHANGELOG.md
  cost/google/old_snapshots/google_delete_old_snapshots.pt
  cost/google/old_snapshots/google_delete_old_snapshots_meta_parent.pt
Labels: READY-FOR-REVIEW

#2253 FOPTS-4039 Bug fix for unitofMeasure for ultra sized disk
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
Labels: READY-FOR-REVIEW, automation

#2258 POL-1246 AWS/Azure Usage Reports - fix BC Allow/Deny Filter
  operational/aws/total_instance_usage_report/CHANGELOG.md
  operational/aws/total_instance_usage_report/aws_total_instance_usage_report.pt
  operational/azure/total_instance_usage_report/CHANGELOG.md
  operational/azure/total_instance_usage_report/azure_total_instance_usage_report.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#2248 POL-1247 fix: Add default value for `IAM Role Names/IDs/ARNs` param
  compliance/aws/iam_role_audit/CHANGELOG.md
  compliance/aws/iam_role_audit/aws_iam_role_audit.pt
Labels: READY-FOR-REVIEW, small fixes

#2262 FOPTS-4009 Revert Flexera Cred Changes in Update README.md
  .dangerfile/readme_tests.rb
  cost/flexera/cco/budget_v_actual_spend_report/README.md
Labels: DO-NOT-MERGE, READY-FOR-REVIEW
