Repository flexera-public/policy_templates, pull requests merged in 2024-12, with the labels that each got.

#2862 POL-1415 AWS Rightsize RDS Instances: Add Connections to Incident Table
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2867 POL-1422 Fix AWS New Marketplace Products
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/marketplace_new_products/CHANGELOG.md
  operational/aws/marketplace_new_products/aws_marketplace_new_products.pt
Labels: READY-FOR-REVIEW

#2817 POL-1410 - Improve Scheduled Instance Notifications
  .dangerfile/policy_tests.rb
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
  cost/google/schedule_instance/CHANGELOG.md
  cost/google/schedule_instance/google_schedule_instance.pt
Labels: enhancement, READY-FOR-REVIEW

#2651 POL-1362 Flexera Policy CloudFormation Template Automation
  .github/workflows/generate-aws-cloudformation-template.yaml
  .spellignore
  compliance/aws/untagged_resources/README.md
  cost/aws/s3_storage_policy/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/aws/s3_buckets_deny_http/README.md
  security/aws/s3_buckets_without_server_access_logging/README.md
  security/aws/s3_ensure_buckets_block_public_access/README.md
  security/aws/s3_ensure_mfa_delete_enabled/README.md
  security/aws/unencrypted_s3_buckets/README.md
  tools/cloudformation-template/FlexeraAutomationPoliciesSimple.template
  tools/cloudformation-template/README.md
  tools/cloudformation-template/aws_cft_generator.rb
  tools/cloudformation-template/rolling/FlexeraAutomationPolicies.template
  tools/cloudformation-template/rolling/FlexeraAutomationPoliciesReadOnly.template
Labels: READY-FOR-REVIEW

#2882 POL-1362 AWS CFT Automation Fix
  tools/cloudformation-template/aws_cft_generator.template.txt
Labels: READY-FOR-REVIEW

#2883 POL-1430 Automate Updating AWS CloudFormation Template
  .github/workflows/cfn-lint.yaml
  .github/workflows/cfn-test.yaml
  .github/workflows/generate-aws-cloudformation-template.yaml
  .github/workflows/update-aws-cloudformation-template.yaml
  cost/aws/s3_lifecycle/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/cloudformation-template/FlexeraAutomationPolicies.template
  tools/cloudformation-template/FlexeraAutomationPoliciesReadOnly.template
  tools/cloudformation-template/README.md
  tools/cloudformation-template/aws_cft_generator.rb
  tools/cloudformation-template/aws_cft_generator.template.txt
  tools/cloudformation-template/aws_cft_new_release.rb
  tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.9.0.template
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2869 POL-1414 Currency Conversion Functionality on Kubecost cluster rightsizing policy
  cost/kubecost/cluster/CHANGELOG.md
  cost/kubecost/cluster/kubecost_cluster_rightsizing_recommendations.pt
Labels: READY-FOR-REVIEW, READY FOR APPROVAL

#2833 POL-1405 Replace deprecated Kubecost endpoints for Kubecost Cluster Policy
  cost/kubecost/cluster/CHANGELOG.md
  cost/kubecost/cluster/README.md
  cost/kubecost/cluster/kubecost_cluster_rightsizing_recommendations.pt
Labels: READY-FOR-REVIEW, READY FOR APPROVAL

#2887 FLEX-5165 Add datalake optimization policy template
  cost/azure/data_lake_optimization/CHANGELOG.md
  cost/azure/data_lake_optimization/README.md
  cost/azure/data_lake_optimization/data_lake_optimization.pt
  cost/azure/data_lake_optimization/data_lake_optimization_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy
