Repository flexera-public/policy_templates, pull requests merged in 2024-10, with the labels that each got.

#2679 POL-1367 New Policy: Azure Rightsize SQL Managed Instance Storage
  cost/azure/rightsize_managed_sql_storage/CHANGELOG.md
  cost/azure/rightsize_managed_sql_storage/README.md
  cost/azure/rightsize_managed_sql_storage/azure_rightsize_managed_sql_storage.pt
  cost/azure/rightsize_managed_sql_storage/azure_rightsize_managed_sql_storage_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2649 POL-1361 Azure Rightsize NetApp Files: Add ignore_status / Misc fixes and Improvements
  cost/azure/rightsize_netapp/CHANGELOG.md
  cost/azure/rightsize_netapp/README.md
  cost/azure/rightsize_netapp/azure_rightsize_netapp.pt
  cost/azure/rightsize_netapp/azure_rightsize_netapp_meta_parent.pt
  cost/azure/rightsize_netapp_files/CHANGELOG.md
  cost/azure/rightsize_netapp_files/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: enhancement, READY-FOR-REVIEW, small fixes

#2668 POL-1354 New Policy: AWS Rightsize Redshift
  cost/aws/rightsize_redshift/CHANGELOG.md
  cost/aws/rightsize_redshift/README.md
  cost/aws/rightsize_redshift/aws_rightsize_redshift.pt
  cost/aws/rightsize_redshift/aws_rightsize_redshift_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2713 POL-1329 Fix calculation of IOPS and Bandwith at Azure Rightsize Managed Disk
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
Labels: READY-FOR-REVIEW, READY FOR APPROVAL

#2708 POL-1373 Update AWS Superseded EBS Volumes - fix incorrect "New Monthly List Price" value
  cost/aws/superseded_ebs_volumes/CHANGELOG.md
  cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes.pt
  cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW, small fixes

#2721 POL-1377 Cloud Bill Processing Error Notification: Fixes/Improvements
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/cco/bill_processing_errors_notification/CHANGELOG.md
  operational/flexera/cco/bill_processing_errors_notification/bill_processing_errors_notification.pt
Labels: READY-FOR-REVIEW

#2709 POL-1374 Email Cost Optimization Recommendations: Added Policy Support
  cost/flexera/cco/email_recommendations/CHANGELOG.md
  cost/flexera/cco/email_recommendations/email_recommendations.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2702 POL-1355 New Policy: AWS Rightsize ElastiCache
  .spellignore
  cost/aws/rightsize_elasticache/CHANGELOG.md
  cost/aws/rightsize_elasticache/README.md
  cost/aws/rightsize_elasticache/aws_rightsize_elasticache.pt
  cost/aws/rightsize_elasticache/aws_rightsize_elasticache_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2739 POL-1381 Update AWS Instance Types JSON to include superseded instances for db.t family
  data/aws/instance_types.json
Labels: enhancement, READY-FOR-REVIEW, data

#2712 POL-1139 New Policy: AWS S3 Usage Type Rule-Based Dimension
  .spellignore
  automation/aws/aws_s3_usage_type_rbd/CHANGELOG.md
  automation/aws/aws_s3_usage_type_rbd/README.md
  automation/aws/aws_s3_usage_type_rbd/aws_s3_usage_type_rbd.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2743 POL-1382 Currency Conversion: Multiple Dimension Support
  cost/flexera/cco/currency_conversion/CHANGELOG.md
  cost/flexera/cco/currency_conversion/README.md
  cost/flexera/cco/currency_conversion/currency_conversion.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2726 POL-1375 Google Label Cardinality Report: BigQuery Fix
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/google/label_cardinality/CHANGELOG.md
  operational/google/label_cardinality/google_label_cardinality.pt
  operational/google/label_cardinality/google_label_cardinality_meta_parent.pt
Labels: READY-FOR-REVIEW

#2728 POL-1379 Azure SQL MI Storage Pricing Automation
  .github/workflows/generate-azure-sqlmi-storage-pricing-json
  cost/azure/rightsize_managed_sql_storage/CHANGELOG.md
  cost/azure/rightsize_managed_sql_storage/azure_rightsize_managed_sql_storage.pt
  cost/azure/rightsize_managed_sql_storage/azure_rightsize_managed_sql_storage_meta_parent.pt
  data/azure/azure_sqlmi_storage_pricing.json
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/cloud_data/azure/azure_sqlmi_storage_pricing.py
Labels: READY-FOR-REVIEW

#2616 POL-1330 New Policy: AWS Account Credentials
  .spellignore
  automation/aws/aws_account_credentials/CHANGELOG.md
  automation/aws/aws_account_credentials/META_README.md
  automation/aws/aws_account_credentials/README.md
  automation/aws/aws_account_credentials/aws_account_credentials.pt
  automation/aws/aws_account_credentials/aws_account_credentials_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2729 POL-1378 Linting Updates: Automation Policies
  .dangerfile/policy_tests.rb
  .spellignore
  automation/aws/aws_account_credentials/CHANGELOG.md
  automation/aws/aws_account_credentials/aws_account_credentials.pt
  automation/aws/aws_account_credentials/aws_account_credentials_meta_parent.pt
  automation/aws/aws_missing_regions/CHANGELOG.md
  automation/aws/aws_missing_regions/README.md
  automation/aws/aws_missing_regions/aws_missing_regions.pt
  automation/aws/aws_missing_regions/aws_missing_regions_meta_parent.pt
  automation/aws/aws_rbd_from_tag/README.md
  automation/azure/azure_missing_subscriptions/CHANGELOG.md
  automation/azure/azure_missing_subscriptions/README.md
  automation/azure/azure_missing_subscriptions/azure_missing_subscriptions.pt
  automation/azure/azure_rbd_from_rg_tag/README.md
  automation/azure/azure_rbd_from_tag/README.md
  automation/flexera/delete_all_billing_centers/CHANGELOG.md
  automation/flexera/delete_all_billing_centers/README.md
  automation/flexera/delete_all_billing_centers/delete_all_billing_centers.pt
  automation/flexera/outdated_applied_policies/CHANGELOG.md
  automation/flexera/outdated_applied_policies/README.md
  automation/flexera/outdated_applied_policies/outdated_applied_policies.pt
  automation/google/google_rbd_from_label/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2753 POL-1386 Dangerfile Improvements
  .dangerfile/policy_tests.rb
  Dangerfile
Labels: READY-FOR-REVIEW

#2733 POL-1378 Linting Updates: SaaS Policies
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  saas/fsm/deactivated_users/CHANGELOG.md
  saas/fsm/deactivated_users/README.md
  saas/fsm/deactivated_users/deactivated_users.pt
  saas/fsm/deactivated_users_for_integrated_apps/CHANGELOG.md
  saas/fsm/deactivated_users_for_integrated_apps/README.md
  saas/fsm/deactivated_users_for_integrated_apps/deactivated_users_for_integrated_apps.pt
  saas/fsm/duplicate_users/CHANGELOG.md
  saas/fsm/duplicate_users/README.md
  saas/fsm/duplicate_users/duplicate_users.pt
  saas/fsm/redundant_apps/CHANGELOG.md
  saas/fsm/redundant_apps/README.md
  saas/fsm/redundant_apps/fsm-redundant_apps.pt
  saas/fsm/renewal_reminder/CHANGELOG.md
  saas/fsm/renewal_reminder/README.md
  saas/fsm/renewal_reminder/fsm-renewal_reminder.pt
  saas/fsm/suspicious_users/CHANGELOG.md
  saas/fsm/suspicious_users/README.md
  saas/fsm/suspicious_users/fsm-suspicious_users.pt
  saas/fsm/unsanctioned_apps_with_contract/CHANGELOG.md
  saas/fsm/unsanctioned_apps_with_contract/README.md
  saas/fsm/unsanctioned_apps_with_contract/fsm-unsanctioned_with_contract.pt
  saas/fsm/unsanctioned_spend/CHANGELOG.md
  saas/fsm/unsanctioned_spend/README.md
  saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
  saas/fsm/user_status_change/CHANGELOG.md
  saas/fsm/user_status_change/README.md
  saas/fsm/user_status_change/fsm-user_status_change.pt
  saas/fsm/users_by_category/CHANGELOG.md
  saas/fsm/users_by_category/README.md
  saas/fsm/users_by_category/users_by_category.pt
  saas/office365/security_alerts/README.md
  saas/okta/inactive_users/README.md
  saas/servicenow/inactive_approvers/README.md
Labels: READY-FOR-REVIEW

#2738 POL-1380 Applied Policy Template Errors: Child Policy Support
  operational/flexera/automation/applied_policy_error_notification/CHANGELOG.md
  operational/flexera/automation/applied_policy_error_notification/README.md
  operational/flexera/automation/applied_policy_error_notification/applied_policy_error_notification.pt
Labels: READY-FOR-REVIEW

#2759 POL-1390 AWS Rightsize EC2 Instances: Downsize Multiple Tiers
  cost/aws/rightsize_ec2_instances/CHANGELOG.md
  cost/aws/rightsize_ec2_instances/README.md
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2762 POL-1391 Azure Rightsize Compute Instances: Downsize Multiple Tiers
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/README.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2763 POL-1392 AWS Rightsize RDS Instances: Downsize Multiple Tiers
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/README.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2772 POL-1398 Azure Expiring Credentials - fix Days Until Expiration bug
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/azure/azure_certificates/CHANGELOG.md
  operational/azure/azure_certificates/azure_certificates.pt
  operational/azure/azure_certificates/azure_certificates_meta_parent.pt
Labels: READY-FOR-REVIEW

#2774 POL-1400 Fix Invalid Recommendations: Azure Rightsize SQL Managed Instances
  README.md
  cost/azure/rightsize_managed_sql/CHANGELOG.md
  cost/azure/rightsize_managed_sql/azure_rightsize_managed_sql.pt
  cost/azure/rightsize_managed_sql/azure_rightsize_managed_sql_meta_parent.pt
  data/azure/sqlmi_tier_types.json
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2777 POL-1404 AWS Superseded EBS Volumes - Fix Currency Conversion Message in Policy Incident
  cost/aws/superseded_ebs_volumes/CHANGELOG.md
  cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes.pt
  cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: bug, READY-FOR-REVIEW

#2747 POL-1385 - New Template: Billing Centers from Dimensions
  operational/flexera/cco/billing_centers_from_dimensions/CHANGELOG.md
  operational/flexera/cco/billing_centers_from_dimensions/README.md
  operational/flexera/cco/billing_centers_from_dimensions/billing_centers_from_dimensions.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2787 POL-1406 AWS Rightsize RDS Instances Fix
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2788 POL-1393 Downsize Multiple Sizes: Azure Rightsize SQL Databases
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/README.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2789 POL-1396 Downsize Multiple Sizes: Azure Rightsize SQL Managed Instances
  cost/azure/rightsize_managed_sql/CHANGELOG.md
  cost/azure/rightsize_managed_sql/README.md
  cost/azure/rightsize_managed_sql/azure_rightsize_managed_sql.pt
  cost/azure/rightsize_managed_sql/azure_rightsize_managed_sql_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2792 POL-1407 Downsize Multiple Sizes: AWS Rightsize ElastiCache
  cost/aws/rightsize_elasticache/CHANGELOG.md
  cost/aws/rightsize_elasticache/README.md
  cost/aws/rightsize_elasticache/aws_rightsize_elasticache.pt
  cost/aws/rightsize_elasticache/aws_rightsize_elasticache_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2790 POL-1394 Downsize Multiple Sizes: Azure MySQL
  cost/azure/rightsize_mysql_flexible/CHANGELOG.md
  cost/azure/rightsize_mysql_flexible/README.md
  cost/azure/rightsize_mysql_flexible/azure_rightsize_mysql_flexible.pt
  cost/azure/rightsize_mysql_flexible/azure_rightsize_mysql_flexible_meta_parent.pt
  cost/azure/rightsize_mysql_single/CHANGELOG.md
  cost/azure/rightsize_mysql_single/README.md
  cost/azure/rightsize_mysql_single/azure_rightsize_mysql_single.pt
  cost/azure/rightsize_mysql_single/azure_rightsize_mysql_single_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2800 POL-1408 AWS Account Credentials Meta Not Spawning Children
  automation/aws/aws_account_credentials/CHANGELOG.md
  automation/aws/aws_account_credentials/aws_account_credentials.pt
  automation/aws/aws_account_credentials/aws_account_credentials_meta_parent.pt
Labels: READY-FOR-REVIEW
