Repository flexera-public/policy_templates, pull requests merged in 2024-07, with the labels that each got.

#2359 POL-1274 Dangerfile: console.log() Test
  .dangerfile/policy_tests.rb
  Dangerfile
Labels: READY-FOR-REVIEW

#2355 POL-1271 Azure Rightsize Managed Disks: SKU Filtering
  .spellignore
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/README.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2371 POL-1276 New Policy: Fixed Cost Common Bill Ingestion
  .dangerfile/policy_tests.rb
  cost/flexera/cco/fixed_cost_cbi/CHANGELOG.md
  cost/flexera/cco/fixed_cost_cbi/README.md
  cost/flexera/cco/fixed_cost_cbi/fixed_cost_cbi.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2374 POL-1277 Cheaper Regions Revamp
  cost/aws/cheaper_regions/CHANGELOG.md
  cost/aws/cheaper_regions/README.md
  cost/aws/cheaper_regions/aws_cheaper_regions.pt
  cost/azure/cheaper_regions/CHANGELOG.md
  cost/azure/cheaper_regions/README.md
  cost/azure/cheaper_regions/azure_cheaper_regions.pt
  cost/flexera/cco/cheaper_regions/CHANGELOG.md
  cost/flexera/cco/cheaper_regions/README.md
  cost/flexera/cco/cheaper_regions/cheaper_regions.pt
  cost/google/cheaper_regions/CHANGELOG.md
  cost/google/cheaper_regions/README.md
  cost/google/cheaper_regions/google_cheaper_regions.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2360 POL-1167 p90/95/99 Support for Azure Rightsize Compute/SQL Policies
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/README.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/README.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
Labels: READY-FOR-REVIEW

#2375 POL-1278 Deprecate/Unpublish Azure Tag Resources with Resource Group Name Policy
  compliance/azure/azure_rg_tags/CHANGELOG.md
  compliance/azure/azure_rg_tags/azure_resource_group_tags.pt
Labels: READY-FOR-REVIEW

#2395 POL-1286 New Policy: Azure Rightsize SQL Managed Instances
  cost/azure/rightsize_managed_sql/CHANGELOG.md
  cost/azure/rightsize_managed_sql/README.md
  cost/azure/rightsize_managed_sql/azure_rightsize_managed_sql.pt
  cost/azure/rightsize_managed_sql/azure_rightsize_managed_sql_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2393 POL-1285 Powered Off Report Math Fix
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/ec2_stopped_report/CHANGELOG.md
  operational/aws/ec2_stopped_report/aws_ec2_stopped_report.pt
  operational/aws/ec2_stopped_report/aws_ec2_stopped_report_meta_parent.pt
  operational/azure/compute_poweredoff_report/CHANGELOG.md
  operational/azure/compute_poweredoff_report/azure_compute_poweredoff_report.pt
  operational/azure/compute_poweredoff_report/azure_compute_poweredoff_report_meta_parent.pt
Labels: READY-FOR-REVIEW

#2382 POL-1280 Flexera Users With Explicit Roles Revamp
  compliance/flexera/iam/iam_explicit_user_roles/CHANGELOG.md
  compliance/flexera/iam/iam_explicit_user_roles/README.md
  compliance/flexera/iam/iam_explicit_user_roles/flexera_iam_explicit_user_roles.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2388 POL-1237 Azure Hybrid Use Benefit for SQL Improvements
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/README.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
  cost/azure/hybrid_use_benefit_sql/ahub_sql_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2376 POL-1279 AWS RDS Instances With Unapproved Backup Settings Revamp
  .spellignore
  compliance/aws/rds_backup/CHANGELOG.md
  compliance/aws/rds_backup/README.md
  compliance/aws/rds_backup/aws_rds_backup.pt
  compliance/aws/rds_backup/aws_rds_backup_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/rds_backup/README.md
  operational/aws/rds_backup/aws_rds_backup.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2394 Fix syntax erros from the meta parent policy of Azure Synapse
  cost/azure/rightsize_synapse_sql_pools/CHANGELOG.md
  cost/azure/rightsize_synapse_sql_pools/azure_rightsize_synapse_sql_pools.pt
  cost/azure/rightsize_synapse_sql_pools/azure_rightsize_synapse_sql_pools_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: bug, DO-NOT-MERGE, small fixes, azure

#2404 POL-1271 Add parameter to decide recommending HDD or not
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/README.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
Labels: enhancement, DO-NOT-MERGE, READY-FOR-REVIEW, READY FOR APPROVAL, small fixes

#1630 POL-745 SaaS Manager - SaaS App User Report by Category Revamp/Unpublish
  saas/fsm/users_by_category/CHANGELOG.md
  saas/fsm/users_by_category/README.md
  saas/fsm/users_by_category/users_by_category.pt
Labels: READY-FOR-REVIEW

#2396 POL-1287 RBD Policy API Update
  automation/aws/aws_rbd_from_tag/CHANGELOG.md
  automation/aws/aws_rbd_from_tag/README.md
  automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
  automation/azure/azure_rbd_from_rg_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_rg_tag/README.md
  automation/azure/azure_rbd_from_rg_tag/azure_rbd_from_rg_tag.pt
  automation/azure/azure_rbd_from_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_tag/README.md
  automation/azure/azure_rbd_from_tag/azure_rbd_from_tag.pt
  automation/google/google_rbd_from_label/CHANGELOG.md
  automation/google/google_rbd_from_label/README.md
  automation/google/google_rbd_from_label/google_rbd_from_label.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2428 POL-1295 Azure Reserved Instances Recommendation: Shared Fix
  .dangerfile/policy_tests.rb
  cost/azure/reserved_instances/recommendations/CHANGELOG.md
  cost/azure/reserved_instances/recommendations/README.md
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
  cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations_meta_parent.pt
Labels: READY-FOR-REVIEW

#2414 POL-1281 AWS Security Policy Revamps: Part 3
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/aws/kms_rotation/CHANGELOG.md
  security/aws/kms_rotation/README.md
  security/aws/kms_rotation/kms_rotation.pt
  security/aws/loadbalancer_internet_facing/CHANGELOG.md
  security/aws/loadbalancer_internet_facing/README.md
  security/aws/loadbalancer_internet_facing/aws_internet-facing_elbs.pt
  security/aws/loadbalancer_internet_facing/aws_internet_facing_elbs.pt
  security/aws/loadbalancer_internet_facing/aws_internet_facing_elbs_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2424 FOPTS-4349 Display recommendation in the local currency.
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
Labels: enhancement, READY-FOR-REVIEW

#2425 POL-1281 AWS Security Policy Revamps: Part 4
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/aws/log_cloudtrail_cloudwatch_integrated/CHANGELOG.md
  security/aws/log_cloudtrail_cloudwatch_integrated/README.md
  security/aws/log_cloudtrail_cloudwatch_integrated/log_cloudtrail_cloudwatch_integrated.pt
  security/aws/log_ensure_cloudtrail_bucket_access_logging/CHANGELOG.md
  security/aws/log_ensure_cloudtrail_bucket_access_logging/README.md
  security/aws/log_ensure_cloudtrail_bucket_access_logging/log_ensure_cloudtrail_bucket_access_logging.pt
  security/aws/log_ensure_cloudtrail_bucket_not_public/CHANGELOG.md
  security/aws/log_ensure_cloudtrail_bucket_not_public/README.md
  security/aws/log_ensure_cloudtrail_bucket_not_public/log_ensure_cloudtrail_bucket_not_public.pt
  security/aws/log_ensure_cloudtrail_bucket_object_logging/CHANGELOG.md
  security/aws/log_ensure_cloudtrail_bucket_object_logging/README.md
  security/aws/log_ensure_cloudtrail_bucket_object_logging/log_ensure_cloudtrail_bucket_object_logging.pt
  security/aws/log_ensure_cloudtrail_encrypted/CHANGELOG.md
  security/aws/log_ensure_cloudtrail_encrypted/README.md
  security/aws/log_ensure_cloudtrail_encrypted/log_ensure_cloudtrail_encrypted.pt
  security/aws/log_ensure_cloudtrail_multiregion/CHANGELOG.md
  security/aws/log_ensure_cloudtrail_multiregion/README.md
  security/aws/log_ensure_cloudtrail_multiregion/log_ensure_cloudtrail_multiregion.pt
  security/aws/log_file_validation_enabled/CHANGELOG.md
  security/aws/log_file_validation_enabled/README.md
  security/aws/log_file_validation_enabled/log_file_validation_enabled.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2447 POL-1281 AWS Security Policy Revamps: Part 6
  .spellignore
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/aws/s3_buckets_deny_http/CHANGELOG.md
  security/aws/s3_buckets_deny_http/README.md
  security/aws/s3_buckets_deny_http/s3_buckets_deny_http.pt
  security/aws/s3_buckets_deny_http/s3_buckets_deny_http_meta_parent.pt
  security/aws/s3_buckets_without_server_access_logging/CHANGELOG.md
  security/aws/s3_buckets_without_server_access_logging/README.md
  security/aws/s3_buckets_without_server_access_logging/aws_s3_buckets_without_server_access_logging.pt
  security/aws/s3_buckets_without_server_access_logging/aws_s3_buckets_without_server_access_logging_meta_parent.pt
  security/aws/s3_ensure_buckets_block_public_access/CHANGELOG.md
  security/aws/s3_ensure_buckets_block_public_access/README.md
  security/aws/s3_ensure_buckets_block_public_access/s3_ensure_buckets_block_public_access.pt
  security/aws/s3_ensure_buckets_block_public_access/s3_ensure_buckets_block_public_access_meta_parent.pt
  security/aws/s3_ensure_mfa_delete_enabled/CHANGELOG.md
  security/aws/s3_ensure_mfa_delete_enabled/README.md
  security/aws/s3_ensure_mfa_delete_enabled/s3_ensure_mfa_delete_enabled.pt
  security/aws/s3_ensure_mfa_delete_enabled/s3_ensure_mfa_delete_enabled_meta_parent.pt
  security/aws/unencrypted_s3_buckets/CHANGELOG.md
  security/aws/unencrypted_s3_buckets/README.md
  security/aws/unencrypted_s3_buckets/aws_unencrypted_s3_buckets.pt
  security/aws/unencrypted_s3_buckets/aws_unencrypted_s3_buckets_meta_parent.pt
  security/aws/vpcs_without_flow_logs_enabled/CHANGELOG.md
  security/aws/vpcs_without_flow_logs_enabled/README.md
  security/aws/vpcs_without_flow_logs_enabled/aws_vpcs_without_flow_logs_enabled.pt
  security/aws/vpcs_without_flow_logs_enabled/aws_vpcs_without_flow_logs_enabled_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2453 POL-1300 - fix: use `PaginationToken` for paginating tagging API
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
  operational/aws/tag_cardinality/CHANGELOG.md
  operational/aws/tag_cardinality/aws_tag_cardinality.pt
Labels: bug, READY-FOR-REVIEW

#2459 POL-1169 P90, P95 and P99 for Azure Rightsize Managed Disks
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/README.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
Labels: enhancement, READY-FOR-REVIEW

#2451 POL-1297 Azure Security Policy Revamps: Part 1
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/azure/blob_storage_logging/CHANGELOG.md
  security/azure/blob_storage_logging/README.md
  security/azure/blob_storage_logging/blob_storage_logging.pt
  security/azure/blob_storage_logging/blob_storage_logging_meta_parent.pt
  security/azure/guest_users/CHANGELOG.md
  security/azure/guest_users/README.md
  security/azure/guest_users/guest_users.pt
  security/azure/high_severity_alerts/CHANGELOG.md
  security/azure/high_severity_alerts/README.md
  security/azure/high_severity_alerts/high_severity_alerts.pt
  security/azure/log_analytics_autoprovision/CHANGELOG.md
  security/azure/log_analytics_autoprovision/README.md
  security/azure/log_analytics_autoprovision/log_analytics_autoprovision.pt
  security/azure/mysql_ssl/CHANGELOG.md
  security/azure/mysql_ssl/README.md
  security/azure/mysql_ssl/mysql_ssl.pt
  security/azure/mysql_ssl/mysql_ssl_meta_parent.pt
  security/azure/mysql_tls_version/CHANGELOG.md
  security/azure/mysql_tls_version/README.md
  security/azure/mysql_tls_version/mysql_tls_version.pt
  security/azure/mysql_tls_version/mysql_tls_version_meta_parent.pt
  security/azure/pg_conn_throttling/CHANGELOG.md
  security/azure/pg_conn_throttling/README.md
  security/azure/pg_conn_throttling/pg_conn_throttling.pt
  security/azure/pg_conn_throttling/pg_conn_throttling_meta_parent.pt
  security/azure/pg_infra_encryption/CHANGELOG.md
  security/azure/pg_infra_encryption/README.md
  security/azure/pg_infra_encryption/pg_infra_encryption.pt
  security/azure/pg_infra_encryption/pg_infra_encryption_meta_parent.pt
  security/azure/pg_log_retention/CHANGELOG.md
  security/azure/pg_log_retention/README.md
  security/azure/pg_log_retention/pg_log_retention.pt
  security/azure/pg_log_retention/pg_log_retention_meta_parent.pt
  security/azure/pg_log_settings/CHANGELOG.md
  security/azure/pg_log_settings/README.md
  security/azure/pg_log_settings/pg_log_settings.pt
  security/azure/pg_log_settings/pg_log_settings_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2452 POL-1297 Azure Security Policy Revamps: Part 2
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  security/azure/private_blob_containers/CHANGELOG.md
  security/azure/private_blob_containers/README.md
  security/azure/private_blob_containers/private_blob_containers.pt
  security/azure/private_blob_containers/private_blob_containers_meta_parent.pt
  security/azure/queue_storage_logging/CHANGELOG.md
  security/azure/queue_storage_logging/README.md
  security/azure/queue_storage_logging/queue_storage_logging.pt
  security/azure/queue_storage_logging/queue_storage_logging_meta_parent.pt
  security/azure/resources_with_public_ip_address/CHANGELOG.md
  security/azure/resources_with_public_ip_address/README.md
  security/azure/resources_with_public_ip_address/azure_open_ip_address_policy.pt
  security/azure/restrict_rdp_internet/CHANGELOG.md
  security/azure/restrict_rdp_internet/README.md
  security/azure/restrict_rdp_internet/azure_restrict_rdp_inet.pt
  security/azure/restrict_rdp_internet/azure_restrict_rdp_inet_meta_parent.pt
  security/azure/restrict_ssh_internet/CHANGELOG.md
  security/azure/restrict_ssh_internet/README.md
  security/azure/restrict_ssh_internet/azure_restrict_ssh_inet.pt
  security/azure/restrict_ssh_internet/azure_restrict_ssh_inet_meta_parent.pt
  security/azure/secure_transfer_required/CHANGELOG.md
  security/azure/secure_transfer_required/README.md
  security/azure/secure_transfer_required/secure_transfer_required.pt
  security/azure/secure_transfer_required/secure_transfer_required_meta_parent.pt
  security/azure/security_alert_owners/CHANGELOG.md
  security/azure/security_alert_owners/README.md
  security/azure/security_alert_owners/security_alert_owners.pt
  security/azure/security_alert_owners/security_alert_owners_meta_parent.pt
  security/azure/security_contact_email/CHANGELOG.md
  security/azure/security_contact_email/README.md
  security/azure/security_contact_email/security_contact_email.pt
  security/azure/security_contact_email/security_contact_email_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2476 POL-1304 Add Hourly Cost to Time Stopped Policy Templates
  operational/aws/ec2_stopped_report/CHANGELOG.md
  operational/aws/ec2_stopped_report/README.md
  operational/aws/ec2_stopped_report/aws_ec2_stopped_report.pt
  operational/aws/ec2_stopped_report/aws_ec2_stopped_report_meta_parent.pt
  operational/azure/compute_poweredoff_report/CHANGELOG.md
  operational/azure/compute_poweredoff_report/README.md
  operational/azure/compute_poweredoff_report/azure_compute_poweredoff_report.pt
  operational/azure/compute_poweredoff_report/azure_compute_poweredoff_report_meta_parent.pt
Labels: READY-FOR-REVIEW

#2478 POL-1306 Add Hourly Cost to AHUB Policy Templates
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/README.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit_meta_parent.pt
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/README.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
  cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
  cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
  cost/azure/hybrid_use_benefit_sql/README.md
  cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
  cost/azure/hybrid_use_benefit_sql/ahub_sql_meta_parent.pt
Labels: READY-FOR-REVIEW

#2475 POL-1303 Kubecost Policy Template Revamps
  .spellignore
  cost/kubecost/cluster/CHANGELOG.md
  cost/kubecost/cluster/README.md
  cost/kubecost/cluster/kubecost_cluster_rightsizing_recommendations.pt
  cost/kubecost/sizing/CHANGELOG.md
  cost/kubecost/sizing/README.md
  cost/kubecost/sizing/kubecost_resizing_recommendation.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW
