Repository flexera-public/policy_templates, pull requests merged in 2024-09, with the labels that each got.

#2584 POL-1335 Add ARN to AWS Recommendation Policy Template Incident Tables
  .spellignore
  cost/aws/burstable_ec2_instances/CHANGELOG.md
  cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances.pt
  cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances_meta_parent.pt
  cost/aws/ec2_compute_optimizer/CHANGELOG.md
  cost/aws/ec2_compute_optimizer/aws_ec2_compute_optimizer.pt
  cost/aws/ec2_compute_optimizer/aws_ec2_compute_optimizer_meta_parent.pt
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
  cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes.pt
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes_meta_parent.pt
  cost/aws/rightsize_ec2_instances/CHANGELOG.md
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
  cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
  cost/aws/superseded_ebs_volumes/CHANGELOG.md
  cost/aws/superseded_ebs_volumes/README.md
  cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes.pt
  cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes_meta_parent.pt
  cost/aws/superseded_instances/CHANGELOG.md
  cost/aws/superseded_instances/aws_superseded_instances.pt
  cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt
  cost/aws/unused_albs/CHANGELOG.md
  cost/aws/unused_albs/aws_unused_albs.pt
  cost/aws/unused_albs/aws_unused_albs_meta_parent.pt
  cost/aws/unused_clbs/CHANGELOG.md
  cost/aws/unused_clbs/aws_unused_clbs.pt
  cost/aws/unused_clbs/aws_unused_clbs_meta_parent.pt
  cost/aws/unused_ip_addresses/CHANGELOG.md
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
  cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
  cost/aws/unused_nlbs/CHANGELOG.md
  cost/aws/unused_nlbs/aws_unused_nlbs.pt
  cost/aws/unused_nlbs/aws_unused_nlbs_meta_parent.pt
  cost/aws/unused_volumes/CHANGELOG.md
  cost/aws/unused_volumes/aws_delete_unused_volumes.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2597 POL-1336 AWS Savings Plan Recommendations: Remove "Any" Option From Savings Plan Term Parameter
  cost/aws/savings_plan/recommendations/CHANGELOG.md
  cost/aws/savings_plan/recommendations/README.md
  cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
Labels: READY-FOR-REVIEW

#2601 POL-1252 Cloud Cost Anomaly Alerts: Additional Parameters
  .spellignore
  cost/flexera/cco/cloud_cost_anomaly_alerts/CHANGELOG.md
  cost/flexera/cco/cloud_cost_anomaly_alerts/README.md
  cost/flexera/cco/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Labels: READY-FOR-REVIEW

#2560 POL-411 Low Usage: Added Resource List
  cost/flexera/cco/low_usage/CHANGELOG.md
  cost/flexera/cco/low_usage/low_usage.pt
Labels: READY-FOR-REVIEW

#2576 POL-1331 New Policy: Azure Advisor Carbon Reduction Recommendations
  compliance/azure/advisor_carbon/CHANGELOG.md
  compliance/azure/advisor_carbon/README.md
  compliance/azure/advisor_carbon/azure_advisor_carbon.pt
  compliance/azure/advisor_carbon/azure_advisor_carbon_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2617 POL-1344 Account Support for AWS Untagged Resources Policy Template
  compliance/aws/untagged_resources/CHANGELOG.md
  compliance/aws/untagged_resources/README.md
  compliance/aws/untagged_resources/aws_untagged_resources.pt
  compliance/aws/untagged_resources/aws_untagged_resources_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2619 task: remove Databricks from generally recommended
  data/active_policy_list/generally_recommended_templates.json
Labels: READY-FOR-REVIEW

#2556 POL-793 Azure MySQL Policy Templates
  cost/azure/rightsize_mysql_flexible/CHANGELOG.md
  cost/azure/rightsize_mysql_flexible/README.md
  cost/azure/rightsize_mysql_flexible/azure_rightsize_mysql_flexible.pt
  cost/azure/rightsize_mysql_flexible/azure_rightsize_mysql_flexible_meta_parent.pt
  cost/azure/rightsize_mysql_single/CHANGELOG.md
  cost/azure/rightsize_mysql_single/README.md
  cost/azure/rightsize_mysql_single/azure_rightsize_mysql_single.pt
  cost/azure/rightsize_mysql_single/azure_rightsize_mysql_single_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2565 POL-1327 New Policy: AWS Lambda Functions Without Provisioned Concurrency
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/aws/lambda_provisioned_concurrency/CHANGELOG.md
  operational/aws/lambda_provisioned_concurrency/README.md
  operational/aws/lambda_provisioned_concurrency/aws_lambda_provisioned_concurrency.pt
  operational/aws/lambda_provisioned_concurrency/aws_lambda_provisioned_concurrency_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2634 POL-1353 New Policy: Azure Unused Load Balancers
  .spellignore
  cost/azure/unused_load_balancers/CHANGELOG.md
  cost/azure/unused_load_balancers/README.md
  cost/azure/unused_load_balancers/azure_unused_load_balancers.pt
  cost/azure/unused_load_balancers/azure_unused_load_balancers_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2622 POL-1348 Cloud Bill Processing Error Notification: Ignore List
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/cco/bill_processing_errors_notification/CHANGELOG.md
  operational/flexera/cco/bill_processing_errors_notification/README.md
  operational/flexera/cco/bill_processing_errors_notification/bill_processing_errors_notification.pt
Labels: READY-FOR-REVIEW

#2642 POL-1358 AWS Rule-Based Dimension From Account Tags: Tag Casing Fix
  automation/aws/aws_rbd_from_tag/CHANGELOG.md
  automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
Labels: READY-FOR-REVIEW

#2610 POL-1338 Validated Permissions
  .github/workflows/generate-policy-master-permission-missing-templates.yaml
  .spellignore
  automation/azure/azure_missing_subscriptions/README.md
  compliance/flexera/fnms/fnms_licenses_expiring/README.md
  compliance/flexera/fnms/overused_licenses/README.md
  compliance/flexera/msp/orgs_and_cloud_accounts_report/README.md
  cost/azure/reserved_instances/utilization_mca/README.md
  cost/flexera/cco/billing_center_cost_anomaly/CHANGELOG.md
  cost/flexera/cco/billing_center_cost_anomaly/README.md
  cost/flexera/cco/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
  cost/flexera/cco/budget_report_alerts/README.md
  cost/flexera/cco/forecasting/straight_line_forecast_simple/CHANGELOG.md
  cost/flexera/cco/forecasting/straight_line_forecast_simple/straight_line_forecast_simple.pt
  cost/flexera/cco/scheduled_report_markupsdowns/README.md
  cost/flexera/cmp/rightlink_rightsize/rightlink_rightsize_add_tags.pt
  cost/turbonomics/credential_refresh/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  data/policy_permissions_list/missing_policy_templates.json
  data/policy_permissions_list/missing_policy_templates.yaml
  operational/flexera/automation/applied_policy_error_notification/README.md
  operational/flexera/fnms/schedule_fnms_reports/README.md
  operational/flexera/fnms/schedule_fnms_reports/schedule_fnms_report.pt
  saas/fsm/deactivated_users/README.md
  saas/fsm/deactivated_users_for_integrated_apps/README.md
  saas/fsm/duplicate_users/README.md
  saas/fsm/redundant_apps/README.md
  saas/fsm/renewal_reminder/README.md
  saas/fsm/suspicious_users/README.md
  saas/fsm/unsanctioned_apps_with_contract/README.md
  saas/fsm/unsanctioned_spend/README.md
  saas/fsm/user_status_change/README.md
  saas/fsm/users_by_category/README.md
  security/aws/public_buckets/README.md
  tools/policy_master_permission_generation/generate_missing_permission_list.rb
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2647 POL-1360 Meta Parent: Fix Deprecation Status
  cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume_meta_parent.pt
  cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
  cost/aws/rds_instance_license_info/rds_instance_license_info_meta_parent.pt
  cost/aws/unused_rds/unused_rds_meta_parent.pt
  cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
  cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt
  cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#2621 POL-1345 Azure Untagged Resources: Subscription/Resource Group Support
  compliance/azure/azure_untagged_resources/CHANGELOG.md
  compliance/azure/azure_untagged_resources/README.md
  compliance/azure/azure_untagged_resources/untagged_resources.pt
  compliance/azure/azure_untagged_resources/untagged_resources_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2637 POL-1354 AWS RedShift/ElastiCache Resource Types Data
  data/aws/elasticache_types.json
  data/aws/redshift_types.json
Labels: READY-FOR-REVIEW

#2624 POL-1349 Applied Policy Template Errors Revamp
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/automation/applied_policy_error_notification/CHANGELOG.md
  operational/flexera/automation/applied_policy_error_notification/README.md
  operational/flexera/automation/applied_policy_error_notification/applied_policy_error_notification.pt
Labels: READY-FOR-REVIEW

#2656 POL-1013 Add Azure Expiring Savings Plans Policy
  cost/azure/savings_plan/expiration/CHANGELOG.md
  cost/azure/savings_plan/expiration/README.md
  cost/azure/savings_plan/expiration/azure_savings_plan_expiration.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2663 POL-1364 Update Azure Savings Plan Expiration - Fix Policy Set value
  cost/azure/savings_plan/expiration/CHANGELOG.md
  cost/azure/savings_plan/expiration/azure_savings_plan_expiration.pt
Labels: READY-FOR-REVIEW, small fixes

#2638 POL-1356 AWS Rightsize EBS Volume: Type Filtering
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/README.md
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes.pt
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2639 POL-1357 Azure Hybrid Use Benefit Policy Actions
  cost/azure/hybrid_use_benefit/CHANGELOG.md
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
  cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit_meta_parent.pt
  cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
  cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
  cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2633 POL-1352 Outdated Applied Policies: Deprecated Policy Support
  .dangerfile/policy_tests.rb
  .spellignore
  automation/flexera/outdated_applied_policies/CHANGELOG.md
  automation/flexera/outdated_applied_policies/README.md
  automation/flexera/outdated_applied_policies/outdated_applied_policies.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2673 POL-1366 Currency Conversion: Add Arbitrary Dimension Support
  .spellignore
  cost/flexera/cco/currency_conversion/CHANGELOG.md
  cost/flexera/cco/currency_conversion/README.md
  cost/flexera/cco/currency_conversion/currency_conversion.pt
Labels: READY-FOR-REVIEW

#2657 POL-1363 AWS EC2 Compute Optimizer Recommendations: Additional Options
  cost/aws/ec2_compute_optimizer/CHANGELOG.md
  cost/aws/ec2_compute_optimizer/README.md
  cost/aws/ec2_compute_optimizer/aws_ec2_compute_optimizer.pt
  cost/aws/ec2_compute_optimizer/aws_ec2_compute_optimizer_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2644 POL-1359 AWS Reserved Instances Recommendations: DynamoDB Support
  cost/aws/reserved_instances/recommendations/CHANGELOG.md
  cost/aws/reserved_instances/recommendations/README.md
  cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#2620 POL-1347 - feat: refactor AWS, Azure, and Google Schedule Instance Policy Templates
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/README.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/README.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
  cost/google/schedule_instance/CHANGELOG.md
  cost/google/schedule_instance/README.md
  cost/google/schedule_instance/google_schedule_instance.pt
Labels: READY-FOR-REVIEW

#2688 POL-1368 AWS Superseded EBS Volumes - Update Name in Readme
  cost/aws/superseded_ebs_volumes/README.md
Labels: READY-FOR-REVIEW, small fixes

#2683 feat/disable_concurrency_update_active_policy_list_workflow
  .github/workflows/update-active-policy-list.yaml
Labels: READY-FOR-REVIEW

#2685 POL-1347 - fix: meta_parent_policy_compiler.rb no export block
  .dangerfile/policy_tests.rb
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/aws/schedule_instance/aws_schedule_instance_meta_parent.pt
  cost/azure/schedule_instance/azure_schedule_instance_meta_parent.pt
  cost/google/schedule_instance/CHANGELOG.md
  cost/google/schedule_instance/google_schedule_instance.pt
  cost/google/schedule_instance/google_schedule_instance_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#2692 POL-1370 Update AWS Instance Types JSON to include superseded instances for r, db.m, db.r families
  data/aws/instance_types.json
Labels: enhancement, READY-FOR-REVIEW, data

#2699 POL-1369 Dangerfile: README Name Test
  .dangerfile/policy_tests.rb
  Dangerfile
Labels: READY-FOR-REVIEW
