Repository flexera-public/policy_templates, pull requests merged in 2025-08, with the labels that each got.

#3372 POL-1571 AWS S3 Buckets Accepting HTTP Requests - fix 'cannot access member' error
  data/policy_permissions_list/master_policy_permissions_list.csv
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.pdf
  data/policy_permissions_list/master_policy_permissions_list.yaml
  data/policy_permissions_list/master_policy_permissions_list_aws.pdf
  data/policy_permissions_list/master_policy_permissions_list_azure.pdf
  data/policy_permissions_list/master_policy_permissions_list_google.pdf
  security/aws/s3_buckets_deny_http/CHANGELOG.md
  security/aws/s3_buckets_deny_http/s3_buckets_deny_http.pt
  security/aws/s3_buckets_deny_http/s3_buckets_deny_http_meta_parent.pt
Labels: READY-FOR-REVIEW, BUG FIX, MINOR UPDATE

#3352 FOPTS-12561 Fixed Incorrect Throughput for Azure Standard SSDs (E1-E50)
  data/azure/azure_md_tier_types.json
  tools/cloud_data/azure/azure_md_tier_types.py
Labels: READY-FOR-REVIEW, data, azure

#3413 FOPTS-12555 Fixed inconsistent type for "nfu" field.
  data/azure/azure_compute_instance_types.json
  tools/cloud_data/azure/azure_compute_instance_types.py
Labels: READY-FOR-REVIEW, BUG FIX

#3410 POL-1577 - fix: max/min selection method
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
Labels: READY-FOR-REVIEW, BUG FIX, MINOR UPDATE

#3455 POL-1575 Percentage Cost Common Bill Ingestion README Fixes
  cost/flexera/cco/percentage_cost_cbi/README.md
Labels: READY-FOR-REVIEW

#3451 FOAA-327 - Spot Ocean CBI - Add support for collecting Azure and GCP cluster cost data
  cost/flexera/spot/ocean_cbi/CHANGELOG.md
  cost/flexera/spot/ocean_cbi/spot_ocean_cbi.pt
Labels: READY-FOR-REVIEW, MINOR UPDATE, azure, google

#3446 FOPTS-12555 Use actual cost to calculate savings for AWS superseded instance policy
  cost/aws/superseded_instances/CHANGELOG.md
  cost/aws/superseded_instances/README.md
  cost/aws/superseded_instances/aws_superseded_instances.pt
  cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt
  cost/azure/superseded_instances/README.md
Labels: READY-FOR-REVIEW, MAJOR UPDATE
