Repository flexera-public/policy_templates, pull requests merged in 2025-04, with the labels that each got.

#3028 POL-1474 Automate Azure Instance Types JSON
  .github/workflows/generate-azure-compute-instance-types-json.yaml
  data/azure/azure_compute_instance_types.json
  requirements.txt
  tools/cloud_data/azure/azure_compute_instance_types.py
Labels: READY-FOR-REVIEW

#3029 POL-1473 Schedule ITAM Report: Add Truncated Date Option
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/itam/schedule_itam_report/CHANGELOG.md
  operational/flexera/itam/schedule_itam_report/README.md
  operational/flexera/itam/schedule_itam_report/images/APIToken.png
  operational/flexera/itam/schedule_itam_report/images/CMP_NewToken.png
  operational/flexera/itam/schedule_itam_report/images/CreateServeceAccount.png
  operational/flexera/itam/schedule_itam_report/images/WebServiceRole.png
  operational/flexera/itam/schedule_itam_report/images/itam_cv_report.png
  operational/flexera/itam/schedule_itam_report/images/report_number.png
  operational/flexera/itam/schedule_itam_report/schedule_itam_report.pt
Labels: READY-FOR-REVIEW

#3033 POL-1476 Fix Github Workflow
  .github/workflows/cfn-lint.yaml
  .github/workflows/cfn-publish.yaml
  .github/workflows/cfn-test.yaml
  .github/workflows/generate-aws-cloudformation-template.yaml
  .github/workflows/generate-aws-ec2-instance-types-json.yaml
  .github/workflows/generate-aws-ec2-pricing-json.yaml
  .github/workflows/generate-aws-rds-pricing-json.yaml
  .github/workflows/generate-azure-compute-instance-types-json.yaml
  .github/workflows/generate-azure-db-storage-pricing-json.yaml
  .github/workflows/generate-azure-md-pricing-json.yaml
  .github/workflows/generate-azure-sqlmi-storage-pricing-json.yaml
  .github/workflows/generate-azure-vm-pricing-json.yaml
  .github/workflows/generate-meta-parent-policy-templates.yaml
  .github/workflows/generate-policy-master-permission-missing-templates.yaml
  .github/workflows/generate-policy-master-permissions-json.yaml
  .github/workflows/generate-policy-release-notifications.yaml
  .github/workflows/generate-readme-policy-table-of-contents.yaml
  .github/workflows/test-policies.yaml
  .github/workflows/update-active-policy-list.yaml
  .github/workflows/update-aws-cloudformation-template.yaml
  .github/workflows/update-change-history.yaml
Labels: READY-FOR-REVIEW

#3038 POL-1477 Update Repository README Automation
  .github/workflows/generate-readme-policy-table-of-contents.yaml
  .spellignore
  Dangerfile
  README.md
  cost/google/cloudsql_rightsizing/CHANGELOG.md
  cost/google/cloudsql_rightsizing/google_cloudsql_rightsizing.pt
  cost/google/idle_compute_instances/CHANGELOG.md
  cost/google/idle_compute_instances/google_idle_compute_instances.pt
  tools/readme_policy_table_of_contents/FOOTER.md
  tools/readme_policy_table_of_contents/HEADER.md
  tools/readme_policy_table_of_contents/README.md
  tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Labels: READY-FOR-REVIEW

#2941 POL-1449 - Initial Spot Policy Templates
  compliance/flexera/spot/security_report/CHANGELOG.md
  compliance/flexera/spot/security_report/README.md
  compliance/flexera/spot/security_report/flexera_spot_security_report.pt
  cost/flexera/spot/ocean_cbi/CHANGELOG.md
  cost/flexera/spot/ocean_cbi/README.md
  cost/flexera/spot/ocean_cbi/spot_ocean_cbi.pt
  cost/flexera/spot/ocean_recommendations/CHANGELOG.md
  cost/flexera/spot/ocean_recommendations/README.md
  cost/flexera/spot/ocean_recommendations/spot_ocean_recommendations.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#3032 POL-1136 Automation Credential Policy Templates
  automation/flexera/disallowed_credentials/CHANGELOG.md
  automation/flexera/disallowed_credentials/README.md
  automation/flexera/disallowed_credentials/disallowed_credentials.pt
  automation/flexera/expiring_credentials/CHANGELOG.md
  automation/flexera/expiring_credentials/README.md
  automation/flexera/expiring_credentials/expiring_credentials.pt
  automation/flexera/outdated_applied_policies/CHANGELOG.md
  automation/flexera/outdated_applied_policies/outdated_applied_policies.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW

#2918 POL-1435 POL-1436 POL-1437 - feat: Schedule Instance PT Enhancements
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/README.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
Labels: enhancement, READY-FOR-REVIEW

#3071 task: add `publish: "false",`
  operational/flexera/cco/rbds_from_csv_in_policy_template/csv_for_rbds_from_csv.pt
  operational/flexera/cco/rbds_from_csv_in_policy_template/rbds_from_csv.pt
Labels: READY-FOR-REVIEW

#3080 POL-1506 Account RBD Policy Updates
  automation/aws/aws_rbd_from_tag/CHANGELOG.md
  automation/aws/aws_rbd_from_tag/README.md
  automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
  automation/azure/azure_rbd_from_rg_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_rg_tag/README.md
  automation/azure/azure_rbd_from_rg_tag/azure_rbd_from_rg_tag.pt
  automation/azure/azure_rbd_from_tag/CHANGELOG.md
  automation/azure/azure_rbd_from_tag/README.md
  automation/azure/azure_rbd_from_tag/azure_rbd_from_tag.pt
  automation/google/google_rbd_from_label/CHANGELOG.md
  automation/google/google_rbd_from_label/README.md
  automation/google/google_rbd_from_label/google_rbd_from_label.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#3073 POL-1503 Google VM Pricing Automation
  .github/workflows/generate-gcp-vm-pricing-json.yaml
  data/google/google_vm_pricing.json
  requirements.txt
  tools/cloud_data/google/google_vm_pricing.py
Labels: READY-FOR-REVIEW

#3097 POL-1511 CloudFormation Generator Fix
  tools/cloudformation-template/FlexeraAutomationPolicies.template
  tools/cloudformation-template/FlexeraAutomationPoliciesReadOnly.template
  tools/cloudformation-template/aws_cft_generator.rb
Labels: READY-FOR-REVIEW
