Repository flexera-public/policy_templates, pull requests merged in 2025-05, with the labels that each got.

#3089 POL-1508 - AWS and Google Scheduled Policy Enhancements
  cost/aws/schedule_instance/CHANGELOG.md
  cost/aws/schedule_instance/README.md
  cost/aws/schedule_instance/aws_schedule_instance.pt
  cost/azure/schedule_instance/CHANGELOG.md
  cost/azure/schedule_instance/azure_schedule_instance.pt
  cost/google/schedule_instance/CHANGELOG.md
  cost/google/schedule_instance/README.md
  cost/google/schedule_instance/google_schedule_instance.pt
Labels: READY-FOR-REVIEW

#3128 SQ-14908 Fix the error with Last 30 days parameter
  cost/flexera/cco/scheduled_report_unallocated/CHANGELOG.md
  cost/flexera/cco/scheduled_report_unallocated/scheduled_report_unallocated.pt
Labels: bug

#1807 POL-877 New Policy: Alibaba Cloud CBI
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  .spellignore
  cost/alibaba/alibaba_cbi/CHANGELOG.md
  cost/alibaba/alibaba_cbi/README.md
  cost/alibaba/alibaba_cbi/alibaba_cbi.pt
Labels: READY-FOR-REVIEW, New Policy

#3107 POL-1513 Azure NFUs in Instance Types JSON
  data/aws/README.md
  data/azure/README.md
  data/azure/azure_compute_instance_types.json
  tools/cloud_data/README.md
  tools/cloud_data/azure/azure_compute_instance_types.py
Labels: READY-FOR-REVIEW

#3092 POL-1480 AWS instance_types.json Policy Template Updates
  cost/aws/burstable_ec2_instances/CHANGELOG.md
  cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances.pt
  cost/aws/instance_cost_per_hour/CHANGELOG.md
  cost/aws/instance_cost_per_hour/aws_instance_cost_per_hour.pt
  cost/aws/rightsize_elasticache/CHANGELOG.md
  cost/aws/rightsize_elasticache/aws_rightsize_elasticache.pt
  cost/aws/rightsize_rds_instances/CHANGELOG.md
  cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt
  cost/aws/superseded_instances/CHANGELOG.md
  cost/aws/superseded_instances/aws_superseded_instances.pt
  operational/aws/total_instance_usage_forecast/CHANGELOG.md
  operational/aws/total_instance_usage_forecast/aws_total_instance_usage_forecast.pt
  operational/aws/total_instance_usage_report/CHANGELOG.md
  operational/aws/total_instance_usage_report/aws_total_instance_usage_report.pt
  security/aws/rds_publicly_accessible/CHANGELOG.md
  security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt
  security/aws/rds_unencrypted/CHANGELOG.md
  security/aws/rds_unencrypted/aws_unencrypted_rds_instances.pt
Labels: READY-FOR-REVIEW

#2954 POL-1446 - New Policy - MSP Usage Audit
  .spellignore
  operational/flexera/msp/customer_usage_insights_report/CHANGELOG.md
  operational/flexera/msp/customer_usage_insights_report/README.md
  operational/flexera/msp/customer_usage_insights_report/flexera_msp_customer_usage_insights_report.pt
Labels: READY-FOR-REVIEW, New Policy

#3143 POL-1522 Style Guide
  .dangerfile/general_tests.rb
  .dangerfile/policy_tests.rb
  .mdlrc
  .spellignore
  CONTRIBUTING.md
  README.md
  README_GUIDELINE.md
  STYLE_GUIDE.md
  VERSIONING.md
  tools/readme_policy_table_of_contents/FOOTER.md
  tools/readme_policy_table_of_contents/HEADER.md
Labels: READY-FOR-REVIEW

#3117 FOPTS-9434 Correctly include all RDS snapshots in policy evaluation
  cost/aws/old_snapshots/CHANGELOG.md
  cost/aws/old_snapshots/aws_delete_old_snapshots.pt
Labels: bug, READY-FOR-REVIEW

#3154 POL-1524 Currency Conversion Fix
  cost/flexera/cco/currency_conversion/CHANGELOG.md
  cost/flexera/cco/currency_conversion/currency_conversion.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#3149 POL-1523 Style Guide Improvements
  .dangerfile/changelog_tests.rb
  .dangerfile/general_tests.rb
  .dangerfile/github_tests.rb
  .dangerfile/policy_tests.rb
  .dangerfile/readme_tests.rb
  CONTRIBUTING.md
  README.md
  STYLE_GUIDE.md
  TROUBLESHOOTING.md
  tools/readme_policy_table_of_contents/FOOTER.txt
  tools/readme_policy_table_of_contents/HEADER.txt
  tools/readme_policy_table_of_contents/README.md
  tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Labels: READY-FOR-REVIEW

#3174 POL-1527 Azure Rightsize NetApp Resources - Correct Typo in Template Description
  cost/azure/rightsize_netapp/CHANGELOG.md
  cost/azure/rightsize_netapp/azure_rightsize_netapp.pt
Labels: READY-FOR-REVIEW, small fixes

#3181 POL-1529 Fixed Write Permissions in AWS Read Only CFT
  cost/aws/schedule_instance/README.md
  cost/aws/unused_volumes/README.md
  cost/azure/schedule_instance/README.md
  cost/google/schedule_instance/README.md
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/cloudformation-template/FlexeraAutomationPolicies.template
  tools/cloudformation-template/FlexeraAutomationPoliciesReadOnly.template
  tools/policy_master_permission_generation/generate_policy_master_permissions.rb
Labels: READY-FOR-REVIEW

#3156 FOPTS-9865 Performance improvement -- migrated to Metrics getBatch API call
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/README.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
Labels: READY-FOR-REVIEW, small fixes

#3180 POL-1528 DTU support for Azure Rightsize SQL Databases
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/README.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
Labels: READY-FOR-REVIEW

#3195 POL-1532 Catalog Update Teams Notifications Failing
  .github/workflows/generate-policy-release-notifications.yaml
  tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
Labels: READY-FOR-REVIEW
