Repository flexera-public/policy_templates, pull requests merged in 2025-07, with the labels that each got.

#3276 SQ-15559 Azure Superseded Compute Instances Reference Error
  cost/azure/superseded_instances/CHANGELOG.md
  cost/azure/superseded_instances/azure_superseded_instances.pt
  cost/azure/superseded_instances/azure_superseded_instances_meta_parent.pt
Labels: BUG FIX, MINOR UPDATE, javascript

#3280 SQ-16235 | Bill Processing Errors Notification | Add support for Azure CSP and Azure MCA Enterprise
  operational/flexera/cco/bill_processing_errors_notification/CHANGELOG.md
  operational/flexera/cco/bill_processing_errors_notification/bill_processing_errors_notification.pt
Labels: READY-FOR-REVIEW, MINOR UPDATE, javascript

#3296 POL-1557 CBI Policy Daily Granularity Support
  cost/flexera/cco/cbi_ingestion_aws_s3/CHANGELOG.md
  cost/flexera/cco/cbi_ingestion_aws_s3/README.md
  cost/flexera/cco/cbi_ingestion_aws_s3/cbi_ingestion_aws_s3.pt
  cost/flexera/cco/cbi_ingestion_azure_blob/CHANGELOG.md
  cost/flexera/cco/cbi_ingestion_azure_blob/README.md
  cost/flexera/cco/cbi_ingestion_azure_blob/cbi_ingestion_azure_blob.pt
Labels: READY-FOR-REVIEW, MINOR UPDATE

#3305 POL-1558 New Unpublished CBI Policy Templates
  cost/flexera/cco/cbi_ingestion_aws_s3_iterating/CHANGELOG.md
  cost/flexera/cco/cbi_ingestion_aws_s3_iterating/README.md
  cost/flexera/cco/cbi_ingestion_aws_s3_iterating/cbi_ingestion_aws_s3_iterating.pt
  cost/flexera/cco/cbi_ingestion_azure_blob_iterating/CHANGELOG.md
  cost/flexera/cco/cbi_ingestion_azure_blob_iterating/README.md
  cost/flexera/cco/cbi_ingestion_azure_blob_iterating/cbi_ingestion_azure_blob_iterating.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, NEW POLICY TEMPLATE, UNPUBLISHED

#3331 SQ-16516 Removed "ITAM VMs Missing Host ID" policy
  compliance/flexera/fnms/vms_missing_hostid/CHANGELOG.md
  compliance/flexera/fnms/vms_missing_hostid/README.md
  compliance/flexera/fnms/vms_missing_hostid/vms_missing_hostid.pt
  data/policy_permissions_list/master_policy_permissions_list.csv
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, UNPUBLISHED

#3345 POL-1563 Style Guide: Incident Design
  STYLE_GUIDE.md
Labels: READY-FOR-REVIEW

#3365 POL-1570 Meta Parent: Added Hourly/15 Minute Options
  tools/meta_parent_policy_compiler/aws_meta_parent.pt.template
  tools/meta_parent_policy_compiler/azure_meta_parent.pt.template
  tools/meta_parent_policy_compiler/google_meta_parent.pt.template
Labels: READY-FOR-REVIEW
