Repository flexera-public/policy_templates, pull requests merged in 2025-03, with the labels that each got.

#2967 FOPTS-7572 Changed the way to calculate used memory | Policy: Azure Rightsize Compute Instances
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Labels: bug, READY-FOR-REVIEW, READY FOR APPROVAL, small fixes

#2965 FOPTS-6833 - Batch Processing Adoption for Azure RightSize Policies
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
  cost/azure/rightsize_managed_disks/CHANGELOG.md
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
  cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
  cost/azure/rightsize_sql_instances/CHANGELOG.md
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
  cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
Labels: enhancement, READY-FOR-REVIEW

#2976 FOPTS-7572 Fixed memory stats showing decimal instead of percentage | Policy: Azure Rightsize Compute Instances
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Labels: bug, READY-FOR-REVIEW, READY FOR APPROVAL, small fixes

#2950 POL-1448 New Policy: FinOps Dashboards
  data/dashboards/finops_business_product.json
  data/dashboards/finops_engineering_operations.json
  data/dashboards/finops_executive_summary.json
  data/dashboards/finops_finance_procurement.json
  data/dashboards/finops_global_cio_ytd_view.json
  data/dashboards/finops_marketplace.json
  data/dashboards/finops_reservation_coverage.json
  data/dashboards/finops_reservation_management.json
  data/policy_permissions_list/master_policy_permissions_list.json
  data/policy_permissions_list/master_policy_permissions_list.yaml
  operational/flexera/cco/finops_dashboards/CHANGELOG.md
  operational/flexera/cco/finops_dashboards/README.md
  operational/flexera/cco/finops_dashboards/finops_dashboards.pt
  tools/policy_master_permission_generation/validated_policy_templates.yaml
Labels: READY-FOR-REVIEW, New Policy

#2996 FOPTS-8007 Fixed OAuth authentication for `Common Bill Ingestion from Azure Blob Storage` policy
  cost/flexera/cco/cbi_ingestion_azure_blob/CHANGELOG.md
  cost/flexera/cco/cbi_ingestion_azure_blob/cbi_ingestion_azure_blob.pt
Labels: bug, READY-FOR-REVIEW, READY FOR APPROVAL, small fixes

#3003 POL-1464 Meta Policy Fix
  cost/aws/schedule_instance/aws_schedule_instance_meta_parent.pt
  cost/azure/schedule_instance/azure_schedule_instance_meta_parent.pt
  cost/google/schedule_instance/google_schedule_instance_meta_parent.pt
  tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Labels: READY-FOR-REVIEW

#3006 SQ-12222 Fixed incorrect calculation for "average used memory"
  cost/azure/rightsize_compute_instances/CHANGELOG.md
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
  cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
Labels: bug, READY-FOR-REVIEW, READY FOR APPROVAL, small fixes

#3005 FOPTS-6901 - Batch Processing Adoption for AWS Rightsize EBS Volumes
  cost/aws/rightsize_ebs_volumes/CHANGELOG.md
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes.pt
  cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes_meta_parent.pt
Labels: READY-FOR-REVIEW

#3014 POL-1468 Bug/fixing retired status in results ITAM Expiring Licenses
  compliance/flexera/fnms/fnms_licenses_expiring/CHANGELOG.md
  compliance/flexera/fnms/fnms_licenses_expiring/expiring_licenses.pt
Labels: bug, READY-FOR-REVIEW, small fixes

#3023 POL-1471 Fix CodeQL Security Issues
  .github/workflows/cfn-lint.yaml
  .github/workflows/cfn-publish.yaml
  .github/workflows/cfn-test.yaml
  .github/workflows/generate-aws-cloudformation-template.yaml
  .github/workflows/generate-aws-ec2-pricing-json.yaml
  .github/workflows/generate-aws-rds-pricing-json.yaml
  .github/workflows/generate-azure-db-storage-pricing-json.yaml
  .github/workflows/generate-azure-md-pricing-json.yaml
  .github/workflows/generate-azure-sqlmi-storage-pricing-json.yaml
  .github/workflows/generate-azure-vm-pricing-json.yaml
  .github/workflows/generate-meta-parent-policy-templates.yaml
  .github/workflows/generate-policy-master-permission-missing-templates.yaml
  .github/workflows/generate-policy-master-permissions-json.yaml
  .github/workflows/generate-policy-release-notifications.yaml
  .github/workflows/generate-readme-policy-table-of-contents.yaml
  .github/workflows/test-policies.yaml
  .github/workflows/update-active-policy-list.yaml
  .github/workflows/update-aws-cloudformation-template.yaml
  .github/workflows/update-change-history.yaml
  tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
  tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Labels: READY-FOR-REVIEW

#3027 POL-1472 Fix Broken Link in CFT README.md
  tools/cloudformation-template/README.md
Labels: READY-FOR-REVIEW
